#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  Испанский: слова программы и слова погоды.
#  Часть проекта EOne screen.
#
#  Автор: EOne
#  Лицензия: CC BY-NC-SA 4.0 — использование в коммерческих целях
#  запрещено без письменного разрешения автора. См. файл LICENSE.
#
"""yazyk_es.py - испанский.

Три таблицы, и все три необязательные: чего здесь нет, то берётся
по-английски, а окно всё равно откроется.

    SLOVAR       надписи окна: русская строка -> испанская
    POGODA       коды погоды ВМО: код -> (коротко, полно)
    SOKRASHENO   те коды, где полное описание слишком длинное для панели

Ключ в SLOVAR - РУССКАЯ строка ровно как в yazyk.py: она и есть имя
надписи. Английский перевод там же, рядом, - на него можно смотреть,
но переводить надо с русского.

ПЕРЕВОД СДЕЛАН С ПОМОЩЬЮ ИИ и носителем языка не проверялся. Русский
и английский написаны автором, остальные пять - нет. Если вы говорите
на этом языке и видите ошибку или корявость, поправьте: строку можно
менять прямо здесь, ключ трогать нельзя.
"""

# Надписи окна. Заполняется отдельно: строк много, а панель работает
# и без них - см. шапку.
SLOVAR = {
    # Готовые надписи, которые всегда по-английски:
    # они просят {weather_en}, а не {weather}.
    "Weather short  Rain": "Clima breve, siempre en inglés  Rain",
    "Weather full  Light rain": "Clima detallado, siempre en inglés  Light rain",
    "Weather and temperature  Rain  12 °C": "Clima y temperatura, siempre en inglés  Rain  12 °C",
    "Weather full and temperature": "Clima detallado y temperatura, siempre en inglés",
    "Weather: feels like  10 °C": "Clima: sensación térmica, siempre en inglés  10 °C",
    "Weather: wind  4 km/h": "Clima: viento, siempre en inglés  4 km/h",
    "Weather: humidity  78 %": "Clima: humedad, siempre en inglés  78 %",
    "Weather: everything": "Clima: todo junto, siempre en inglés",
    # Значения движка: подпись видит человек, а в тему уходит
    # русское слово - его подставляет сама программа.
    "плавно": "suave",
    "средне": "medio",
    "резко": "brusco",

    'Главная': 'Inicio',
    'Темы': 'Temas',
    'Настройки': 'Ajustes',
    'экран водянки': 'pantalla del refrigerador líquido',
    'экран выключен': 'pantalla apagada',
    'экран: {} · {:.0f} кадр/с': 'pantalla: {} · {:.0f} fps',
    'переход {:.0f} с': 'transición {:.0f} s',
    'тема отправлена на экран': 'tema enviado a la pantalla',
    'перезапускаю экран…': 'reiniciando la pantalla…',
    'сбой обновления: {}': 'fallo al actualizar: {}',
    '{} — экран выключен': '{} — pantalla apagada',
    '{} — {} ({:.1f} кадр/с, {})': '{} — {} ({:.1f} fps, {})',
    'Включить или выключить экран': 'Encender o apagar la pantalla',
    'Показать окно': 'Mostrar la ventana',
    'Выход': 'Salir',
    'Пауза': 'Pausa',
    'Продолжить': 'Reanudar',
    'Перечитать тему': 'Releer el tema',
    '{} · {} — {} ({:.1f} кадр/с, тема {})': '{} · {} — {} ({:.1f} fps, tema {})',
    'по солнцу': 'según el sol',
    'как в Windows': 'como en Windows',
    'всегда ночная': 'siempre nocturna',
    'всегда дневная': 'siempre diurna',
    'запускается': 'iniciando',
    'остановлена': 'detenida',
    'на паузе': 'en pausa',
    'слишком много сбоев': 'demasiados fallos',
    'Сохранить правки?': '¿Guardar los cambios?',
    'Несохранённые правки пропадут. Продолжить?': 'Se perderán los cambios sin guardar. ¿Continuar?',
    'Это не похоже на тему: нет слоёв.': 'Esto no parece un tema: no tiene capas.',
    'Моя тема': 'Mi tema',
    'Сейчас на экране': 'Ahora en la pantalla',
    'Что показывать': 'Qué mostrar',
    'Погода на экране': 'Clima en la pantalla',
    'Включить экран': 'Encender la pantalla',
    'Выключить экран': 'Apagar la pantalla',
    'Перезапустить': 'Reiniciar',
    'выключен': 'apagado',
    'работает': 'en marcha',
    'работает · {:.0f} кадр/с': 'en marcha · {:.0f} fps',
    '(прогноз не пришёл)': '(no ha llegado el pronóstico)',
    'готовлю кадры фона': 'preparando los fotogramas de fondo',
    'тема: ': 'tema: ',
    'погода': 'clima',
    'днём': 'de día',
    'ночью': 'de noche',
    'восход {}   закат {}   сейчас {:.0f} % дня': 'amanecer {}   atardecer {}   ahora {:.0f} % del día',
    '   (прогноз не пришёл)': '   (sin pronóstico aún)',
    'отправлено кадров {}': 'fotogramas enviados {}',
    'сбоев {}': 'fallos {}',
    '{:g} кадр/с': '{:g} fps',
    'не удалось собрать кадр: {}': 'no se pudo montar el fotograma: {}',
    'кадры фона не листаются, чтобы окно не тратило лишнего': 'los fotogramas de fondo no se reproducen aquí, para no gastar recursos de más',
    'Начать или прекратить вывод картинки на экран водянки.': 'Empezar o detener el envío de la imagen a la pantalla del refrigerador líquido.',
    'Придержать вывод, не закрывая порт. Экран замрёт на последнем кадре.': 'Detener el envío sin cerrar el puerto. La pantalla se queda congelada en el último fotograma.',
    'Заново открыть порт и поздороваться с экраном. Выручает, если картинка сбилась или порт подвис.': 'Volver a abrir el puerto y saludar a la pantalla. Ayuda cuando la imagen se desajusta o el puerto se cuelga.',
    'Яркость подсветки экрана водянки. Уходит на экран, когда отпустишь ползунок.': 'Brillo de la retroiluminación de la pantalla del refrigerador líquido. Se aplica al soltar el control deslizante.',
    'По солнцу': 'Según el sol',
    'Как в Windows': 'Como en Windows',
    'Ночь': 'Noche',
    'День': 'Día',
    'Светлеет на рассвете и темнеет на закате, по времени восхода и заката в твоём городе.': 'Se aclara al amanecer y se oscurece al atardecer, según la hora del amanecer y el atardecer en tu ciudad.',
    'Следит за оформлением Windows: светлая тема — дневной вид, тёмная — ночной.': 'Sigue el tema de Windows: claro es la vista de día, oscuro la de noche.',
    'Всегда ночной вид, независимо от времени.': 'Siempre la vista de noche, sin importar la hora.',
    'Всегда дневной вид, независимо от времени.': 'Siempre la vista de día, sin importar la hora.',
    'По прогнозу': 'Según el pronóstico',
    'Ясно': 'Despejado',
    'Пасмурно': 'Nublado',
    'Дождь': 'Lluvia',
    'Гроза': 'Tormenta',
    'Снег': 'Nieve',
    'Метель': 'Ventisca',
    'Туман': 'Niebla',
    'Мороз': 'Helada',
    'Жара': 'Calor',
    'Показывать настоящий прогноз.': 'Mostrar el pronóstico real.',
    'Показать «{}» так, будто оно за окном: {:+.0f} {}, ветер {:.0f} {}. Прогноз никуда не девается.': 'Mostrar «{}» como si estuviera fuera: {:+.0f} {}, viento {:.0f} {}. El pronóstico no se pierde.',
    'Показывать дождь, снег, туман и грозу на дневной теме.': 'Mostrar lluvia, nieve, niebla y tormentas en el tema de día.',
    'То же на ночной. Звёзды и метеоры останутся в любом случае.': 'Lo mismo de noche. Las estrellas y meteoros se quedan de todos modos.',
    '{}: {}, {:.0f} {}, ветер {:.0f} {}   ·   небо — {}': '{}: {}, {:.0f} {}, viento {:.0f} {}   ·   cielo — {}',
    'км/ч': 'km/h',
    'м/с': 'm/s',
    'миль/ч': 'mi/h',
    'выдумано': 'inventado',
    'за окном': 'fuera',
    'нет данных': 'sin datos',
    'ничего': 'nada',
    'ясно': 'despejado',
    'облака': 'nubes',
    'серость': 'gris',
    'дождь': 'lluvia',
    'снег': 'nieve',
    'гроза': 'tormenta',
    'туман': 'niebla',
    'Мои темы': 'Mis temas',
    'Создать тему': 'Crear tema',
    'Редактор': 'Editor',
    'Всё, что лежит рядом с программой. Отсюда тему отправляют на экран, правят, копируют и упаковывают для пересылки.': 'Todo lo que está junto al programa. Desde aquí el tema se envía a la pantalla, se edita, se copia y se empaqueta para enviarlo.',
    'Обновить': 'Actualizar',
    'Из папки…': 'Desde una carpeta…',
    'Из архива…': 'Desde un archivo…',
    'На экран': 'A la pantalla',
    'Изменить': 'Editar',
    'Открыть в редакторе': 'Abrir en el editor',
    'Переименовать': 'Renombrar',
    'открыта': 'abierta',
    'нет предпросмотра': 'sin vista previa',
    '{} слоёв · {} · {:g} кадр/с': '{} capas · {} · {:g} fps',
    'автор: {}   ·   {}': 'autor: {}   ·   {}',
    'Сделать эту тему текущей: она уйдёт на экран водянки и откроется на главной.': 'Hacer este tema el actual: pasará a la pantalla del refrigerador líquido y se abrirá en el inicio.',
    'Открыть тему в редакторе: слои, надписи, цвета, дневной и ночной вид.': 'Abrir el tema en el editor: capas, textos, colores, vista de día y de noche.',
    'Сменить название темы. Папка на диске получит то же имя — тема и папка ходят вместе.': 'Cambiar el nombre del tema. La carpeta en el disco recibirá el mismo nombre — tema y carpeta van juntos.',
    'Название, автор и пояснение к теме. Эти строки уедут вместе с ней к другому человеку. Название меняет и имя папки на диске.': 'Nombre, autor y descripción del tema. Estos datos viajan con el tema a otra persona. El nombre también cambia el de la carpeta en el disco.',
    'Копия темы целиком, вместе с кадрами и шрифтами. Спросит имя. Оригинал не пострадает.': 'Una copia completa del tema, con fotogramas y fuentes. Pedirá un nombre. El original no se toca.',
    'Упаковать тему в один файл, чтобы переслать. Всё, на что она ссылается, попадёт внутрь.': 'Empaquetar el tema en un solo archivo para enviarlo. Todo lo que usa queda incluido dentro.',
    'Картинка для показа: ночь и день рядом, с именем, автором и списком умений. Чтобы выложить или прислать.': 'Una imagen para presumir el tema: noche y día uno junto al otro, con el nombre, el autor y lo que sabe hacer. Para publicar o enviar.',
    'Убрать тему из витрины. Папка остаётся на диске и переименовывается с точки — вернуть можно в проводнике.': 'Quitar el tema del catálogo. La carpeta se queda en el disco y se le añade un punto delante — se puede recuperar desde el Explorador.',
    'Новая тема': 'Tema nuevo',
    'Как её назвать?': '¿Cómo lo llamamos?',
    'Переименовать тему': 'Renombrar el tema',
    'Новое название:': 'Nuevo nombre:',
    'Копия темы': 'Copia del tema',
    'Как назвать копию?': '¿Cómo llamamos a la copia?',
    'Копирую тему': 'Copiando el tema',
    ' — копия': ' — copia',
    'Скопировать': 'Copiar',
    'Создать': 'Crear',
    'Отмена': 'Cancelar',
    'Сохранить': 'Guardar',
    'Упаковываю тему': 'Empaquetando el tema',
    'Упаковать тему': 'Empaquetar el tema',
    'Куда упаковать тему': 'Dónde empaquetar el tema',
    'Архив с темой': 'Archivo del tema',
    'Папка с темой': 'Carpeta del tema',
    'В папке нет описания темы.': 'En la carpeta no hay descripción del tema.',
    'Распаковываю тему': 'Desempaquetando el tema',
    'Открыть архив': 'Abrir el archivo',
    'Тема добавлена. Открыть её?': 'Tema añadido. ¿Abrirlo?',
    'Картинка для показа': 'Imagen para mostrar',
    'Убрать тему': 'Quitar el tema',
    'Эта тема сейчас открыта. Откройте другую и попробуйте снова.': 'Este tema está abierto ahora mismo. Abre otro e inténtalo de nuevo.',
    'Убрать «{}» из витрины?\n\nПапка останется на диске — она просто получит точку в начале имени. Вернуть можно переименованием в проводнике.': '¿Quitar «{}» del catálogo?\n\nLa carpeta se quedará en el disco — solo recibirá un punto al principio del nombre. Se puede recuperar renombrándola desde el Explorador.',
    'Готово, файлов внутри: {}.\n{}\n\nПоказать в папке?': 'Listo, archivos dentro: {}.\n{}\n\n¿Mostrar en la carpeta?',
    'Готово:\n{}\n\nОткрыть копию?': 'Listo:\n{}\n\n¿Abrir la copia?',
    'Готово:\n{}\n\nОткрыть её?': 'Listo:\n{}\n\n¿Abrirla?',
    'Описание темы': 'Descripción del tema',
    'Что увидят другие': 'Qué verán los demás',
    'эти строки уедут вместе с темой': 'estos datos viajan con el tema',
    'Название': 'Nombre',
    'Автор': 'Autor',
    'Описание': 'Descripción',
    '{} из {}   {}': '{} de {}   {}',
    'имя не может быть пустым': 'el nombre no puede estar vacío',
    'в архиве нет описания темы': 'el archivo no tiene descripción del tema',
    'без названия': 'sin nombre',
    'тема': 'tema',
    'День и ночь': 'Día y noche',
    'Картинки': 'Imágenes',
    'Движение': 'Movimiento',
    'Погода': 'Clima',
    'Видео': 'Gráficos',
    'Процессор': 'Procesador',
    'Осмотр машины': 'Revisión del equipo',
    'что на этой машине есть, что отвечает и чего не хватает': 'qué tiene este equipo, qué responde y qué falta',
    'Что на этой машине': 'Qué tiene este equipo',
    'те же проверки, что делает start.bat перед первым запуском. Опрос датчиков занимает несколько секунд.': 'las mismas comprobaciones que hace start.bat antes del primer arranque. Consultar los sensores tarda unos segundos.',
    'что на этой машине отвечает, а что молчит. Опрос датчиков занимает несколько секунд.': 'qué responde en este equipo y qué se queda callado. Consultar los sensores tarda unos segundos.',
    'Осмотреть': 'Revisar',
    '  смотрю…': '  revisando…',
    'Осмотр ещё не делался.': 'Aún no se ha revisado.',
    'всё в порядке': 'todo en orden',
    'важных замечаний: {}': 'avisos importantes: {}',
    'команда в буфере обмена': 'el comando está en el portapapeles',
    'не вышло': 'no funcionó',
    'Оформление программы': 'Aspecto del programa',
    'Единицы и время': 'Unidades y hora',
    'Сборка кадра': 'Montaje del fotograma',
    'это про машину, а не про тему: настройка остаётся при смене темы': 'esto es del equipo, no del tema: el ajuste se mantiene al cambiar de tema',
    'В один поток': 'En un hilo',
    'В два потока': 'En dos hilos',
    'В четыре': 'En cuatro',
    'Пусть решит сама': 'Automático',
    'Кадр собирается кусками, и куски друг о друге не знают — их можно готовить разом. Картинка выходит та же до последней точки, проверено. Но выигрыш во времени невелик и на быстрой машине теряется в разбросе: если панель и так укладывается в отпущенное время, кадров в секунду не прибавится. Смысл — уложиться на слабой машине.': 'El fotograma se arma en trozos, y los trozos no saben nada unos de otros — se pueden preparar a la vez. La imagen sale igual hasta el último punto, está comprobado. Pero la ganancia de tiempo es pequeña, y en un equipo rápido se pierde en el margen: si el panel ya cumple con el tiempo asignado, no habrá más fotogramas por segundo. La idea es ajustarse en un equipo modesto.',
    'в чём показывать градусы, время и дату — и в окне, и на экране': 'en qué mostrar los grados, la hora y la fecha — tanto en la ventana como en la pantalla',
    'Градусы': 'Grados',
    'Ветер': 'Viento',
    'и в окне, и в надписях на экране': 'tanto en la ventana como en los textos de la pantalla',
    'и температура железа, и погода': 'tanto la temperatura del hardware como el clima',
    'Цельсий': 'Celsius',
    'Фаренгейт': 'Fahrenheit',
    'Часы': 'Reloj',
    'двенадцать часов дописывают AM и PM': 'el de doce horas añade AM y PM',
    '24 часа': '24 horas',
    '12 часов': '12 horas',
    'Порядок чисел в дате': 'Orden de los números en la fecha',
    'день, месяц и год': 'día, mes y año',
    'Неделя начинается': 'La semana empieza',
    'по этому дню тема считает номер дня': 'el tema cuenta el número de día a partir de este',
    'с понедельника': 'el lunes',
    'с воскресенья': 'el domingo',
    'Как это будет выглядеть': 'Cómo se verá',
    'по умолчанию всё берётся из самой Windows: какие единицы и форматы там выбраны, такие и здесь': 'por defecto todo se toma de Windows: las unidades y formatos elegidos allí son los que se usan aquí',
    'Тема может брать готовые {time}, {date} и {deg} — они идут по этой настройке. А может писать свой вид через {now:…} — тогда настройка его не тронет.': 'El tema puede usar los ya hechos {time}, {date} y {deg} — siguen este ajuste. O puede escribir su propio formato con {now:…} — entonces el ajuste no lo toca.',
    'Запуск': 'Arranque',
    'Датчики': 'Sensores',
    'Погода и адрес': 'Clima y dirección',
    'Производительность': 'Rendimiento',
    'О программе': 'Acerca de',
    'кто это написал и на каких условиях этим можно пользоваться': 'quién lo escribió y en qué condiciones se puede usar',
    'как выглядит само окно программы, а не картинка на экране': 'cómo se ve la ventana del programa, no la imagen de la pantalla',
    'что делать при включении компьютера и при закрытии окна': 'qué hacer al encender el equipo y al cerrar la ventana',
    'откуда берутся значения и что из этого читается сейчас': 'de dónde vienen los valores y qué se está leyendo ahora',
    'чем платим за плавность: памятью, процессором, качеством': 'qué se paga por la fluidez: memoria, procesador, calidad',
    'откуда брать прогноз, восход и закат': 'de dónde tomar el pronóstico, el amanecer y el atardecer',
    'Светлое или тёмное': 'Claro u oscuro',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за темой панели.': '«Como en Windows» sigue el aspecto del sistema, «Como en la pantalla» sigue el tema del panel.',
    'Как на экране': 'Como en la pantalla',
    'Светлое': 'Claro',
    'Тёмное': 'Oscuro',
    'Язык': 'Idioma',
    'Смена языка': 'Cambio de idioma',
    'В теме есть несохранённые правки. Сохранить их?': 'El tema tiene cambios sin guardar. ¿Guardarlos?',
    'Изменения применятся при следующем запуске.': 'Los cambios se aplicarán la próxima vez que se inicie el programa.',
    'Ярлык на рабочем столе': 'Acceso directo en el escritorio',
    'чтобы запускать не из папки, а с рабочего стола': 'para iniciarlo desde el escritorio y no desde la carpeta',
    'Не получилось. Рабочий стол может быть закрыт для записи.': 'No funcionó. Puede que el escritorio no permita escritura.',
    'Запускать вместе с Windows': 'Iniciar con Windows',
    'через app.bat, чтобы поднялись права на температуру': 'a través de app.bat, para obtener permisos de temperatura',
    'Язык темы': 'Idioma del tema',
    'Как в окне': 'Igual que la ventana',
    'на нём говорит панель на экране водянки: погода, подпись ветра, названия слоёв в редакторе': 'en este idioma habla el panel de la pantalla del refrigerador líquido: el clima, la unidad del viento, los nombres de las capas en el editor',
    'Запускать при входе в систему': 'Iniciar al entrar en el sistema',
    'записью .desktop в автозапуске': 'con un archivo .desktop en el autoarranque',
    'Открывать сразу свёрнутым в трей': 'Abrir minimizado en la bandeja',
    'окно не мешает, панель работает': 'la ventana no estorba, el panel sigue funcionando',
    'Сразу включать экран': 'Encender la pantalla de inmediato',
    'не нажимать кнопку каждый раз': 'sin pulsar el botón cada vez',
    'Крестик прячет в трей, а не закрывает': 'La X oculta en la bandeja en lugar de cerrar',
    'иначе панель погаснет вместе с окном': 'si no, el panel se apaga junto con la ventana',
    'Автозапуск': 'Autoarranque',
    'Не удалось изменить запись в реестре.': 'No se pudo modificar la entrada del registro.',
    'Что опрашивать': 'Qué consultar',
    'выключенный источник не опрашивается вообще — это и есть экономия': 'una fuente apagada no se consulta en absoluto — en eso está el ahorro',
    'Что читается прямо сейчас': 'Qué se está leyendo ahora mismo',
    'значения как есть, до перевода в выбранные единицы: температуры здесь всегда в Цельсиях, на них настраивается реакция слоёв': 'los valores tal cual, antes de convertirlos a las unidades elegidas: aquí las temperaturas siempre están en Celsius, y sobre ellas se ajusta la reacción de las capas',
    'Процессор, память, диски, сеть': 'Procesador, memoria, discos, red',
    'почти бесплатно': 'casi gratis',
    'Видеокарта': 'Tarjeta gráfica',
    'через nvidia-smi': 'mediante nvidia-smi',
    'Температуры': 'Temperaturas',
    'нужны права администратора': 'requiere permisos de administrador',
    'их отдаёт само ядро': 'las da el propio núcleo',
    'через nvidia-smi или /sys/class/drm': 'mediante nvidia-smi o /sys/class/drm',
    'Погода, восход и закат': 'Clima, amanecer y atardecer',
    'нужен интернет': 'requiere internet',
    'Место': 'Ubicación',
    'по нему берётся прогноз, а заодно время восхода и заката — от них панель светлеет и темнеет': 'según esta se toma el pronóstico, y también la hora del amanecer y el atardecer — con ellas el panel se aclara y se oscurece',
    'Название города на любом языке. Нажми «Найти» и выбери из списка.': 'Nombre de la ciudad en cualquier idioma. Pulsa «Buscar» y elige de la lista.',
    'Найти': 'Buscar',
    'По адресу в сети': 'Por dirección de red',
    'Выбрать это место': 'Usar esta ubicación',
    '  ищу…': '  buscando…',
    '  ничего не нашлось': '  no se encontró nada',
    '  не вышло: {}': '  no funcionó: {}',
    'место: {}': 'ubicación: {}',
    'Сейчас: {}   ({:.3f}, {:.3f}) {}': 'Ahora: {}   ({:.3f}, {:.3f}) {}',
    'Место не выбрано — прогноза не будет, а восход и закат возьмутся запасные: 07:00 и 20:00.': 'No se ha elegido ubicación — no habrá pronóstico, y el amanecer y el atardecer usarán los valores de reserva: 07:00 y 20:00.',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за тем, день сейчас на панели или ночь.': '«Como en Windows» sigue el aspecto del sistema, «Como en la pantalla» sigue si el panel está en su vista de día o de noche.',
    'Сейчас: {}   ({:.3f}, {:.3f})\n{}': 'Ahora: {}   ({:.3f}, {:.3f})\n{}',
    'ночь': 'noche',
    'и день': 'y día',
    'Проверить, как тема выглядит в дождь или метель, можно на главной — ряд справа от выбора дня и ночи.': 'Para ver cómo se ve el tema con lluvia o ventisca, usa la página de inicio — la fila a la derecha de la elección de día y noche.',
    'Источник прогноза': 'Fuente del pronóstico',
    'Без ключа и без регистрации': 'Sin clave ni registro',
    'По ключу службы': 'Con la clave del servicio',
    'свой источник': 'fuente propia',
    'Где что лежит в ответе': 'Dónde está cada cosa en la respuesta',
    'В адресе можно писать {lat}, {lon} и {key} — программа подставит место и ключ. Нажмите «Спросить службу»: ответ разберётся на пути, и останется выбрать нужные из списков.': 'En la dirección puedes escribir {lat}, {lon} y {key} — el programa pondrá la ubicación y la clave. Pulsa «Preguntar al servicio»: la respuesta se descompone en rutas, y solo queda elegir las que hacen falta en las listas.',
    'Спросить службу': 'Preguntar al servicio',
    'Температура': 'Temperatura',
    'Состояние погоды числом': 'Estado del clima como número',
    'Ощущается как': 'Sensación térmica',
    'Влажность': 'Humedad',
    'Минимум за сутки': 'Mínima del día',
    'Максимум за сутки': 'Máxima del día',
    'Восход': 'Amanecer',
    'Закат': 'Atardecer',
    'Ветер в': 'Viento en',
    'Восход записан как': 'El amanecer está escrito como',
    'iso — 2026-08-13T05:08, unix — число секунд, 12h — 05:08 AM, 24h — 05:08': 'iso — 2026-08-13T05:08, unix — número de segundos, 12h — 05:08 AM, 24h — 05:08',
    'Числа состояния': 'Números de estado',
    'wmo — служба уже отдаёт коды по стандарту ВМО. Своя таблица чисел прописывается в weather.json, см. справочник.': 'wmo — el servicio ya entrega los códigos del estándar WMO. Tu propia tabla de números se define en weather.json, consulta el manual.',
    'служба ответила, полей нашлось: {}. Выберите нужные из списков и нажмите «Проверить».': 'el servicio respondió, campos encontrados: {}. Elige los que necesites en las listas y pulsa «Comprobar».',
    'Впишите адрес службы.': 'Escribe la dirección del servicio.',
    'по умолчанию Open-Meteo: без ключа и без регистрации. Другие службы отвечают по-своему, поэтому у каждой свой переходник — выберите нужную, и программа сама переведёт её ответ в понятный панели вид.': 'por defecto Open-Meteo: sin clave ni registro. Otros servicios responden a su manera, así que cada uno tiene su propio adaptador — elige el que necesites, y el programa traducirá su respuesta a un formato que el panel entienda.',
    'Ключ': 'Clave',
    'Ключ выдаёт сама служба при регистрации. Он хранится в weather.json рядом с программой.': 'La clave la da el propio servicio al registrarte. Se guarda en weather.json junto al programa.',
    'Адрес': 'Dirección',
    'Пусто — обычный адрес выбранной службы. Свой нужен для зеркала или своего сервера: полный адрес без вопросов и параметров, их программа допишет сама.': 'Vacío — la dirección habitual del servicio elegido. Uno propio hace falta para un espejo o tu propio servidor: la dirección completa sin signo de interrogación ni parámetros, el programa los añade solo.',
    'Проверить': 'Comprobar',
    'Обычный': 'Normal',
    '  спрашиваю…': '  preguntando…',
    'Сначала выберите место — без него спрашивать не о чем.': 'Elige primero una ubicación — sin ella no hay nada que preguntar.',
    '{} отвечает: {}, {:.0f} {}, ветер {:.0f} {}. Записано.': '{} responde: {}, {:.0f} {}, viento {:.0f} {}. Guardado.',
    '\nВосхода и заката эта служба не даёт — считаем их сами по координатам.': '\nEste servicio no da amanecer ni atardecer — los calculamos nosotros mismos a partir de las coordenadas.',
    'Не отвечает или отвечает не тем: {}': 'No responde, o responde con algo distinto: {}',
    'Картинка и нагрузка': 'Imagen y carga',
    'эти значения хранятся внутри темы': 'estos valores se guardan dentro del tema',
    'Кадров в секунду': 'Fotogramas por segundo',
    'ниже 0.5 нельзя: экран уснёт': 'no puede ser menor de 0.5: la pantalla se dormiría',
    'Качество JPEG': 'Calidad JPEG',
    '1–100, влияет на размер кадра': '1–100, afecta al tamaño del fotograma',
    'Сглаживание': 'Suavizado',
    '2 или 3, больше — плавнее края': '2 o 3, cuanto más alto, bordes más suaves',
    'Переход день/ночь, секунд': 'Transición día/noche, segundos',
    'сколько длится смена вида': 'cuánto dura el cambio de vista',
    'Сжимать кадры фона в памяти': 'Comprimir los fotogramas de fondo en memoria',
    'Сжатие без потерь: картинка та же до последнего бита, памяти уходит втрое меньше. Плата — около семи десятых миллисекунды на кадр. Переключение заставляет заново разобрать все кадры фона: на тяжёлой теме экран замрёт на несколько секунд.': 'Compresión sin pérdidas: la imagen es la misma hasta el último bit, y ocupa tres veces menos memoria. El coste es de unas siete décimas de milisegundo por fotograma. Cambiar esta opción obliga a volver a procesar todos los fotogramas de fondo: en un tema pesado la pantalla se quedará congelada unos segundos.',
    '      сейчас программа занимает {:.0f} МБ': '      ahora mismo el programa ocupa {:.0f} MB',
    'Экран выключен': 'La pantalla está apagada',
    'Включите вывод на главной — здесь будет видно, сколько кадров получается на самом деле.': 'Activa la salida desde el inicio — aquí se verá cuántos fotogramas se consiguen en realidad.',
    'Задано {:g}, выходит {:.1f} кадр/с': 'Ajustado a {:g}, dando {:.1f} fps',
    'Только запустились, счёт ещё набирается.': 'Recién empezado, el conteo aún se está acumulando.',
    'Успевает.': 'Va a tiempo.',
    'Не успевает: {:.0f} %. Упирается либо в отрисовку — тогда помогут меньше сглаживание и меньше живых слоёв, — либо в канал до экрана: тогда снижайте качество JPEG, кадр станет легче.': 'No llega a tiempo: {:.0f} %. El cuello de botella está o en el dibujado — entonces ayuda bajar el suavizado y usar menos capas activas —, o en el canal hacia la pantalla: entonces baja la calidad JPEG para aligerar el fotograma.',
    'версия {} · автор {}': 'versión {} · por {}',
    'Открытая замена штатной программе для экрана водянки: контроллер TXW818, панель ST7701S, 960x480 по COM-порту.': 'Una alternativa abierta al programa original de la pantalla del refrigerador líquido: controlador TXW818, panel ST7701S, 960x480 por puerto COM.',
    'Лицензия': 'Licencia',
    'Пользоваться, копировать и переделывать — можно.': 'Usarlo, copiarlo y modificarlo está permitido.',
    'Зарабатывать на этом — нельзя.': 'Ganar dinero con ello, no.',
    'Переделанное раздавать на тех же условиях и с указанием автора.': 'Lo que modifiques se comparte bajo las mismas condiciones y citando al autor.',
    'Условия распространяются и на программу, и на темы, которые с ней идут. Про коммерческое использование договариваются с автором письменно.': 'Las condiciones cubren tanto el programa como los temas que vienen con él. El uso comercial se acuerda con el autor por escrito.',
    'Открыть файл лицензии': 'Abrir el archivo de licencia',
    'Полный текст в сети': 'Texto completo en internet',
    'Файла LICENSE нет рядом с программой.': 'No hay ningún archivo LICENSE junto al programa.',
    '      Наш файл — пересказ для человека. Юридическую силу имеет полный текст на сайте Creative Commons.': '      Nuestro archivo lo cuenta en palabras sencillas. El texto legalmente válido es el completo, en el sitio de Creative Commons.',
    'Чужое': 'Ajeno',
    'Температуры читает LibreHardwareMonitor — четыре файла .dll рядом с программой. Библиотека принадлежит своим авторам и идёт по своей лицензии, MPL 2.0.': 'Las temperaturas las lee LibreHardwareMonitor — cuatro archivos .dll junto al programa. La biblioteca pertenece a sus propios autores y tiene su propia licencia, MPL 2.0.',
    'Не удалось открыть файл: {}': 'No se pudo abrir el archivo: {}',
    'Загрузка процессора, %': 'Carga de CPU, %',
    'Температура процессора': 'Temperatura de la CPU',
    'Частота процессора, ГГц': 'Frecuencia de la CPU, GHz',
    'Потребление процессора, Вт': 'Consumo de la CPU, W',
    'Обороты вентилятора ЦП': 'Velocidad del ventilador de la CPU',
    'Загрузка видеокарты, %': 'Carga de la GPU, %',
    'Температура видеокарты': 'Temperatura de la GPU',
    'Потребление видеокарты, Вт': 'Consumo de la GPU, W',
    'Загрузка видеопамяти, %': 'Carga de la memoria de vídeo, %',
    'Занято видеопамяти, ГБ': 'Memoria de vídeo usada, GB',
    'Частота видеокарты, МГц': 'Frecuencia de la GPU, MHz',
    'Вентилятор видеокарты, %': 'Ventilador de la GPU, %',
    'Загрузка ОЗУ, %': 'Carga de la RAM, %',
    'Занято ОЗУ, ГБ': 'RAM usada, GB',
    'Свободно ОЗУ, ГБ': 'RAM libre, GB',
    'Загрузка диска, %': 'Carga del disco, %',
    'Свободно на диске, ГБ': 'Espacio libre en disco, GB',
    'Приём из сети, МБ/с': 'Recepción de red, MB/s',
    'Отдача в сеть, МБ/с': 'Envío de red, MB/s',
    'Температура платы': 'Temperatura de la placa base',
    'Погода: температура': 'Clima: temperatura',
    'Погода: ощущается как': 'Clima: sensación térmica',
    'Погода: влажность, %': 'Clima: humedad, %',
    'Погода: ветер, км/ч': 'Clima: viento, km/h',
    '— свой текст —': '— tu propio texto —',
    'Загрузка процессора  23%': 'Carga de CPU  23%',
    'Температура процессора  67 °C': 'Temperatura de la CPU  67 °C',
    'Частота процессора  4.85 ГГц': 'Frecuencia de la CPU  4.85 GHz',
    'Потребление процессора  142 Вт': 'Consumo de la CPU  142 W',
    'Загрузка видеокарты  41%': 'Carga de la GPU  41%',
    'Температура видеокарты  51 °C': 'Temperatura de la GPU  51 °C',
    'Потребление видеокарты  186 Вт': 'Consumo de la GPU  186 W',
    'Видеопамять  9.9 ГБ': 'Memoria de vídeo  9.9 GB',
    'Видеопамять  9.9 / 16 ГБ': 'Memoria de vídeo  9.9 / 16 GB',
    'Загрузка ОЗУ  28%': 'Carga de RAM  28%',
    'ОЗУ  17.0 / 64 ГБ': 'RAM  17.0 / 64 GB',
    'Свободно на диске  231 ГБ': 'Espacio libre en disco  231 GB',
    'Приём из сети  11.4 МБ/с': 'Recepción de red  11.4 MB/s',
    'Отдача в сеть  2.3 МБ/с': 'Envío de red  2.3 MB/s',
    'Время работы  5ч 49м': 'Tiempo activo  5h 49m',
    'Часы  как выбрано в настройках': 'Reloj  como se eligió en los ajustes',
    'Часы с секундами  как выбрано в настройках': 'Reloj con segundos  como se eligió en los ajustes',
    'Дата  как выбрано в настройках': 'Fecha  como se eligió en los ajustes',
    'Дата коротко  как выбрано в настройках': 'Fecha corta  como se eligió en los ajustes',
    'Погода: температура со знаком настройки  12 °C': 'Clima: temperatura con la escala elegida  12 °C',
    'Часы  14:30': 'Reloj  14:30',
    'Часы с секундами  14:30:45': 'Reloj con segundos  14:30:45',
    'Часы 12-часовые  02:30 PM': 'Reloj de 12 horas  02:30 PM',
    'Часы 12-часовые с секундами  02:30:45 PM': 'Reloj de 12 horas con segundos  02:30:45 PM',
    'Дата  03.08.2026': 'Fecha  03.08.2026',
    'Дата  03.08.26': 'Fecha  03.08.26',
    'Дата  2026-08-03': 'Fecha  2026-08-03',
    'Дата  03 August': 'Fecha  03 August',
    'День недели  Monday': 'Día de la semana  Monday',
    'Погода кратко  Дождь': 'Clima breve  Lluvia',
    'Погода подробно  Небольшой дождь': 'Clima detallado  Lluvia débil',
    'Погода и температура  Дождь  12 °C': 'Clima y temperatura  Lluvia  12 °C',
    'Погода подробно и температура': 'Clima detallado y temperatura',
    'Погода: только температура  12 °C': 'Clima: solo temperatura  12 °C',
    'Погода: ощущается как  10 °C': 'Clima: sensación térmica  10 °C',
    'Погода: минимум и максимум  8…15 °C': 'Clima: mínima y máxima  8…15 °C',
    'Погода: ветер  4 км/ч': 'Clima: viento  4 km/h',
    'Погода: влажность  78 %': 'Clima: humedad  78 %',
    'Погода: город и температура': 'Clima: ciudad y temperatura',
    'Погода: всё вместе': 'Clima: todo junto',
    'по центру': 'centro',
    'слева, по середине': 'izquierda, medio',
    'справа, по середине': 'derecha, medio',
    'слева сверху': 'arriba izquierda',
    'по центру сверху': 'arriba centro',
    'справа сверху': 'arriba derecha',
    'слева снизу': 'abajo izquierda',
    'по центру снизу': 'abajo centro',
    'справа снизу': 'abajo derecha',
    'слева направо': 'de izquierda a derecha',
    'справа налево': 'de derecha a izquierda',
    'снизу вверх': 'de abajo arriba',
    'сверху вниз': 'de arriba abajo',
    'сверху': 'arriba',
    'снизу': 'abajo',
    'слева': 'izquierda',
    'справа': 'derecha',
    'заполнить с обрезкой': 'rellenar y recortar',
    'вписать целиком': 'ajustar completo',
    'растянуть': 'estirar',
    'как есть': 'tal cual',
    'нет': 'ninguno',
    'по диагонали': 'en diagonal',
    'текст': 'texto',
    'прямоугольник': 'rectángulo',
    'квадрат': 'cuadrado',
    'овал': 'óvalo',
    'круг': 'círculo',
    'линия': 'línea',
    'стрелка': 'flecha',
    'звезда': 'estrella',
    'полоса': 'barra',
    'кольцо': 'anillo',
    'картинка': 'imagen',
    'туда-обратно': 'ida y vuelta',
    'по кругу': 'en bucle',
    'затухание': 'desvanecimiento',
    'движение': 'movimiento',
    'поворот': 'giro',
    'цвет': 'color',
    'размер': 'tamaño',
    'Arial обычный': 'Arial normal',
    'Arial жирный': 'Arial negrita',
    'Segoe UI обычный': 'Segoe UI normal',
    'Segoe UI жирный': 'Segoe UI negrita',
    'Consolas обычный': 'Consolas normal',
    'Consolas жирный': 'Consolas negrita',
    'Tahoma обычный': 'Tahoma normal',
    'Tahoma жирный': 'Tahoma negrita',
    'Verdana обычный': 'Verdana normal',
    'Verdana жирный': 'Verdana negrita',
    'Calibri обычный': 'Calibri normal',
    'Calibri жирный': 'Calibri negrita',
    'Искать по названию, типу и тексту слоя. Рядом — показывать все слои, только видимые ночью или только днём.': 'Buscar por el nombre, el tipo y el texto de la capa. Al lado: mostrar todas las capas, solo las visibles de noche o solo las visibles de día.',
    'Подпись для себя, в списке слева. На картинку не влияет.': 'Un nombre para ti, que aparece en la lista de la izquierda. No afecta a la imagen.',
    'Отступ слева, в точках. Начало координат — левый верхний угол.': 'Distancia desde la izquierda, en puntos. El origen de coordenadas es la esquina superior izquierda.',
    'Отступ сверху, в точках.': 'Distancia desde arriba, en puntos.',
    'Куда линия приходит по горизонтали.': 'Dónde termina la línea en horizontal.',
    'Куда линия приходит по вертикали.': 'Dónde termina la línea en vertical.',
    'Наклон слоя в градусах, по часовой стрелке.': 'Inclinación de la capa en grados, en sentido horario.',
    'Растянуть слой вширь. 1 — как есть, 2 — вдвое шире.': 'Estirar la capa a lo ancho. 1 — tal cual, 2 — el doble de ancho.',
    'Растянуть слой ввысь. 1 — как есть, 0.5 — вдвое ниже.': 'Estirar la capa a lo alto. 1 — tal cual, 0.5 — la mitad de alto.',
    'Насколько слой прозрачен: 0 — не видно совсем, 1 — плотно.': 'Cuánto se transparenta la capa: 0 — invisible del todo, 1 — sólido.',
    'Что написать. В фигурных скобках подставляются показания: {cpu_load:.0f}% даст «37%».': 'Qué escribir. Entre llaves van las lecturas: {cpu_load:.0f}% da «37%».',
    'Готовые надписи: часы, дата, погода, загрузка. Выбери — и текст подставится сам.': 'Textos ya preparados: reloj, fecha, clima, carga. Elige uno y el texto se rellena solo.',
    'Файл шрифта. Любой из системы или положенный рядом с темой.': 'Un archivo de fuente. Cualquiera del sistema, o uno puesto junto al tema.',
    'Высота букв в точках.': 'Altura de las letras en puntos.',
    'Влезть в ширину': 'Ajustar al ancho',
    'Влезть в столько точек по ширине. Длинная надпись сама уменьшится, короткая останется как есть. 0 — не ужимать, тогда длинное уедет за край.': 'Ajustar a este ancho en puntos. Un texto largo se reducirá solo, uno corto se queda tal cual. 0 — no reducir, y el texto largo se saldrá del borde.',
    'Цвет букв.': 'Color de las letras.',
    'За какую точку слой держится координатами. По центру — удобно для цифр, что меняют длину.': 'A qué punto de la capa se agarran las coordenadas. El centro es cómodo para números que cambian de longitud.',
    'Цвет обводки. Помогает читать надпись поверх пёстрой картинки.': 'Color del contorno. Ayuda a leer el texto sobre una imagen recargada.',
    'Толщина обводки букв в точках.': 'Grosor del contorno de las letras en puntos.',
    'Ширина слоя в точках.': 'Ancho de la capa en puntos.',
    'Высота слоя в точках.': 'Alto de la capa en puntos.',
    'Скругление углов. 0 — прямые углы.': 'Redondeo de las esquinas. 0 — esquinas rectas.',
    'Основной цвет заливки.': 'Color principal de relleno.',
    'Второй цвет: заливка станет переходом от первого ко второму.': 'Un segundo color: el relleno se convierte en un degradado del primero al segundo.',
    'В какую сторону идёт переход между двумя цветами.': 'En qué dirección va el degradado entre los dos colores.',
    'Толщина линии или окантовки в точках.': 'Grosor de la línea o del borde en puntos.',
    'Откуда берётся число: загрузка, температура, погода.': 'De dónde viene el número: carga, temperatura, clima.',
    'Какому значению соответствует пустая полоса или дуга.': 'El valor con el que la barra o el arco están vacíos.',
    'Какому значению соответствует полная полоса или дуга.': 'El valor con el que la barra o el arco están llenos.',
    'В какую сторону растёт заполнение.': 'En qué dirección crece el relleno.',
    'Цвет незаполненной части. Можно не задавать.': 'Color de la parte vacía. Puede dejarse sin definir.',
    'Радиус в точках. Координаты — это центр, а не угол.': 'Radio en puntos. Las coordenadas son el centro, no una esquina.',
    'Радиус впадин между лучами звезды.': 'Radio de las hendiduras entre las puntas de la estrella.',
    'Сколько лучей у звезды.': 'Cuántas puntas tiene la estrella.',
    'Повернуть звезду на столько градусов.': 'Girar la estrella estos grados.',
    'Толщина дуги в точках.': 'Grosor del arco en puntos.',
    'С какой стороны у кольца вырез.': 'Por qué lado tiene el corte el anillo.',
    'Ширина выреза в градусах. 60 — небольшой, 180 — половина круга.': 'Ancho del corte en grados. 60 es pequeño, 180 es medio círculo.',
    'Заполнять дугу с другого конца, навстречу обычному.': 'Rellenar el arco desde el otro extremo, en sentido contrario al habitual.',
    'Скруглить концы — дуга или линия смотрится мягче.': 'Redondear los extremos — el arco o la línea se ven más suaves.',
    'Размер наконечника стрелки в точках.': 'Tamaño de la punta de la flecha en puntos.',
    'Файл картинки или папка с кадрами. Папка листается как ролик.': 'Un archivo de imagen o una carpeta de fotogramas. Una carpeta se reproduce como un clip.',
    'Что делать, если картинка не совпала с отведённым местом.': 'Qué hacer cuando la imagen no encaja en el espacio asignado.',
    'Своя частота листания кадров. Ставь ту, с которой резал ролик, иначе он поедет быстрее или медленнее задуманного.': 'Su propia velocidad de fotogramas. Pon la misma con la que se cortó el clip, o irá más rápido o más lento de lo previsto.',
    'Включи, если PNG выгружены из DaVinci: там цвет уже умножен на прозрачность, и без этого по мягкому краю пойдёт тёмная каёмка.': 'Actívalo si los PNG vienen exportados de DaVinci: allí el color ya está multiplicado por la transparencia, y sin esto aparece un borde oscuro en los bordes suaves.',
    'Поднять непрозрачность, если объект вырезался полупрозрачным и выглядит блёклым. 1 — не трогать, 1.5 — заметно плотнее.': 'Sube la opacidad si el objeto se recortó semitransparente y se ve apagado. 1 — sin cambios, 1.5 — notablemente más denso.',
    'Поворот, °': 'Giro, °',
    'Шире': 'Más ancho',
    'Выше': 'Más alto',
    'Прозрачность': 'Transparencia',
    'Второй цвет': 'Segundo color',
    'Переход цвета': 'Degradado de color',
    'Готовая надпись': 'Texto ya preparado',
    'Текст': 'Texto',
    'Шрифт': 'Fuente',
    'Размер': 'Tamaño',
    'Цвет': 'Color',
    'Держится за': 'Anclaje',
    'Обводка': 'Contorno',
    'Толщина обводки': 'Grosor del contorno',
    'Ширина': 'Ancho',
    'Высота': 'Alto',
    'Скругление': 'Redondeo',
    'Заливка': 'Relleno',
    'Окантовка': 'Borde',
    'Толщина': 'Grosor',
    'Наконечник': 'Punta de flecha',
    'Мягкие концы': 'Extremos suaves',
    'X конца': 'X final',
    'Y конца': 'Y final',
    'Радиус': 'Radio',
    'Радиус впадин': 'Radio de hendiduras',
    'Лучей': 'Puntas',
    'Наклон, °': 'Inclinación, °',
    'Показание': 'Lectura',
    'Пусто при': 'Vacío en',
    'Полно при': 'Lleno en',
    'Направление': 'Dirección',
    'Цвет заполнения': 'Color de relleno',
    'Цвет пустоты': 'Color de vacío',
    'Толщина дуги': 'Grosor del arco',
    'Вырез': 'Corte',
    'Вырез, °': 'Corte, °',
    'Наоборот': 'Al revés',
    'Картинка': 'Imagen',
    'Как вписать': 'Cómo ajustar',
    'PNG из DaVinci': 'PNG de DaVinci',
    'Плотнее': 'Más denso',
    'Что показывает': 'Qué muestra',
    'Где и какого размера': 'Dónde y de qué tamaño',
    'Как выглядит': 'Cómo se ve',
    'Прочее': 'Otros',
    'новый текст': 'texto nuevo',
    'новый прямоугольник': 'rectángulo nuevo',
    'новый квадрат': 'cuadrado nuevo',
    'новый овал': 'óvalo nuevo',
    'новый круг': 'círculo nuevo',
    'новая линия': 'línea nueva',
    'новая стрелка': 'flecha nueva',
    'новая звезда': 'estrella nueva',
    'новая полоса': 'barra nueva',
    'новое кольцо': 'anillo nuevo',
    'новая картинка': 'imagen nueva',
    'слой': 'capa',
    'блок': 'bloque',
    ' копия': ' copia',
    '←  К темам': '←  A los temas',
    'Сохранить как…': 'Guardar como…',
    'Вернуть с диска': 'Recargar desde el disco',
    'Открыть тему…': 'Abrir un tema…',
    'Описание темы…': 'Detalles del tema…',
    '●  Магнит': '●  Imán',
    '○  Магнит': '○  Imán',
    '●  Сетка {}': '●  Cuadrícula {}',
    '○  Сетка': '○  Cuadrícula',
    'Выровнять:': 'Alinear:',
    'К левому краю экрана': 'Al borde izquierdo de la pantalla',
    'По центру экрана вбок': 'Al centro de la pantalla, horizontal',
    'К правому краю экрана': 'Al borde derecho de la pantalla',
    'К верхнему краю экрана': 'Al borde superior de la pantalla',
    'По центру экрана вниз': 'Al centro de la pantalla, vertical',
    'К нижнему краю экрана': 'Al borde inferior de la pantalla',
    'Размер:': 'Tamaño:',
    'Уменьшить выбранные слои на десятую часть': 'Reducir las capas elegidas una décima parte',
    'Увеличить выбранные слои на десятую часть': 'Aumentar las capas elegidas una décima parte',
    '. Работает и на нескольких сразу: выдели их в списке с Ctrl или Shift.': '. Funciona también con varias a la vez: selecciónalas en la lista con Ctrl o Shift.',
    'Показать на экране': 'Mostrar en la pantalla',
    'Остановить показ': 'Dejar de mostrar',
    'Слои · нижние перекрываются верхними': 'Capas · las de abajo quedan tapadas por las de arriba',
    'все': 'todas',
    'день': 'día',
    'Скрыть': 'Ocultar',
    'Копия': 'Copia',
    'Удалить': 'Eliminar',
    'Добавить:': 'Añadir:',
    'Режим правки:': 'Modo de edición:',
    'Ночной вид': 'Vista nocturna',
    'Переход': 'Transición',
    'Дневной вид': 'Vista diurna',
    'Прокрутка перехода:': 'Recorrer la transición:',
    'Двигается только выбранный слой. Стрелки — на пиксель, Shift+стрелки — на десять.\nМагнит притягивает к краям и центрам соседей; Alt при перетаскивании временно его отключает.\nНесколько слоёв разом: Ctrl+щелчок или Shift+щелчок в списке.\nCtrl+Z отменить · Ctrl+Y вернуть · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S сохранить · Delete удалить': 'Solo se mueve la capa elegida. Las flechas la mueven un píxel, Shift+flechas diez.\nEl imán atrae a los bordes y centros de las capas vecinas; Alt mientras arrastras lo desactiva por un momento.\nVarias capas a la vez: Ctrl+clic o Shift+clic en la lista.\nCtrl+Z deshacer · Ctrl+Y rehacer · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S guardar · Delete eliminar',
    'Тип блока': 'Tipo de bloque',
    'Экран': 'Pantalla',
    'Фон под всеми блоками:': 'Fondo bajo todos los bloques:',
    'Убрать дневной': 'Quitar diurno',
    'нет дневного — фон ночной круглые сутки': 'sin diurno — el fondo nocturno se queda todo el día',
    'Сжимать кадры фона': 'Comprimir los fotogramas de fondo',
    'памяти вчетверо меньше, картинка та же': 'cuatro veces menos memoria, la misma imagen',
    'кадры фона будут сжаты — готовлю заново': 'los fotogramas de fondo se comprimirán — preparándolos de nuevo',
    'кадры фона будут распакованы — готовлю заново': 'los fotogramas de fondo se descomprimirán — preparándolos de nuevo',
    'Здесь настраивается только движение.\nЧто именно меняется — задаётся\nв ночном и дневном видах.': 'Aquí solo se configura el movimiento.\nQué es lo que cambia se define\nen las vistas de noche y de día.',
    'Правки уходят в дневной вид': 'Los cambios van a la vista diurna',
    'Сбросить': 'Restablecer',
    'Переход к дневному виду': 'Transición a la vista diurna',
    'настроен': 'configurado',
    'не настроен': 'sin configurar',
    'Что меняется:': 'Qué cambia:',
    'Отрезок перехода, %': 'Tramo de la transición, %',
    'Начало': 'Inicio',
    'Середина': 'Medio',
    'Окончание': 'Fin',
    'Повтор по времени': 'Repetir con el tiempo',
    'Период, секунд': 'Período, segundos',
    'Как повторять': 'Cómo repetir',
    'Показать в момент': 'Mostrar en el momento',
    'сброс': 'restablecer',
    'Реакция на датчик': 'Reacción a una lectura',
    'Датчик': 'Lectura',
    'Начинает меняться при': 'Empieza a cambiar en',
    'Полностью при': 'Al máximo en',
    'Показать при значении': 'Mostrar en el valor',
    'отменять нечего': 'nada que deshacer',
    'отменено': 'deshecho',
    'возвращать нечего': 'nada que rehacer',
    'возвращено': 'rehecho',
    'слой скопирован': 'capa copiada',
    'слой вырезан': 'capa cortada',
    'в буфере нет слоя': 'no hay ninguna capa en el portapapeles',
    'слой вставлен': 'capa pegada',
    'магнит включён': 'imán activado',
    'магнит выключен': 'imán desactivado',
    'сетка выключена': 'cuadrícula desactivada',
    'сетка по {} точек': 'cuadrícula cada {} puntos',
    'размер {:+.0f} % у {} слоёв': 'tamaño {:+.0f} % en {} capas',
    'показано {} из {}': 'mostrando {} de {}',
    'X {}  Y {}   (без магнита)': 'X {}  Y {}   (sin imán)',
    'X {}  Y {}{}': 'X {}  Y {}{}',
    '   ({} слоёв)': '   ({} capas)',
    'шрифт скопирован в папку fonts': 'la fuente se copió a la carpeta fonts',
    'не смог скопировать: {}': 'no se pudo copiar: {}',
    'переименовано, папка тоже': 'renombrado, la carpeta también',
    'папку переименовать не вышло: {}': 'no se pudo renombrar la carpeta: {}',
    'описание изменено, не забудь сохранить': 'la descripción cambió, no olvides guardar',
    'дневной вид блока сброшен': 'la vista diurna del bloque se restableció',
    'ошибка: {}': 'error: {}',
    'сохранено': 'guardado',
    'открыто: ': 'abierto: ',
    'экран не найден': 'no se encontró la pantalla',
    'показ прерван: {}': 'la muestra se detuvo: {}',
    '{} · редактор · {} — {}': '{} · editor · {} — {}',
    'Удалить слой «{}»?': '¿Eliminar la capa «{}»?',
    'Удалить выбранные слои ({} шт.)?': '¿Eliminar las capas elegidas ({} en total)?',
    'Выбери файл шрифта': 'Elige un archivo de fuente',
    'Шрифты': 'Fuentes',
    'Папка с кадрами (Отмена - выбрать файл)': 'Carpeta de fotogramas (Cancelar para elegir un archivo)',
    'Открыть': 'Abrir',
    'Вернуть': 'Recargar',
    'Папка с темой (Отмена — выбрать файл)': 'Carpeta del tema (Cancelar para elegir un archivo)',
    'В папке нет файлов описания темы (.json).\n\nФайл темы должен лежать рядом с папками кадров.': 'No hay archivos de descripción del tema (.json) en la carpeta.\n\nEl archivo del tema debe estar junto a las carpetas de fotogramas.',
    'Какой файл темы открыть': 'Qué archivo de tema abrir',
    'Файл темы': 'Archivo del tema',
    'Описание панели': 'Archivo del panel',
    'Не удалось прочитать файл:\n{}': 'No se pudo leer el archivo:\n{}',
    'Это не похоже на тему: нет раздела layers.': 'Esto no parece un tema: no tiene la sección layers.',
    'Тема ссылается на то, чего нет рядом с её файлом:\n\n  ': 'El tema hace referencia a cosas que no están junto a su archivo:\n\n  ',
    '\n\nПеренеси эти папки в {}': '\n\nMueve estas carpetas a {}',
    'Не найден файл описания: {}': 'No se encontró el archivo de descripción: {}',
    'осмотр машины': 'revisión del equipo',
    '[д/н] ': '[s/n] ',
    'прервано': 'interrumpido',
    'язык уже выбран': 'el idioma ya está elegido',
    'язык Windows подсказывал другой: {}': 'el idioma de Windows sugería otro: {}',
    'язык выбран по языку Windows': 'el idioma se tomó de Windows',
    'поменять можно в Настройках -> Оформление программы': 'se puede cambiar en Ajustes -> Aspecto del programa',
    'Библиотеки': 'Bibliotecas',
    'сборка кадров и всё рисование': 'montaje de fotogramas y todo el dibujado',
    'загрузка процессора, память, диски, сеть': 'carga del procesador, memoria, discos, red',
    'разговор с экраном по COM-порту': 'comunicación con la pantalla por puerto COM',
    'само окно программы': 'la propia ventana del programa',
    'температура процессора, видеокарты AMD и Intel': 'temperatura del procesador, tarjetas gráficas AMD e Intel',
    'переходы цвета и мягкие края': 'degradados de color y bordes suaves',
    'значок рядом с часами': 'el icono junto al reloj',
    'переустанови Python, отметив «tcl/tk and IDLE»': 'reinstala Python marcando «tcl/tk and IDLE»',
    'Поставить всё разом:': 'Instalar todo de una vez:',
    'Без обязательных библиотек осматривать дальше нечего.': 'Sin las bibliotecas obligatorias no hay nada más que revisar.',
    'Права': 'Permisos',
    'права администратора есть': 'hay permisos de administrador',
    'прав администратора нет': 'no hay permisos de administrador',
    'без них температуры процессора не будет вовсе': 'sin ellos no habrá temperatura del procesador en absoluto',
    'запусти start.bat, а программу - через app.bat': 'ejecuta start.bat, y el programa en sí a través de app.bat',
    'Библиотека датчиков': 'La biblioteca de sensores',
    'нет рядом с программой': 'no está junto al programa',
    'возьми из архива LibreHardwareMonitor и положи сюда': 'tómala del archivo de LibreHardwareMonitor y ponla aquí',
    'все четыре файла на месте': 'los cuatro archivos están en su sitio',
    'снял пометку «из интернета»': 'se quitó la marca «de internet»',
    'помечен как скачанный из интернета': 'marcado como descargado de internet',
    'Свойства файла -> галочка «Разблокировать»': 'Propiedades del archivo -> la casilla «Desbloquear»',
    'пометки «из интернета» ни на одном нет': 'ninguno tiene la marca «de internet»',
    'Железо': 'El equipo',
    'процессор': 'procesador',
    'видеокарта': 'tarjeta gráfica',
    'название выяснить не удалось': 'no se pudo averiguar el nombre',
    'ядер {}, потоков {}': '{} núcleos, {} hilos',
    'оперативной памяти {:.0f} ГБ': '{:.0f} GB de memoria',
    'системный диск {}': 'disco del sistema {}',
    'опрашиваю железо, это занимает несколько секунд…': 'consultando el hardware, esto tarda unos segundos…',
    'загрузка процессора': 'carga del procesador',
    'температура процессора': 'temperatura del procesador',
    'частота процессора': 'frecuencia del procesador',
    'загрузка памяти': 'carga de la memoria',
    'загрузка диска': 'carga del disco',
    'приём из сети': 'recepción de red',
    'загрузка видеокарты': 'carga de la tarjeta gráfica',
    'температура видеокарты': 'temperatura de la tarjeta gráfica',
    'занято видеопамяти': 'memoria de vídeo usada',
    'потребление видеокарты': 'consumo de la tarjeta gráfica',
    'не читается': 'no se puede leer',
    'температура читается': 'la temperatura se puede leer',
    'выбран датчик: ': 'sensor elegido: ',
    'источник открылся, но отдаёт нули': 'la fuente se abrió, pero da ceros',
    'библиотека отдаёт нули по всем ядрам: нет прав администратора': 'la biblioteca da ceros en todos los núcleos: no hay permisos de administrador',
    'так бывает без прав администратора: запусти start.bat': 'eso pasa sin permisos de administrador: ejecuta start.bat',
    'источник не найден': 'no se encontró ninguna fuente',
    'запусти программу через app.bat': 'inicia el programa a través de app.bat',
    'нужны права администратора и четыре .dll рядом': 'hacen falta permisos de administrador y los cuatro archivos .dll cerca',
    'видеокарта читается': 'la tarjeta gráfica se puede leer',
    'нет источника показаний': 'no hay ninguna fuente de lecturas',
    'положи System.Numerics.Vectors.dll рядом с программой': 'pon System.Numerics.Vectors.dll junto al programa',
    'нужен для видеокарт не Nvidia — на месте': 'hace falta para tarjetas que no son Nvidia — está en su sitio',
    'нужен, чтобы читать видеокарту не Nvidia': 'hace falta para leer una tarjeta gráfica que no sea Nvidia',
    'особых прав не нужно': 'no hacen falta permisos especiales',
    'температуры читает ядро, оно их и так отдаёт': 'las temperaturas las lee el núcleo, y las da de todos modos',
    'температуры читает ядро, библиотека датчиков не нужна': 'las temperaturas las lee el núcleo, no hace falta biblioteca de sensores',
    'ядро Linux': 'el núcleo de Linux',
    'ядро Linux (drm)': 'el núcleo de Linux (drm)',
    'ядро не отдаёт температур: нет /sys/class/hwmon': 'el núcleo no da temperaturas: no existe /sys/class/hwmon',
    'ядро не отдаёт показаний видеокарты: нет /sys/class/drm': 'el núcleo no da lecturas de la tarjeta gráfica: no existe /sys/class/drm',
    'ядро не выложило /sys/class/hwmon: посмотри, загружен ли модуль датчиков процессора': 'el núcleo no expuso /sys/class/hwmon: revisa si está cargado el módulo de sensores del procesador',
    'для Nvidia нужен nvidia-smi, для AMD - драйвер amdgpu в /sys/class/drm': 'para Nvidia hace falta nvidia-smi, para AMD el controlador amdgpu en /sys/class/drm',
    'библиотеке не хватает файла System.Numerics.Vectors.dll — без него показаний видеокарты не будет. Возьми его из архива LibreHardwareMonitor': 'a la biblioteca le falta el archivo System.Numerics.Vectors.dll — sin él no habrá lecturas de la tarjeta gráfica. Tómalo del archivo de LibreHardwareMonitor',
    'для Nvidia хватит драйвера, для AMD и Intel нужна библиотека датчиков и права': 'para Nvidia basta con el controlador; AMD e Intel necesitan la biblioteca de sensores y los permisos',
    'psutil (процессор, память, диски, сеть): ': 'psutil (procesador, memoria, discos, red): ',
    'есть': 'presente',
    'НЕ УСТАНОВЛЕН': 'NO INSTALADO',
    'процессор: ': 'procesador: ',
    'видеокарта: ': 'tarjeta gráfica: ',
    'показания видеокарты: ': 'lecturas de la tarjeta gráfica: ',
    'показания видеокарты: НЕТ — ': 'lecturas de la tarjeta gráfica: NINGUNA — ',
    'показания видеокарты: НЕТ — нет ни nvidia-smi, ни LibreHardwareMonitorLib.dll': 'lecturas de la tarjeta gráfica: NINGUNA — no está ni nvidia-smi ni LibreHardwareMonitorLib.dll',
    'температура процессора: читается ({})': 'temperatura del procesador: se puede leer ({})',
    'библиотека напрямую': 'la biblioteca directamente',
    'через WMI': 'mediante WMI',
    'способ не указан': 'no se indica el método',
    ', вспомогательных сборок: {}': ', ensamblados auxiliares: {}',
    '  выбран датчик: ': '  sensor elegido: ',
    '  все найденные датчики процессора:': '  todos los sensores del procesador encontrados:',
    'температура процессора: НЕТ — ': 'temperatura del procesador: NINGUNA — ',
    '  ВНИМАНИЕ: программа запущена без прав администратора.': '  ATENCIÓN: el programa se está ejecutando sin permisos de administrador.',
    '  Температуру процессора без них прочитать невозможно в принципе:': '  Sin ellos, la temperatura del procesador no se puede leer de ninguna manera:',
    '  Windows не даёт доступ к регистрам процессора обычным программам.': '  Windows no deja que los programas normales accedan a los registros del procesador.',
    '  Права администратора есть. Положи рядом LibreHardwareMonitorLib.dll': '  Los permisos de administrador están. Pon LibreHardwareMonitorLib.dll junto al programa',
    '  и HidSharp.dll, либо запусти саму LibreHardwareMonitor в фоне.': '  y HidSharp.dll, o ejecuta la propia LibreHardwareMonitor en segundo plano.',
    'рядом нет LibreHardwareMonitorLib.dll (положи её в папку с программой)': 'no está LibreHardwareMonitorLib.dll junto al programa (ponla en la carpeta del programa)',
    'библиотека есть, но нет pythonnet. Выполни: pip install pythonnet': 'la biblioteca está, pero falta pythonnet. Ejecuta: pip install pythonnet',
    'библиотека заблокирована Windows как скачанная из интернета. Свойства файла -> галочка «Разблокировать»': 'Windows bloqueó la biblioteca por estar descargada de internet. Propiedades del archivo -> la casilla «Desbloquear»',
    'погода: получена{}{}': 'clima: recibido{}{}',
    ' от ': ' de ',
    ' для ': ' para ',
    '  восход и закат: ': '  amanecer y atardecer: ',
    'погода: НЕТ — ': 'clima: NINGUNO — ',
    'ещё не загружена': 'todavía no se ha cargado',
    'не выбрано место — укажи город в настройках, раздел «Погода»': 'no se ha elegido ubicación — indica la ciudad en los ajustes, en la sección «Clima»',
    'не смог заглянуть в порты': 'no se pudo mirar en los puertos',
    'экран найден': 'se encontró la pantalla',
    'ни на одном COM-порту': 'en ningún puerto COM',
    'проверь кабель от помпы к разъёму USB на плате': 'revisa el cable de la bomba al conector USB de la placa',
    'а вот что на портах есть:': 'esto es lo que sí hay en los puertos:',
    'COM-портов не найдено вообще': 'no se encontró ningún puerto COM',
    'погода выключена в настройках': 'el clima está desactivado en los ajustes',
    'прогноз получен': 'el pronóstico ha llegado',
    'восход {}   закат {}   ({})': 'amanecer {}   atardecer {}   ({})',
    'свой расчёт': 'calculado por nosotros',
    'прогноза нет': 'no hay pronóstico',
    'источник не ответил': 'la fuente no respondió',
    'проверь интернет и место в Настройках -> Погода и адрес': 'revisa internet y la ubicación en Ajustes -> Clima y dirección',
    'не смог просмотреть темы': 'no se pudieron revisar los temas',
    'названия железа нигде не вписаны руками': 'no hay nombres de hardware escritos a mano en ningún sitio',
    '«{}»: {} слоёв с вписанным названием': '«{}»: {} capas con un nombre escrito',
    'Заменить, чтобы тема сама называла ваше железо?': '¿Reemplazarlos para que el tema nombre tu propio hardware?',
    'оставил как было': 'se dejó como estaba',
    'тема поправлена': 'el tema se corrigió',
    'не смог записать тему': 'no se pudo guardar el tema',
    'Записываю в настройки': 'Guardando en los ajustes',
    'железо записано': 'el hardware quedó registrado',
    'опрос nvidia-smi': 'consulta a nvidia-smi',
    'включён': 'activado',
    'выключен, он тут не нужен': 'desactivado, aquí no hace falta',
    'Температуру прочитать нечем. Выключить её опрос?': 'No hay con qué leer la temperatura. ¿Dejar de consultarla?',
    'опрос температур выключен': 'la consulta de temperaturas está desactivada',
    'Итог': 'En resumen',
    'Всё на месте. Запускай app.bat.': 'Todo está en su sitio. Ejecuta app.bat.',
    'Без этого программа будет работать не полностью:': 'Sin esto, el programa no funcionará al completo:',
    'Мелочи, жить можно:': 'Detalles menores, se puede vivir con ellos:',
    'Когда поправишь - запусти start.bat ещё раз.': 'Cuando lo arregles, ejecuta start.bat otra vez.',
}

# Погода. Коротко - одно слово для тесных мест, полно - для строки
# на весь экран.
POGODA = {
    0: ("Despejado", "Despejado"),
    1: ("Despejado", "Mayormente despejado"),
    2: ("Nubes", "Parcialmente nublado"),
    3: ("Nublado", "Nublado"),
    45: ("Niebla", "Niebla"),
    48: ("Niebla", "Niebla helada"),
    51: ("Llovizna", "Llovizna débil"),
    53: ("Llovizna", "Llovizna"),
    55: ("Llovizna", "Llovizna intensa"),
    56: ("Hielo", "Llovizna helada"),
    57: ("Hielo", "Llovizna helada intensa"),
    61: ("Lluvia", "Lluvia débil"),
    63: ("Lluvia", "Lluvia"),
    65: ("Lluvia", "Lluvia intensa"),
    66: ("Hielo", "Lluvia helada"),
    67: ("Hielo", "Lluvia helada intensa"),
    71: ("Nieve", "Nieve débil"),
    73: ("Nieve", "Nieve"),
    75: ("Nieve", "Nieve intensa"),
    77: ("Nieve", "Granos de nieve"),
    80: ("Chubascos", "Chubascos débiles"),
    81: ("Chubascos", "Chubascos"),
    82: ("Chubascos", "Chubascos intensos"),
    85: ("Nieve", "Chubascos de nieve"),
    86: ("Nieve", "Chubascos de nieve intensos"),
    95: ("Tormenta", "Tormenta"),
    96: ("Tormenta", "Tormenta con granizo"),
    99: ("Tormenta", "Tormenta fuerte con granizo"),
}

# Сокращения - только там, где полное длиннее двадцати знаков.
SOKRASHENO = {
    57: "Llovizna helada int.",
    67: "Lluvia helada int.",
    82: "Chubascos int.",
    85: "Chubascos de nieve",
    86: "Chub. de nieve int.",
    96: "Tormenta c/ granizo",
    99: "Tormenta fuerte c/ granizo",
}
