#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  Португальский: слова программы и слова погоды.
#  Часть проекта EOne screen.
#
#  Автор: EOne
#  Лицензия: CC BY-NC-SA 4.0 — использование в коммерческих целях
#  запрещено без письменного разрешения автора. См. файл LICENSE.
#
"""yazyk_pt.py - португальский. Устройство описано в yazyk_es.py.

ПЕРЕВОД СДЕЛАН С ПОМОЩЬЮ ИИ и носителем языка не проверялся. Русский
и английский написаны автором, остальные пять - нет. Если вы говорите
на этом языке и видите ошибку или корявость, поправьте: строку можно
менять прямо здесь, а ключ трогать нельзя.

"""

SLOVAR = {
    # Готовые надписи, которые всегда по-английски:
    # они просят {weather_en}, а не {weather}.
    "Weather short  Rain": "Clima resumido, sempre em inglês  Rain",
    "Weather full  Light rain": "Clima detalhado, sempre em inglês  Light rain",
    "Weather and temperature  Rain  12 °C": "Clima e temperatura, sempre em inglês  Rain  12 °C",
    "Weather full and temperature": "Clima detalhado e temperatura, sempre em inglês",
    "Weather: feels like  10 °C": "Clima: sensação térmica, sempre em inglês  10 °C",
    "Weather: wind  4 km/h": "Clima: vento, sempre em inglês  4 km/h",
    "Weather: humidity  78 %": "Clima: umidade, sempre em inglês  78 %",
    "Weather: everything": "Clima: tudo junto, sempre em inglês",
    # Значения движка: подпись видит человек, а в тему уходит
    # русское слово - его подставляет сама программа.
    "плавно": "suave",
    "средне": "médio",
    "резко": "brusco",

    'Главная': 'Início',
    'Темы': 'Temas',
    'Настройки': 'Configurações',
    'экран водянки': 'tela da water cooler',
    'экран выключен': 'tela desligada',
    'экран: {} · {:.0f} кадр/с': 'tela: {} · {:.0f} fps',
    'переход {:.0f} с': 'transição {:.0f} s',
    'тема отправлена на экран': 'tema enviado para a tela',
    'перезапускаю экран…': 'reiniciando a tela…',
    'сбой обновления: {}': 'falha ao atualizar: {}',
    '{} — экран выключен': '{} — tela desligada',
    '{} — {} ({:.1f} кадр/с, {})': '{} — {} ({:.1f} fps, {})',
    'Включить или выключить экран': 'Ligar ou desligar a tela',
    'Показать окно': 'Mostrar a janela',
    'Выход': 'Sair',
    'Пауза': 'Pausar',
    'Продолжить': 'Continuar',
    'Перечитать тему': 'Reler o tema',
    '{} · {} — {} ({:.1f} кадр/с, тема {})': '{} · {} — {} ({:.1f} fps, tema {})',
    'по солнцу': 'pelo sol',
    'как в Windows': 'como no Windows',
    'всегда ночная': 'sempre noturna',
    'всегда дневная': 'sempre diurna',
    'запускается': 'iniciando',
    'остановлена': 'parada',
    'на паузе': 'em pausa',
    'слишком много сбоев': 'muitas falhas seguidas',
    'Сохранить правки?': 'Salvar as alterações?',
    'Несохранённые правки пропадут. Продолжить?': 'As alterações não salvas serão perdidas. Continuar?',
    'Это не похоже на тему: нет слоёв.': 'Isso não parece um tema: não há camadas.',
    'Моя тема': 'Meu tema',
    'Сейчас на экране': 'Agora na tela',
    'Что показывать': 'O que mostrar',
    'Погода на экране': 'Clima na tela',
    'Включить экран': 'Ligar a tela',
    'Выключить экран': 'Desligar a tela',
    'Перезапустить': 'Reiniciar',
    'выключен': 'desligada',
    'работает': 'funcionando',
    'работает · {:.0f} кадр/с': 'funcionando · {:.0f} fps',
    '(прогноз не пришёл)': '(a previsão não chegou)',
    'готовлю кадры фона': 'preparando os quadros de fundo',
    'тема: ': 'tema: ',
    'погода': 'clima',
    'днём': 'de dia',
    'ночью': 'à noite',
    'восход {}   закат {}   сейчас {:.0f} % дня': 'nascer do sol {}   pôr do sol {}   agora {:.0f} % do dia',
    '   (прогноз не пришёл)': '   (a previsão não chegou)',
    'отправлено кадров {}': 'quadros enviados {}',
    'сбоев {}': 'falhas {}',
    '{:g} кадр/с': '{:g} fps',
    'не удалось собрать кадр: {}': 'não foi possível montar o quadro: {}',
    'кадры фона не листаются, чтобы окно не тратило лишнего': 'os quadros de fundo não são animados aqui, para não gastar recursos à toa',
    'Начать или прекратить вывод картинки на экран водянки.': 'Iniciar ou parar o envio da imagem para a tela da water cooler.',
    'Придержать вывод, не закрывая порт. Экран замрёт на последнем кадре.': 'Pausar o envio sem fechar a porta. A tela vai congelar no último quadro.',
    'Заново открыть порт и поздороваться с экраном. Выручает, если картинка сбилась или порт подвис.': 'Reabrir a porta e reconectar com a tela. Ajuda quando a imagem trava ou a porta engasga.',
    'Яркость подсветки экрана водянки. Уходит на экран, когда отпустишь ползунок.': 'Brilho da luz de fundo da tela da water cooler. É aplicado na tela quando você solta o controle deslizante.',
    'По солнцу': 'Pelo sol',
    'Как в Windows': 'Como no Windows',
    'Ночь': 'Noite',
    'День': 'Dia',
    'Светлеет на рассвете и темнеет на закате, по времени восхода и заката в твоём городе.': 'Clareia ao amanhecer e escurece ao anoitecer, pelo horário do nascer e pôr do sol na sua cidade.',
    'Следит за оформлением Windows: светлая тема — дневной вид, тёмная — ночной.': 'Segue o tema do Windows: claro é a visão diurna, escuro é a noturna.',
    'Всегда ночной вид, независимо от времени.': 'Sempre a visão noturna, não importa a hora.',
    'Всегда дневной вид, независимо от времени.': 'Sempre a visão diurna, não importa a hora.',
    'По прогнозу': 'Pela previsão',
    'Ясно': 'Limpo',
    'Пасмурно': 'Nublado',
    'Дождь': 'Chuva',
    'Гроза': 'Trovoada',
    'Снег': 'Neve',
    'Метель': 'Nevasca',
    'Туман': 'Nevoeiro',
    'Мороз': 'Geada',
    'Жара': 'Calor',
    'Показывать настоящий прогноз.': 'Mostrar a previsão real.',
    'Показать «{}» так, будто оно за окном: {:+.0f} {}, ветер {:.0f} {}. Прогноз никуда не девается.': 'Mostrar «{}» como se fosse o tempo lá fora: {:+.0f} {}, vento {:.0f} {}. A previsão continua guardada.',
    'Показывать дождь, снег, туман и грозу на дневной теме.': 'Mostrar chuva, neve, nevoeiro e tempestade no tema diurno.',
    'То же на ночной. Звёзды и метеоры останутся в любом случае.': 'O mesmo à noite. Estrelas e meteoros continuam aparecendo de qualquer forma.',
    '{}: {}, {:.0f} {}, ветер {:.0f} {}   ·   небо — {}': '{}: {}, {:.0f} {}, vento {:.0f} {}   ·   céu — {}',
    'км/ч': 'km/h',
    'м/с': 'm/s',
    'миль/ч': 'mi/h',
    'выдумано': 'inventado',
    'за окном': 'lá fora',
    'нет данных': 'sem dados',
    'ничего': 'nada',
    'ясно': 'limpo',
    'облака': 'nuvens',
    'серость': 'cinza',
    'дождь': 'chuva',
    'снег': 'neve',
    'гроза': 'tempestade',
    'туман': 'nevoeiro',
    'Мои темы': 'Meus temas',
    'Создать тему': 'Criar tema',
    'Редактор': 'Editor',
    'Всё, что лежит рядом с программой. Отсюда тему отправляют на экран, правят, копируют и упаковывают для пересылки.': 'Tudo o que está junto do programa. Daqui o tema é enviado para a tela, editado, copiado e empacotado para enviar a outra pessoa.',
    'Обновить': 'Atualizar',
    'Из папки…': 'De uma pasta…',
    'Из архива…': 'De um pacote…',
    'На экран': 'Para a tela',
    'Изменить': 'Editar',
    'Открыть в редакторе': 'Abrir no editor',
    'Переименовать': 'Renomear',
    'открыта': 'aberto',
    'нет предпросмотра': 'sem pré-visualização',
    '{} слоёв · {} · {:g} кадр/с': '{} camadas · {} · {:g} fps',
    'автор: {}   ·   {}': 'autor: {}   ·   {}',
    'Сделать эту тему текущей: она уйдёт на экран водянки и откроется на главной.': 'Tornar este tema o atual: ele vai para a tela da water cooler e abre na página inicial.',
    'Открыть тему в редакторе: слои, надписи, цвета, дневной и ночной вид.': 'Abrir o tema no editor: camadas, textos, cores, visão diurna e noturna.',
    'Сменить название темы. Папка на диске получит то же имя — тема и папка ходят вместе.': 'Mudar o nome do tema. A pasta no disco recebe o mesmo nome — tema e pasta andam juntos.',
    'Название, автор и пояснение к теме. Эти строки уедут вместе с ней к другому человеку. Название меняет и имя папки на диске.': 'Nome, autor e descrição do tema. Esses textos vão junto quando o tema for enviado a outra pessoa. O nome também muda o nome da pasta no disco.',
    'Копия темы целиком, вместе с кадрами и шрифтами. Спросит имя. Оригинал не пострадает.': 'Uma cópia completa do tema, com quadros e fontes. Vai perguntar o nome. O original fica intacto.',
    'Упаковать тему в один файл, чтобы переслать. Всё, на что она ссылается, попадёт внутрь.': 'Empacotar o tema em um único arquivo para enviar. Tudo que ele usa vai junto.',
    'Картинка для показа: ночь и день рядом, с именем, автором и списком умений. Чтобы выложить или прислать.': 'Uma imagem para mostrar: noite e dia lado a lado, com nome, autor e o que o tema sabe fazer. Para publicar ou enviar.',
    'Убрать тему из витрины. Папка остаётся на диске и переименовывается с точки — вернуть можно в проводнике.': 'Remover o tema da vitrine. A pasta continua no disco e recebe um ponto no início do nome — dá para trazer de volta pelo Explorador de Arquivos.',
    'Новая тема': 'Novo tema',
    'Как её назвать?': 'Como quer chamá-lo?',
    'Переименовать тему': 'Renomear o tema',
    'Новое название:': 'Novo nome:',
    'Копия темы': 'Cópia do tema',
    'Как назвать копию?': 'Como quer chamar a cópia?',
    'Копирую тему': 'Copiando o tema',
    ' — копия': ' — cópia',
    'Скопировать': 'Copiar',
    'Создать': 'Criar',
    'Отмена': 'Cancelar',
    'Сохранить': 'Salvar',
    'Упаковываю тему': 'Empacotando o tema',
    'Упаковать тему': 'Empacotar o tema',
    'Куда упаковать тему': 'Onde salvar o pacote',
    'Архив с темой': 'Pacote do tema',
    'Папка с темой': 'Pasta do tema',
    'В папке нет описания темы.': 'Não há descrição do tema na pasta.',
    'Распаковываю тему': 'Descompactando o tema',
    'Открыть архив': 'Abrir o pacote',
    'Тема добавлена. Открыть её?': 'Tema adicionado. Abrir agora?',
    'Картинка для показа': 'Imagem para mostrar',
    'Убрать тему': 'Remover o tema',
    'Эта тема сейчас открыта. Откройте другую и попробуйте снова.': 'Este tema está aberto agora. Abra outro e tente de novo.',
    'Убрать «{}» из витрины?\n\nПапка останется на диске — она просто получит точку в начале имени. Вернуть можно переименованием в проводнике.': 'Remover «{}» da vitrine?\n\nA pasta continua no disco — só recebe um ponto no início do nome. Dá para trazer de volta renomeando pelo Explorador de Arquivos.',
    'Готово, файлов внутри: {}.\n{}\n\nПоказать в папке?': 'Pronto, arquivos dentro: {}.\n{}\n\nMostrar na pasta?',
    'Готово:\n{}\n\nОткрыть копию?': 'Pronto:\n{}\n\nAbrir a cópia?',
    'Готово:\n{}\n\nОткрыть её?': 'Pronto:\n{}\n\nAbrir agora?',
    'Описание темы': 'Descrição do tema',
    'Что увидят другие': 'O que os outros vão ver',
    'эти строки уедут вместе с темой': 'esses textos vão junto com o tema',
    'Название': 'Nome',
    'Автор': 'Autor',
    'Описание': 'Descrição',
    '{} из {}   {}': '{} de {}   {}',
    'имя не может быть пустым': 'o nome não pode ficar vazio',
    'в архиве нет описания темы': 'o pacote não tem descrição do tema',
    'без названия': 'sem nome',
    'тема': 'tema',
    'День и ночь': 'Dia e noite',
    'Картинки': 'Imagens',
    'Движение': 'Movimento',
    'Погода': 'Clima',
    'Видео': 'Gráficos',
    'Процессор': 'Processador',
    'Осмотр машины': 'Inspeção da máquina',
    'что на этой машине есть, что отвечает и чего не хватает': 'o que esta máquina tem, o que responde e o que está faltando',
    'Что на этой машине': 'O que esta máquina tem',
    'те же проверки, что делает start.bat перед первым запуском. Опрос датчиков занимает несколько секунд.': 'as mesmas verificações que o start.bat faz antes da primeira execução. A leitura dos sensores leva alguns segundos.',
    'что на этой машине отвечает, а что молчит. Опрос датчиков занимает несколько секунд.': 'o que responde nesta máquina e o que fica em silêncio. A leitura dos sensores leva alguns segundos.',
    'Осмотреть': 'Inspecionar',
    '  смотрю…': '  verificando…',
    'Осмотр ещё не делался.': 'Ainda não foi feita nenhuma inspeção.',
    'всё в порядке': 'tudo em ordem',
    'важных замечаний: {}': 'observações importantes: {}',
    'команда в буфере обмена': 'o comando está na área de transferência',
    'не вышло': 'não deu certo',
    'Оформление программы': 'Aparência do programa',
    'Единицы и время': 'Unidades e horário',
    'Сборка кадра': 'Montagem do quadro',
    'это про машину, а не про тему: настройка остаётся при смене темы': 'isso é sobre a máquina, não sobre o tema: a configuração continua ao trocar de tema',
    'В один поток': 'Em uma thread',
    'В два потока': 'Em duas threads',
    'В четыре': 'Em quatro',
    'Пусть решит сама': 'Deixar o programa decidir',
    'Кадр собирается кусками, и куски друг о друге не знают — их можно готовить разом. Картинка выходит та же до последней точки, проверено. Но выигрыш во времени невелик и на быстрой машине теряется в разбросе: если панель и так укладывается в отпущенное время, кадров в секунду не прибавится. Смысл — уложиться на слабой машине.': 'O quadro é montado em pedaços, e os pedaços não dependem uns dos outros — dá para prepará-los ao mesmo tempo. A imagem final fica idêntica até o último ponto, isso já foi conferido. Mas o ganho de tempo é pequeno, e numa máquina rápida ele se perde na variação natural: se o painel já dá conta do tempo disponível, os quadros por segundo não vão aumentar. A ideia é ajudar máquinas mais fracas a acompanhar o ritmo.',
    'в чём показывать градусы, время и дату — и в окне, и на экране': 'em que formato mostrar graus, hora e data — na janela e na tela',
    'Градусы': 'Graus',
    'Ветер': 'Vento',
    'и в окне, и в надписях на экране': 'na janela e nos textos da tela',
    'и температура железа, и погода': 'na temperatura do hardware e no clima',
    'Цельсий': 'Celsius',
    'Фаренгейт': 'Fahrenheit',
    'Часы': 'Relógio',
    'двенадцать часов дописывают AM и PM': 'o formato de 12 horas acrescenta AM e PM',
    '24 часа': '24 horas',
    '12 часов': '12 horas',
    'Порядок чисел в дате': 'Ordem dos números na data',
    'день, месяц и год': 'dia, mês e ano',
    'Неделя начинается': 'A semana começa',
    'по этому дню тема считает номер дня': 'o tema conta o número do dia a partir deste',
    'с понедельника': 'na segunda-feira',
    'с воскресенья': 'no domingo',
    'Как это будет выглядеть': 'Como vai ficar',
    'по умолчанию всё берётся из самой Windows: какие единицы и форматы там выбраны, такие и здесь': 'por padrão, tudo é herdado do próprio Windows: as unidades e formatos escolhidos lá valem aqui também',
    'Тема может брать готовые {time}, {date} и {deg} — они идут по этой настройке. А может писать свой вид через {now:…} — тогда настройка его не тронет.': 'O tema pode usar prontos {time}, {date} e {deg} — eles seguem esta configuração. Ou pode definir seu próprio formato com {now:…} — aí a configuração não interfere.',
    'Запуск': 'Inicialização',
    'Датчики': 'Sensores',
    'Погода и адрес': 'Clima e endereço',
    'Производительность': 'Desempenho',
    'О программе': 'Sobre',
    'кто это написал и на каких условиях этим можно пользоваться': 'quem escreveu isto e em que condições pode ser usado',
    'как выглядит само окно программы, а не картинка на экране': 'como a janela do programa se parece, e não a imagem da tela',
    'что делать при включении компьютера и при закрытии окна': 'o que fazer ao ligar o computador e ao fechar a janela',
    'откуда берутся значения и что из этого читается сейчас': 'de onde vêm os valores e o que está sendo lido agora',
    'чем платим за плавность: памятью, процессором, качеством': 'o preço da fluidez: memória, processador, qualidade',
    'откуда брать прогноз, восход и закат': 'de onde vêm a previsão, o nascer e o pôr do sol',
    'Светлое или тёмное': 'Claro ou escuro',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за темой панели.': '«Como no Windows» segue o tema do sistema, «Como na tela» segue o tema do painel.',
    'Как на экране': 'Como na tela',
    'Светлое': 'Claro',
    'Тёмное': 'Escuro',
    'Язык': 'Idioma',
    'Смена языка': 'Troca de idioma',
    'В теме есть несохранённые правки. Сохранить их?': 'O tema tem alterações não salvas. Salvar agora?',
    'Изменения применятся при следующем запуске.': 'As alterações valem a partir da próxima abertura do programa.',
    'Ярлык на рабочем столе': 'Atalho na área de trabalho',
    'чтобы запускать не из папки, а с рабочего стола': 'para abrir direto da área de trabalho, sem entrar na pasta',
    'Не получилось. Рабочий стол может быть закрыт для записи.': 'Não deu certo. A área de trabalho pode estar bloqueada para gravação.',
    'Запускать вместе с Windows': 'Iniciar junto com o Windows',
    'через app.bat, чтобы поднялись права на температуру': 'via app.bat, para liberar acesso às temperaturas',
    'Язык темы': 'Idioma do tema',
    'Как в окне': 'Igual à janela',
    'на нём говорит панель на экране водянки: погода, подпись ветра, названия слоёв в редакторе': 'é o idioma do painel na tela da water cooler: clima, unidade do vento, nomes das camadas no editor',
    'Запускать при входе в систему': 'Iniciar ao entrar no sistema',
    'записью .desktop в автозапуске': 'por um arquivo .desktop na inicialização automática',
    'Открывать сразу свёрнутым в трей': 'Abrir já minimizado na bandeja',
    'окно не мешает, панель работает': 'a janela não atrapalha, e o painel continua funcionando',
    'Сразу включать экран': 'Ligar a tela automaticamente',
    'не нажимать кнопку каждый раз': 'sem precisar clicar no botão toda vez',
    'Крестик прячет в трей, а не закрывает': 'O X minimiza para a bandeja em vez de fechar',
    'иначе панель погаснет вместе с окном': 'senão o painel apaga junto com a janela',
    'Автозапуск': 'Inicialização automática',
    'Не удалось изменить запись в реестре.': 'Não foi possível alterar a entrada no registro.',
    'Что опрашивать': 'O que consultar',
    'выключенный источник не опрашивается вообще — это и есть экономия': 'uma fonte desligada não é consultada — é aí que se economiza',
    'Что читается прямо сейчас': 'O que está sendo lido agora',
    'значения как есть, до перевода в выбранные единицы: температуры здесь всегда в Цельсиях, на них настраивается реакция слоёв': 'os valores brutos, antes da conversão para as unidades escolhidas: aqui as temperaturas são sempre em Celsius, e é nelas que a reação das camadas é configurada',
    'Процессор, память, диски, сеть': 'Processador, memória, discos, rede',
    'почти бесплатно': 'praticamente de graça',
    'Видеокарта': 'Placa de vídeo',
    'через nvidia-smi': 'via nvidia-smi',
    'Температуры': 'Temperaturas',
    'нужны права администратора': 'requer direitos de administrador',
    'их отдаёт само ядро': 'o próprio kernel fornece',
    'через nvidia-smi или /sys/class/drm': 'via nvidia-smi ou /sys/class/drm',
    'Погода, восход и закат': 'Clima, nascer e pôr do sol',
    'нужен интернет': 'requer internet',
    'Место': 'Local',
    'по нему берётся прогноз, а заодно время восхода и заката — от них панель светлеет и темнеет': 'é usado para a previsão, e também para o nascer e o pôr do sol — que fazem o painel clarear e escurecer',
    'Название города на любом языке. Нажми «Найти» и выбери из списка.': 'Nome da cidade em qualquer idioma. Clique em «Buscar» e escolha na lista.',
    'Найти': 'Buscar',
    'По адресу в сети': 'Por endereço na internet',
    'Выбрать это место': 'Usar este local',
    '  ищу…': '  buscando…',
    '  ничего не нашлось': '  nada encontrado',
    '  не вышло: {}': '  falhou: {}',
    'место: {}': 'local: {}',
    'Сейчас: {}   ({:.3f}, {:.3f}) {}': 'Agora: {}   ({:.3f}, {:.3f}) {}',
    'Место не выбрано — прогноза не будет, а восход и закат возьмутся запасные: 07:00 и 20:00.': 'Nenhum local escolhido — não vai haver previsão, e o nascer e o pôr do sol usarão valores padrão: 07:00 e 20:00.',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за тем, день сейчас на панели или ночь.': '«Como no Windows» segue o tema do sistema, «Como na tela» segue se o painel está em modo dia ou noite.',
    'Сейчас: {}   ({:.3f}, {:.3f})\n{}': 'Agora: {}   ({:.3f}, {:.3f})\n{}',
    'ночь': 'noite',
    'и день': 'e dia',
    'Проверить, как тема выглядит в дождь или метель, можно на главной — ряд справа от выбора дня и ночи.': 'Para ver como o tema fica na chuva ou na nevasca, use a página inicial — a fileira à direita da escolha de dia e noite.',
    'Источник прогноза': 'Fonte da previsão',
    'Без ключа и без регистрации': 'Sem chave e sem cadastro',
    'По ключу службы': 'Com chave do serviço',
    'свой источник': 'sua própria fonte',
    'Где что лежит в ответе': 'Onde cada coisa está na resposta',
    'В адресе можно писать {lat}, {lon} и {key} — программа подставит место и ключ. Нажмите «Спросить службу»: ответ разберётся на пути, и останется выбрать нужные из списков.': 'No endereço você pode usar {lat}, {lon} e {key} — o programa preenche o local e a chave. Clique em «Perguntar ao serviço»: a resposta é organizada em caminhos, e você só escolhe os certos nas listas.',
    'Спросить службу': 'Perguntar ao serviço',
    'Температура': 'Temperatura',
    'Состояние погоды числом': 'Condição do tempo em número',
    'Ощущается как': 'Sensação térmica',
    'Влажность': 'Umidade',
    'Минимум за сутки': 'Mínima do dia',
    'Максимум за сутки': 'Máxima do dia',
    'Восход': 'Nascer do sol',
    'Закат': 'Pôr do sol',
    'Ветер в': 'Vento em',
    'Восход записан как': 'O nascer do sol é gravado como',
    'iso — 2026-08-13T05:08, unix — число секунд, 12h — 05:08 AM, 24h — 05:08': 'iso — 2026-08-13T05:08, unix — número de segundos, 12h — 05:08 AM, 24h — 05:08',
    'Числа состояния': 'Números de condição',
    'wmo — служба уже отдаёт коды по стандарту ВМО. Своя таблица чисел прописывается в weather.json, см. справочник.': 'wmo — o serviço já fornece os códigos no padrão OMM. Uma tabela própria de números é definida em weather.json, veja o guia.',
    'служба ответила, полей нашлось: {}. Выберите нужные из списков и нажмите «Проверить».': 'o serviço respondeu, campos encontrados: {}. Escolha os certos nas listas e clique em «Verificar».',
    'Впишите адрес службы.': 'Digite o endereço do serviço.',
    'по умолчанию Open-Meteo: без ключа и без регистрации. Другие службы отвечают по-своему, поэтому у каждой свой переходник — выберите нужную, и программа сама переведёт её ответ в понятный панели вид.': 'por padrão é o Open-Meteo: sem chave e sem cadastro. Outros serviços respondem cada um à sua maneira, por isso cada um tem seu próprio adaptador — escolha o serviço certo, e o programa traduz a resposta para o formato que o painel entende.',
    'Ключ': 'Chave',
    'Ключ выдаёт сама служба при регистрации. Он хранится в weather.json рядом с программой.': 'A chave é fornecida pelo próprio serviço no cadastro. Ela fica guardada em weather.json, junto do programa.',
    'Адрес': 'Endereço',
    'Пусто — обычный адрес выбранной службы. Свой нужен для зеркала или своего сервера: полный адрес без вопросов и параметров, их программа допишет сама.': 'Vazio significa o endereço padrão do serviço escolhido. Um endereço próprio serve para um espelho ou servidor próprio: o endereço completo, sem interrogação nem parâmetros — o programa completa isso sozinho.',
    'Проверить': 'Verificar',
    'Обычный': 'Padrão',
    '  спрашиваю…': '  perguntando…',
    'Сначала выберите место — без него спрашивать не о чем.': 'Escolha um local primeiro — sem ele não há o que perguntar.',
    '{} отвечает: {}, {:.0f} {}, ветер {:.0f} {}. Записано.': '{} respondeu: {}, {:.0f} {}, vento {:.0f} {}. Salvo.',
    '\nВосхода и заката эта служба не даёт — считаем их сами по координатам.': '\nEsse serviço não informa o nascer e o pôr do sol — nós mesmos calculamos pelas coordenadas.',
    'Не отвечает или отвечает не тем: {}': 'Não responde, ou responde algo inesperado: {}',
    'Картинка и нагрузка': 'Imagem e desempenho',
    'эти значения хранятся внутри темы': 'esses valores ficam guardados dentro do tema',
    'Кадров в секунду': 'Quadros por segundo',
    'ниже 0.5 нельзя: экран уснёт': 'não pode ser menor que 0.5: a tela vai dormir',
    'Качество JPEG': 'Qualidade do JPEG',
    '1–100, влияет на размер кадра': '1–100, afeta o tamanho do quadro',
    'Сглаживание': 'Suavização',
    '2 или 3, больше — плавнее края': '2 ou 3, quanto maior, mais suaves as bordas',
    'Переход день/ночь, секунд': 'Transição dia/noite, segundos',
    'сколько длится смена вида': 'quanto tempo dura a troca de visual',
    'Сжимать кадры фона в памяти': 'Compactar os quadros de fundo na memória',
    'Сжатие без потерь: картинка та же до последнего бита, памяти уходит втрое меньше. Плата — около семи десятых миллисекунды на кадр. Переключение заставляет заново разобрать все кадры фона: на тяжёлой теме экран замрёт на несколько секунд.': 'Compactação sem perdas: a imagem fica idêntica até o último bit, e usa um terço da memória. O custo é cerca de sete décimos de milissegundo por quadro. Trocar essa opção faz todos os quadros de fundo serem processados de novo: em temas pesados, a tela pode travar por alguns segundos.',
    '      сейчас программа занимает {:.0f} МБ': '      o programa está usando {:.0f} MB agora',
    'Экран выключен': 'A tela está desligada',
    'Включите вывод на главной — здесь будет видно, сколько кадров получается на самом деле.': 'Ligue a saída na página inicial — aqui vai aparecer quantos quadros realmente são gerados.',
    'Задано {:g}, выходит {:.1f} кадр/с': 'Definido {:g}, obtendo {:.1f} fps',
    'Только запустились, счёт ещё набирается.': 'Acabou de começar, a contagem ainda está se ajustando.',
    'Успевает.': 'Está dando conta.',
    'Не успевает: {:.0f} %. Упирается либо в отрисовку — тогда помогут меньше сглаживание и меньше живых слоёв, — либо в канал до экрана: тогда снижайте качество JPEG, кадр станет легче.': 'Não está dando conta: {:.0f} %. O gargalo pode ser o desenho — nesse caso, ajuda reduzir a suavização e o número de camadas animadas — ou o canal até a tela: nesse caso, reduza a qualidade do JPEG para deixar o quadro mais leve.',
    'версия {} · автор {}': 'versão {} · por {}',
    'Открытая замена штатной программе для экрана водянки: контроллер TXW818, панель ST7701S, 960x480 по COM-порту.': 'Uma alternativa aberta ao programa original da tela de water cooler: controlador TXW818, painel ST7701S, 960x480 por porta COM.',
    'Лицензия': 'Licença',
    'Пользоваться, копировать и переделывать — можно.': 'Usar, copiar e modificar — pode.',
    'Зарабатывать на этом — нельзя.': 'Ganhar dinheiro com isso — não pode.',
    'Переделанное раздавать на тех же условиях и с указанием автора.': 'Distribuir versões modificadas nas mesmas condições e citando o autor.',
    'Условия распространяются и на программу, и на темы, которые с ней идут. Про коммерческое использование договариваются с автором письменно.': 'As condições valem tanto para o programa quanto para os temas que o acompanham. Uso comercial precisa de acordo por escrito com o autor.',
    'Открыть файл лицензии': 'Abrir o arquivo de licença',
    'Полный текст в сети': 'Texto completo online',
    'Файла LICENSE нет рядом с программой.': 'Não há um arquivo LICENSE junto do programa.',
    '      Наш файл — пересказ для человека. Юридическую силу имеет полный текст на сайте Creative Commons.': '      Nosso arquivo é um resumo em linguagem simples. O texto completo no site da Creative Commons é que vale legalmente.',
    'Чужое': 'De terceiros',
    'Температуры читает LibreHardwareMonitor — четыре файла .dll рядом с программой. Библиотека принадлежит своим авторам и идёт по своей лицензии, MPL 2.0.': 'As temperaturas são lidas pelo LibreHardwareMonitor — quatro arquivos .dll junto do programa. A biblioteca pertence aos seus próprios autores e segue sua própria licença, MPL 2.0.',
    'Не удалось открыть файл: {}': 'Não foi possível abrir o arquivo: {}',
    'Загрузка процессора, %': 'Uso do processador, %',
    'Температура процессора': 'Temperatura do processador',
    'Частота процессора, ГГц': 'Frequência do processador, GHz',
    'Потребление процессора, Вт': 'Consumo do processador, W',
    'Обороты вентилятора ЦП': 'Rotação do cooler da CPU',
    'Загрузка видеокарты, %': 'Uso da placa de vídeo, %',
    'Температура видеокарты': 'Temperatura da placa de vídeo',
    'Потребление видеокарты, Вт': 'Consumo da placa de vídeo, W',
    'Загрузка видеопамяти, %': 'Uso da memória de vídeo, %',
    'Занято видеопамяти, ГБ': 'Memória de vídeo usada, GB',
    'Частота видеокарты, МГц': 'Frequência da placa de vídeo, MHz',
    'Вентилятор видеокарты, %': 'Cooler da placa de vídeo, %',
    'Загрузка ОЗУ, %': 'Uso da RAM, %',
    'Занято ОЗУ, ГБ': 'RAM usada, GB',
    'Свободно ОЗУ, ГБ': 'RAM livre, GB',
    'Загрузка диска, %': 'Uso do disco, %',
    'Свободно на диске, ГБ': 'Espaço livre no disco, GB',
    'Приём из сети, МБ/с': 'Download da rede, MB/s',
    'Отдача в сеть, МБ/с': 'Upload para a rede, MB/s',
    'Температура платы': 'Temperatura da placa-mãe',
    'Погода: температура': 'Clima: temperatura',
    'Погода: ощущается как': 'Clima: sensação térmica',
    'Погода: влажность, %': 'Clima: umidade, %',
    'Погода: ветер, км/ч': 'Clima: vento, km/h',
    '— свой текст —': '— texto próprio —',
    'Загрузка процессора  23%': 'Uso do processador  23%',
    'Температура процессора  67 °C': 'Temperatura do processador  67 °C',
    'Частота процессора  4.85 ГГц': 'Frequência do processador  4.85 GHz',
    'Потребление процессора  142 Вт': 'Consumo do processador  142 W',
    'Загрузка видеокарты  41%': 'Uso da placa de vídeo  41%',
    'Температура видеокарты  51 °C': 'Temperatura da placa de vídeo  51 °C',
    'Потребление видеокарты  186 Вт': 'Consumo da placa de vídeo  186 W',
    'Видеопамять  9.9 ГБ': 'Memória de vídeo  9.9 GB',
    'Видеопамять  9.9 / 16 ГБ': 'Memória de vídeo  9.9 / 16 GB',
    'Загрузка ОЗУ  28%': 'Uso da RAM  28%',
    'ОЗУ  17.0 / 64 ГБ': 'RAM  17.0 / 64 GB',
    'Свободно на диске  231 ГБ': 'Espaço livre no disco  231 GB',
    'Приём из сети  11.4 МБ/с': 'Download da rede  11.4 MB/s',
    'Отдача в сеть  2.3 МБ/с': 'Upload para a rede  2.3 MB/s',
    'Время работы  5ч 49м': 'Tempo ligado  5h 49m',
    'Часы  как выбрано в настройках': 'Relógio  conforme escolhido nas configurações',
    'Часы с секундами  как выбрано в настройках': 'Relógio com segundos  conforme escolhido nas configurações',
    'Дата  как выбрано в настройках': 'Data  conforme escolhido nas configurações',
    'Дата коротко  как выбрано в настройках': 'Data curta  conforme escolhido nas configurações',
    'Погода: температура со знаком настройки  12 °C': 'Clima: temperatura na escala configurada  12 °C',
    'Часы  14:30': 'Relógio  14:30',
    'Часы с секундами  14:30:45': 'Relógio com segundos  14:30:45',
    'Часы 12-часовые  02:30 PM': 'Relógio 12 horas  02:30 PM',
    'Часы 12-часовые с секундами  02:30:45 PM': 'Relógio 12 horas com segundos  02:30:45 PM',
    'Дата  03.08.2026': 'Data  03.08.2026',
    'Дата  03.08.26': 'Data  03.08.26',
    'Дата  2026-08-03': 'Data  2026-08-03',
    'Дата  03 August': 'Data  03 de agosto',
    'День недели  Monday': 'Dia da semana  Monday',
    'Погода кратко  Дождь': 'Clima resumido  Chuva',
    'Погода подробно  Небольшой дождь': 'Clima detalhado  Chuva fraca',
    'Погода и температура  Дождь  12 °C': 'Clima e temperatura  Chuva  12 °C',
    'Погода подробно и температура': 'Clima detalhado e temperatura',
    'Погода: только температура  12 °C': 'Clima: só a temperatura  12 °C',
    'Погода: ощущается как  10 °C': 'Clima: sensação térmica  10 °C',
    'Погода: минимум и максимум  8…15 °C': 'Clima: mínima e máxima, só os números',
    'Погода: ветер  4 км/ч': 'Clima: vento  4 km/h',
    'Погода: влажность  78 %': 'Clima: umidade  78 %',
    'Погода: город и температура': 'Clima: cidade e temperatura',
    'Погода: всё вместе': 'Clima: tudo junto',
    'по центру': 'centro',
    'слева, по середине': 'esquerda, meio',
    'справа, по середине': 'direita, meio',
    'слева сверху': 'superior esquerdo',
    'по центру сверху': 'superior centro',
    'справа сверху': 'superior direito',
    'слева снизу': 'inferior esquerdo',
    'по центру снизу': 'inferior centro',
    'справа снизу': 'inferior direito',
    'слева направо': 'esquerda para direita',
    'справа налево': 'direita para esquerda',
    'снизу вверх': 'baixo para cima',
    'сверху вниз': 'cima para baixo',
    'сверху': 'cima',
    'снизу': 'baixo',
    'слева': 'esquerda',
    'справа': 'direita',
    'заполнить с обрезкой': 'preencher e cortar',
    'вписать целиком': 'ajustar por inteiro',
    'растянуть': 'esticar',
    'как есть': 'como está',
    'нет': 'nenhum',
    'по диагонали': 'na diagonal',
    'текст': 'texto',
    'прямоугольник': 'retângulo',
    'квадрат': 'quadrado',
    'овал': 'oval',
    'круг': 'círculo',
    'линия': 'linha',
    'стрелка': 'seta',
    'звезда': 'estrela',
    'полоса': 'barra',
    'кольцо': 'anel',
    'картинка': 'imagem',
    'туда-обратно': 'vai e volta',
    'по кругу': 'em círculo',
    'затухание': 'desvanecimento',
    'движение': 'movimento',
    'поворот': 'rotação',
    'цвет': 'cor',
    'размер': 'tamanho',
    'Arial обычный': 'Arial normal',
    'Arial жирный': 'Arial negrito',
    'Segoe UI обычный': 'Segoe UI normal',
    'Segoe UI жирный': 'Segoe UI negrito',
    'Consolas обычный': 'Consolas normal',
    'Consolas жирный': 'Consolas negrito',
    'Tahoma обычный': 'Tahoma normal',
    'Tahoma жирный': 'Tahoma negrito',
    'Verdana обычный': 'Verdana normal',
    'Verdana жирный': 'Verdana negrito',
    'Calibri обычный': 'Calibri normal',
    'Calibri жирный': 'Calibri negrito',
    'Искать по названию, типу и тексту слоя. Рядом — показывать все слои, только видимые ночью или только днём.': 'Buscar por nome, tipo e texto da camada. Ao lado: mostrar todas as camadas, só as visíveis à noite ou só as de dia.',
    'Подпись для себя, в списке слева. На картинку не влияет.': 'Um nome só para você, mostrado na lista à esquerda. Não afeta a imagem.',
    'Отступ слева, в точках. Начало координат — левый верхний угол.': 'Distância da esquerda, em pontos. A origem das coordenadas é o canto superior esquerdo.',
    'Отступ сверху, в точках.': 'Distância do topo, em pontos.',
    'Куда линия приходит по горизонтали.': 'Até onde a linha vai na horizontal.',
    'Куда линия приходит по вертикали.': 'Até onde a linha vai na vertical.',
    'Наклон слоя в градусах, по часовой стрелке.': 'Inclinação da camada em graus, no sentido horário.',
    'Растянуть слой вширь. 1 — как есть, 2 — вдвое шире.': 'Esticar a camada na largura. 1 é o tamanho original, 2 é o dobro da largura.',
    'Растянуть слой ввысь. 1 — как есть, 0.5 — вдвое ниже.': 'Esticar a camada na altura. 1 é o tamanho original, 0.5 é metade da altura.',
    'Насколько слой прозрачен: 0 — не видно совсем, 1 — плотно.': 'O quanto a camada é transparente: 0 é invisível, 1 é totalmente sólido.',
    'Что написать. В фигурных скобках подставляются показания: {cpu_load:.0f}% даст «37%».': 'O que escrever. As chaves recebem as leituras: {cpu_load:.0f}% vira «37%».',
    'Готовые надписи: часы, дата, погода, загрузка. Выбери — и текст подставится сам.': 'Textos prontos: relógio, data, clima, uso. Escolha um e o texto se preenche sozinho.',
    'Файл шрифта. Любой из системы или положенный рядом с темой.': 'Arquivo de fonte. Qualquer uma do sistema, ou colocada junto do tema.',
    'Высота букв в точках.': 'Altura das letras em pontos.',
    'Влезть в ширину': 'Ajustar à largura',
    'Влезть в столько точек по ширине. Длинная надпись сама уменьшится, короткая останется как есть. 0 — не ужимать, тогда длинное уедет за край.': 'Ajustar a esse tanto de pontos de largura. Um texto longo encolhe sozinho, um curto fica como está. 0 — não encolher, e o texto longo passa da borda.',
    'Цвет букв.': 'Cor das letras.',
    'За какую точку слой держится координатами. По центру — удобно для цифр, что меняют длину.': 'A qual ponto da camada as coordenadas se referem. Pelo centro é prático para números que mudam de tamanho.',
    'Цвет обводки. Помогает читать надпись поверх пёстрой картинки.': 'Cor do contorno. Ajuda a ler o texto sobre uma imagem cheia de detalhes.',
    'Толщина обводки букв в точках.': 'Espessura do contorno das letras em pontos.',
    'Ширина слоя в точках.': 'Largura da camada em pontos.',
    'Высота слоя в точках.': 'Altura da camada em pontos.',
    'Скругление углов. 0 — прямые углы.': 'Arredondamento dos cantos. 0 é cantos retos.',
    'Основной цвет заливки.': 'Cor principal do preenchimento.',
    'Второй цвет: заливка станет переходом от первого ко второму.': 'Segunda cor: o preenchimento vira um gradiente da primeira para a segunda.',
    'В какую сторону идёт переход между двумя цветами.': 'Em que direção vai o gradiente entre as duas cores.',
    'Толщина линии или окантовки в точках.': 'Espessura da linha ou da borda em pontos.',
    'Откуда берётся число: загрузка, температура, погода.': 'De onde vem o número: uso, temperatura, clima.',
    'Какому значению соответствует пустая полоса или дуга.': 'A que valor corresponde a barra ou o arco vazio.',
    'Какому значению соответствует полная полоса или дуга.': 'A que valor corresponde a barra ou o arco cheio.',
    'В какую сторону растёт заполнение.': 'Em que direção o preenchimento cresce.',
    'Цвет незаполненной части. Можно не задавать.': 'Cor da parte não preenchida. Pode deixar em branco.',
    'Радиус в точках. Координаты — это центр, а не угол.': 'Raio em pontos. As coordenadas são o centro, não um canto.',
    'Радиус впадин между лучами звезды.': 'Raio das reentrâncias entre as pontas da estrela.',
    'Сколько лучей у звезды.': 'Quantas pontas a estrela tem.',
    'Повернуть звезду на столько градусов.': 'Girar a estrela por este tanto de graus.',
    'Толщина дуги в точках.': 'Espessura do arco em pontos.',
    'С какой стороны у кольца вырез.': 'De que lado fica a abertura do anel.',
    'Ширина выреза в градусах. 60 — небольшой, 180 — половина круга.': 'Largura da abertura em graus. 60 é pequena, 180 é meio círculo.',
    'Заполнять дугу с другого конца, навстречу обычному.': 'Preencher o arco a partir do outro lado, na direção contrária à usual.',
    'Скруглить концы — дуга или линия смотрится мягче.': 'Arredondar as pontas — o arco ou a linha fica com aparência mais suave.',
    'Размер наконечника стрелки в точках.': 'Tamanho da ponta da seta em pontos.',
    'Файл картинки или папка с кадрами. Папка листается как ролик.': 'Arquivo de imagem ou pasta de quadros. Uma pasta é reproduzida como um vídeo.',
    'Что делать, если картинка не совпала с отведённым местом.': 'O que fazer quando a imagem não bate com o espaço reservado.',
    'Своя частота листания кадров. Ставь ту, с которой резал ролик, иначе он поедет быстрее или медленнее задуманного.': 'Taxa própria de quadros. Use a mesma taxa em que o vídeo foi criado, senão ele vai rodar mais rápido ou mais devagar do que deveria.',
    'Включи, если PNG выгружены из DaVinci: там цвет уже умножен на прозрачность, и без этого по мягкому краю пойдёт тёмная каёмка.': 'Ative se os PNGs vieram do DaVinci: lá a cor já vem multiplicada pela transparência, e sem isso aparece uma borda escura nas bordas suaves.',
    'Поднять непрозрачность, если объект вырезался полупрозрачным и выглядит блёклым. 1 — не трогать, 1.5 — заметно плотнее.': 'Aumentar a opacidade se o objeto foi recortado meio transparente e parece desbotado. 1 não altera nada, 1.5 fica visivelmente mais sólido.',
    'Поворот, °': 'Rotação, °',
    'Шире': 'Mais largo',
    'Выше': 'Mais alto',
    'Прозрачность': 'Transparência',
    'Второй цвет': 'Segunda cor',
    'Переход цвета': 'Gradiente de cor',
    'Готовая надпись': 'Texto pronto',
    'Текст': 'Texto',
    'Шрифт': 'Fonte',
    'Размер': 'Tamanho',
    'Цвет': 'Cor',
    'Держится за': 'Ponto de referência',
    'Обводка': 'Contorno',
    'Толщина обводки': 'Espessura do contorno',
    'Ширина': 'Largura',
    'Высота': 'Altura',
    'Скругление': 'Arredondamento',
    'Заливка': 'Preenchimento',
    'Окантовка': 'Borda',
    'Толщина': 'Espessura',
    'Наконечник': 'Ponta da seta',
    'Мягкие концы': 'Pontas suaves',
    'X конца': 'X final',
    'Y конца': 'Y final',
    'Радиус': 'Raio',
    'Радиус впадин': 'Raio das reentrâncias',
    'Лучей': 'Pontas',
    'Наклон, °': 'Inclinação, °',
    'Показание': 'Leitura',
    'Пусто при': 'Vazio em',
    'Полно при': 'Cheio em',
    'Направление': 'Direção',
    'Цвет заполнения': 'Cor de preenchimento',
    'Цвет пустоты': 'Cor do vazio',
    'Толщина дуги': 'Espessura do arco',
    'Вырез': 'Abertura',
    'Вырез, °': 'Abertura, °',
    'Наоборот': 'Ao contrário',
    'Картинка': 'Imagem',
    'Как вписать': 'Como ajustar',
    'PNG из DaVinci': 'PNG do DaVinci',
    'Плотнее': 'Mais sólido',
    'Что показывает': 'O que mostra',
    'Где и какого размера': 'Onde e de que tamanho',
    'Как выглядит': 'Como aparece',
    'Прочее': 'Outros',
    'новый текст': 'novo texto',
    'новый прямоугольник': 'novo retângulo',
    'новый квадрат': 'novo quadrado',
    'новый овал': 'novo oval',
    'новый круг': 'novo círculo',
    'новая линия': 'nova linha',
    'новая стрелка': 'nova seta',
    'новая звезда': 'nova estrela',
    'новая полоса': 'nova barra',
    'новое кольцо': 'novo anel',
    'новая картинка': 'nova imagem',
    'слой': 'camada',
    'блок': 'bloco',
    ' копия': ' cópia',
    '←  К темам': '←  Voltar aos temas',
    'Сохранить как…': 'Salvar como…',
    'Вернуть с диска': 'Recarregar do disco',
    'Открыть тему…': 'Abrir um tema…',
    'Описание темы…': 'Detalhes do tema…',
    '●  Магнит': '●  Ímã',
    '○  Магнит': '○  Ímã',
    '●  Сетка {}': '●  Grade {}',
    '○  Сетка': '○  Grade',
    'Выровнять:': 'Alinhar:',
    'К левому краю экрана': 'À borda esquerda da tela',
    'По центру экрана вбок': 'Ao centro da tela na horizontal',
    'К правому краю экрана': 'À borda direita da tela',
    'К верхнему краю экрана': 'À borda superior da tela',
    'По центру экрана вниз': 'Ao centro da tela na vertical',
    'К нижнему краю экрана': 'À borda inferior da tela',
    'Размер:': 'Tamanho:',
    'Уменьшить выбранные слои на десятую часть': 'Reduzir as camadas selecionadas em um décimo',
    'Увеличить выбранные слои на десятую часть': 'Aumentar as camadas selecionadas em um décimo',
    '. Работает и на нескольких сразу: выдели их в списке с Ctrl или Shift.': '. Funciona em várias de uma vez: selecione-as na lista com Ctrl ou Shift.',
    'Показать на экране': 'Mostrar na tela',
    'Остановить показ': 'Parar de mostrar',
    'Слои · нижние перекрываются верхними': 'Camadas · as de baixo ficam atrás das de cima',
    'все': 'todas',
    'день': 'dia',
    'Скрыть': 'Ocultar',
    'Копия': 'Copiar',
    'Удалить': 'Excluir',
    'Добавить:': 'Adicionar:',
    'Режим правки:': 'Modo de edição:',
    'Ночной вид': 'Visão noturna',
    'Переход': 'Transição',
    'Дневной вид': 'Visão diurna',
    'Прокрутка перехода:': 'Avançar a transição:',
    'Двигается только выбранный слой. Стрелки — на пиксель, Shift+стрелки — на десять.\nМагнит притягивает к краям и центрам соседей; Alt при перетаскивании временно его отключает.\nНесколько слоёв разом: Ctrl+щелчок или Shift+щелчок в списке.\nCtrl+Z отменить · Ctrl+Y вернуть · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S сохранить · Delete удалить': 'Só a camada selecionada se move. As setas movem por pixel, Shift+setas por dez.\nO ímã atrai para as bordas e centros dos vizinhos; Alt durante o arraste desativa isso por um instante.\nVárias camadas de uma vez: Ctrl+clique ou Shift+clique na lista.\nCtrl+Z desfazer · Ctrl+Y refazer · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S salvar · Delete excluir',
    'Тип блока': 'Tipo de bloco',
    'Экран': 'Tela',
    'Фон под всеми блоками:': 'Fundo sob todos os blocos:',
    'Убрать дневной': 'Remover diurno',
    'нет дневного — фон ночной круглые сутки': 'sem fundo diurno — o fundo noturno fica o dia todo',
    'Сжимать кадры фона': 'Compactar os quadros de fundo',
    'памяти вчетверо меньше, картинка та же': 'um quarto da memória, mesma imagem',
    'кадры фона будут сжаты — готовлю заново': 'os quadros de fundo serão compactados — preparando de novo',
    'кадры фона будут распакованы — готовлю заново': 'os quadros de fundo serão descompactados — preparando de novo',
    'Здесь настраивается только движение.\nЧто именно меняется — задаётся\nв ночном и дневном видах.': 'Aqui só se configura o movimento.\nO que exatamente muda é definido\nnas visões noturna e diurna.',
    'Правки уходят в дневной вид': 'As edições vão para a visão diurna',
    'Сбросить': 'Redefinir',
    'Переход к дневному виду': 'Transição para a visão diurna',
    'настроен': 'configurado',
    'не настроен': 'não configurado',
    'Что меняется:': 'O que muda:',
    'Отрезок перехода, %': 'Trecho da transição, %',
    'Начало': 'Início',
    'Середина': 'Meio',
    'Окончание': 'Fim',
    'Повтор по времени': 'Repetir com o tempo',
    'Период, секунд': 'Período, segundos',
    'Как повторять': 'Como repetir',
    'Показать в момент': 'Mostrar no momento',
    'сброс': 'redefinir',
    'Реакция на датчик': 'Reação a um sensor',
    'Датчик': 'Leitura',
    'Начинает меняться при': 'Começa a mudar em',
    'Полностью при': 'Completo em',
    'Показать при значении': 'Mostrar no valor',
    'отменять нечего': 'nada para desfazer',
    'отменено': 'desfeito',
    'возвращать нечего': 'nada para refazer',
    'возвращено': 'refeito',
    'слой скопирован': 'camada copiada',
    'слой вырезан': 'camada recortada',
    'в буфере нет слоя': 'não há camada na área de transferência',
    'слой вставлен': 'camada colada',
    'магнит включён': 'ímã ativado',
    'магнит выключен': 'ímã desativado',
    'сетка выключена': 'grade desativada',
    'сетка по {} точек': 'grade a cada {} pontos',
    'размер {:+.0f} % у {} слоёв': 'tamanho {:+.0f} % em {} camadas',
    'показано {} из {}': 'mostrando {} de {}',
    'X {}  Y {}   (без магнита)': 'X {}  Y {}   (sem ímã)',
    'X {}  Y {}{}': 'X {}  Y {}{}',
    '   ({} слоёв)': '   ({} camadas)',
    'шрифт скопирован в папку fonts': 'fonte copiada para a pasta fonts',
    'не смог скопировать: {}': 'não foi possível copiar: {}',
    'переименовано, папка тоже': 'renomeado, a pasta também',
    'папку переименовать не вышло: {}': 'não foi possível renomear a pasta: {}',
    'описание изменено, не забудь сохранить': 'descrição alterada, não esqueça de salvar',
    'дневной вид блока сброшен': 'a visão diurna do bloco foi redefinida',
    'ошибка: {}': 'erro: {}',
    'сохранено': 'salvo',
    'открыто: ': 'aberto: ',
    'экран не найден': 'tela não encontrada',
    'показ прерван: {}': 'exibição interrompida: {}',
    '{} · редактор · {} — {}': '{} · editor · {} — {}',
    'Удалить слой «{}»?': 'Excluir a camada «{}»?',
    'Удалить выбранные слои ({} шт.)?': 'Excluir as camadas selecionadas ({} no total)?',
    'Выбери файл шрифта': 'Escolha o arquivo de fonte',
    'Шрифты': 'Fontes',
    'Папка с кадрами (Отмена - выбрать файл)': 'Pasta de quadros (Cancelar para escolher um arquivo)',
    'Открыть': 'Abrir',
    'Вернуть': 'Recarregar',
    'Папка с темой (Отмена — выбрать файл)': 'Pasta do tema (Cancelar para escolher um arquivo)',
    'В папке нет файлов описания темы (.json).\n\nФайл темы должен лежать рядом с папками кадров.': 'Não há arquivos de descrição do tema (.json) na pasta.\n\nO arquivo do tema precisa estar junto das pastas de quadros.',
    'Какой файл темы открыть': 'Qual arquivo de tema abrir',
    'Файл темы': 'Arquivo do tema',
    'Описание панели': 'Arquivo do painel',
    'Не удалось прочитать файл:\n{}': 'Não foi possível ler o arquivo:\n{}',
    'Это не похоже на тему: нет раздела layers.': 'Isso não parece um tema: não há a seção layers.',
    'Тема ссылается на то, чего нет рядом с её файлом:\n\n  ': 'O tema referencia coisas que não estão junto do seu arquivo:\n\n  ',
    '\n\nПеренеси эти папки в {}': '\n\nMova estas pastas para {}',
    'Не найден файл описания: {}': 'Arquivo de descrição não encontrado: {}',
    'осмотр машины': 'inspeção da máquina',
    '[д/н] ': '[s/n] ',
    'прервано': 'interrompido',
    'язык уже выбран': 'o idioma já está escolhido',
    'язык Windows подсказывал другой: {}': 'o idioma do Windows sugeria outro: {}',
    'язык выбран по языку Windows': 'o idioma foi escolhido a partir do Windows',
    'поменять можно в Настройках -> Оформление программы': 'pode ser trocado em Configurações -> Aparência do programa',
    'Библиотеки': 'Bibliotecas',
    'сборка кадров и всё рисование': 'montagem dos quadros e todo o desenho',
    'загрузка процессора, память, диски, сеть': 'uso do processador, memória, discos, rede',
    'разговор с экраном по COM-порту': 'comunicação com a tela pela porta COM',
    'само окно программы': 'a própria janela do programa',
    'температура процессора, видеокарты AMD и Intel': 'temperatura do processador, placas de vídeo AMD e Intel',
    'переходы цвета и мягкие края': 'gradientes de cor e bordas suaves',
    'значок рядом с часами': 'o ícone junto do relógio',
    'переустанови Python, отметив «tcl/tk and IDLE»': 'reinstale o Python marcando «tcl/tk and IDLE»',
    'Поставить всё разом:': 'Instalar tudo de uma vez:',
    'Без обязательных библиотек осматривать дальше нечего.': 'Sem as bibliotecas obrigatórias, não há mais nada para verificar.',
    'Права': 'Permissões',
    'права администратора есть': 'há direitos de administrador',
    'прав администратора нет': 'não há direitos de administrador',
    'без них температуры процессора не будет вовсе': 'sem eles, a temperatura do processador simplesmente não vai aparecer',
    'запусти start.bat, а программу - через app.bat': 'execute start.bat, e o programa em si, via app.bat',
    'Библиотека датчиков': 'Biblioteca de sensores',
    'нет рядом с программой': 'não está junto do programa',
    'возьми из архива LibreHardwareMonitor и положи сюда': 'pegue no pacote do LibreHardwareMonitor e coloque aqui',
    'все четыре файла на месте': 'os quatro arquivos estão no lugar',
    'снял пометку «из интернета»': 'a marca «baixado da internet» foi removida',
    'помечен как скачанный из интернета': 'marcado como baixado da internet',
    'Свойства файла -> галочка «Разблокировать»': 'Propriedades do arquivo -> caixa «Desbloquear»',
    'пометки «из интернета» ни на одном нет': 'nenhum deles tem a marca «baixado da internet»',
    'Железо': 'Hardware',
    'процессор': 'processador',
    'видеокарта': 'placa de vídeo',
    'название выяснить не удалось': 'não foi possível descobrir o nome',
    'ядер {}, потоков {}': '{} núcleos, {} threads',
    'оперативной памяти {:.0f} ГБ': '{:.0f} GB de memória',
    'системный диск {}': 'disco do sistema {}',
    'опрашиваю железо, это занимает несколько секунд…': 'consultando o hardware, isso leva alguns segundos…',
    'загрузка процессора': 'uso do processador',
    'температура процессора': 'temperatura do processador',
    'частота процессора': 'frequência do processador',
    'загрузка памяти': 'uso da memória',
    'загрузка диска': 'uso do disco',
    'приём из сети': 'download da rede',
    'загрузка видеокарты': 'uso da placa de vídeo',
    'температура видеокарты': 'temperatura da placa de vídeo',
    'занято видеопамяти': 'memória de vídeo usada',
    'потребление видеокарты': 'consumo da placa de vídeo',
    'не читается': 'não é lido',
    'температура читается': 'a temperatura é lida',
    'выбран датчик: ': 'sensor escolhido: ',
    'источник открылся, но отдаёт нули': 'a fonte abriu, mas só retorna zeros',
    'библиотека отдаёт нули по всем ядрам: нет прав администратора': 'a biblioteca retorna zeros em todos os núcleos: faltam direitos de administrador',
    'так бывает без прав администратора: запусти start.bat': 'isso acontece sem direitos de administrador: execute start.bat',
    'источник не найден': 'nenhuma fonte encontrada',
    'запусти программу через app.bat': 'execute o programa via app.bat',
    'нужны права администратора и четыре .dll рядом': 'são necessários direitos de administrador e os quatro .dll junto',
    'видеокарта читается': 'a placa de vídeo é lida',
    'нет источника показаний': 'não há fonte de leituras',
    'положи System.Numerics.Vectors.dll рядом с программой': 'coloque System.Numerics.Vectors.dll junto do programa',
    'нужен для видеокарт не Nvidia — на месте': 'necessário para placas que não são Nvidia — está no lugar',
    'нужен, чтобы читать видеокарту не Nvidia': 'necessário para ler placas que não são Nvidia',
    'особых прав не нужно': 'não precisa de permissões especiais',
    'температуры читает ядро, оно их и так отдаёт': 'as temperaturas são lidas pelo kernel, que já as fornece de qualquer jeito',
    'температуры читает ядро, библиотека датчиков не нужна': 'as temperaturas são lidas pelo kernel, a biblioteca de sensores não é necessária',
    'ядро Linux': 'o kernel do Linux',
    'ядро Linux (drm)': 'o kernel do Linux (drm)',
    'ядро не отдаёт температур: нет /sys/class/hwmon': 'o kernel não fornece temperaturas: não há /sys/class/hwmon',
    'ядро не отдаёт показаний видеокарты: нет /sys/class/drm': 'o kernel não fornece leituras da placa de vídeo: não há /sys/class/drm',
    'ядро не выложило /sys/class/hwmon: посмотри, загружен ли модуль датчиков процессора': 'o kernel não disponibilizou /sys/class/hwmon: verifique se o módulo de sensores do processador está carregado',
    'для Nvidia нужен nvidia-smi, для AMD - драйвер amdgpu в /sys/class/drm': 'para Nvidia é preciso nvidia-smi; para AMD, o driver amdgpu em /sys/class/drm',
    'библиотеке не хватает файла System.Numerics.Vectors.dll — без него показаний видеокарты не будет. Возьми его из архива LibreHardwareMonitor': 'falta o arquivo System.Numerics.Vectors.dll na biblioteca — sem ele não haverá leituras da placa de vídeo. Pegue-o no pacote do LibreHardwareMonitor',
    'для Nvidia хватит драйвера, для AMD и Intel нужна библиотека датчиков и права': 'para Nvidia basta o driver; para AMD e Intel é preciso a biblioteca de sensores e as permissões',
    'psutil (процессор, память, диски, сеть): ': 'psutil (processador, memória, discos, rede): ',
    'есть': 'presente',
    'НЕ УСТАНОВЛЕН': 'NÃO INSTALADO',
    'процессор: ': 'processador: ',
    'видеокарта: ': 'placa de vídeo: ',
    'показания видеокарты: ': 'leituras da placa de vídeo: ',
    'показания видеокарты: НЕТ — ': 'leituras da placa de vídeo: NENHUMA — ',
    'показания видеокарты: НЕТ — нет ни nvidia-smi, ни LibreHardwareMonitorLib.dll': 'leituras da placa de vídeo: NENHUMA — não há nvidia-smi nem LibreHardwareMonitorLib.dll',
    'температура процессора: читается ({})': 'temperatura do processador: lida ({})',
    'библиотека напрямую': 'biblioteca direta',
    'через WMI': 'via WMI',
    'способ не указан': 'modo não informado',
    ', вспомогательных сборок: {}': ', assemblies auxiliares: {}',
    '  выбран датчик: ': '  sensor escolhido: ',
    '  все найденные датчики процессора:': '  todos os sensores do processador encontrados:',
    'температура процессора: НЕТ — ': 'temperatura do processador: NENHUMA — ',
    '  ВНИМАНИЕ: программа запущена без прав администратора.': '  ATENÇÃO: o programa está rodando sem direitos de administrador.',
    '  Температуру процессора без них прочитать невозможно в принципе:': '  Sem eles é simplesmente impossível ler a temperatura do processador:',
    '  Windows не даёт доступ к регистрам процессора обычным программам.': '  O Windows não dá acesso aos registradores do processador para programas comuns.',
    '  Права администратора есть. Положи рядом LibreHardwareMonitorLib.dll': '  Os direitos de administrador estão presentes. Coloque LibreHardwareMonitorLib.dll junto do programa',
    '  и HidSharp.dll, либо запусти саму LibreHardwareMonitor в фоне.': '  e HidSharp.dll, ou execute o próprio LibreHardwareMonitor em segundo plano.',
    'рядом нет LibreHardwareMonitorLib.dll (положи её в папку с программой)': 'não há LibreHardwareMonitorLib.dll junto do programa (coloque-o na pasta do programa)',
    'библиотека есть, но нет pythonnet. Выполни: pip install pythonnet': 'a biblioteca está presente, mas falta o pythonnet. Execute: pip install pythonnet',
    'библиотека заблокирована Windows как скачанная из интернета. Свойства файла -> галочка «Разблокировать»': 'o Windows bloqueou a biblioteca por ter sido baixada da internet. Propriedades do arquivo -> caixa «Desbloquear»',
    'погода: получена{}{}': 'clima: recebido{}{}',
    ' от ': ' de ',
    ' для ': ' para ',
    '  восход и закат: ': '  nascer e pôr do sol: ',
    'погода: НЕТ — ': 'clima: NENHUM — ',
    'ещё не загружена': 'ainda não carregado',
    'не выбрано место — укажи город в настройках, раздел «Погода»': 'nenhum local escolhido — informe a cidade nas configurações, seção «Clima»',
    'не смог заглянуть в порты': 'não foi possível verificar as portas',
    'экран найден': 'tela encontrada',
    'ни на одном COM-порту': 'em nenhuma porta COM',
    'проверь кабель от помпы к разъёму USB на плате': 'verifique o cabo da bomba até o conector USB na placa',
    'а вот что на портах есть:': 'mas aqui está o que há nas portas:',
    'COM-портов не найдено вообще': 'nenhuma porta COM foi encontrada',
    'погода выключена в настройках': 'o clima está desligado nas configurações',
    'прогноз получен': 'previsão recebida',
    'восход {}   закат {}   ({})': 'nascer do sol {}   pôr do sol {}   ({})',
    'свой расчёт': 'calculado por nós',
    'прогноза нет': 'não há previsão',
    'источник не ответил': 'a fonte não respondeu',
    'проверь интернет и место в Настройках -> Погода и адрес': 'verifique a internet e o local em Configurações -> Clima e endereço',
    'не смог просмотреть темы': 'não foi possível percorrer os temas',
    'названия железа нигде не вписаны руками': 'nenhum nome de hardware foi digitado manualmente em lugar algum',
    '«{}»: {} слоёв с вписанным названием': '«{}»: {} camadas com nome digitado',
    'Заменить, чтобы тема сама называла ваше железо?': 'Substituir para o tema nomear seu hardware automaticamente?',
    'оставил как было': 'deixado como estava',
    'тема поправлена': 'tema corrigido',
    'не смог записать тему': 'não foi possível gravar o tema',
    'Записываю в настройки': 'Gravando nas configurações',
    'железо записано': 'o hardware foi gravado',
    'опрос nvidia-smi': 'consulta ao nvidia-smi',
    'включён': 'ativado',
    'выключен, он тут не нужен': 'desativado, não é necessário aqui',
    'Температуру прочитать нечем. Выключить её опрос?': 'Não há como ler a temperatura. Desativar essa consulta?',
    'опрос температур выключен': 'consulta de temperaturas desativada',
    'Итог': 'Resumo',
    'Всё на месте. Запускай app.bat.': 'Está tudo certo. Pode executar app.bat.',
    'Без этого программа будет работать не полностью:': 'Sem isto, o programa não vai funcionar por completo:',
    'Мелочи, жить можно:': 'Detalhes pequenos, dá para viver com eles:',
    'Когда поправишь - запусти start.bat ещё раз.': 'Quando corrigir, execute start.bat de novo.',
}

POGODA = {
    0: ("Limpo", "Céu limpo"),
    1: ("Limpo", "Predominantemente limpo"),
    2: ("Nuvens", "Parcialmente nublado"),
    3: ("Nublado", "Nublado"),
    45: ("Nevoeiro", "Nevoeiro"),
    48: ("Nevoeiro", "Nevoeiro gelado"),
    51: ("Chuvisco", "Chuvisco fraco"),
    53: ("Chuvisco", "Chuvisco"),
    55: ("Chuvisco", "Chuvisco forte"),
    56: ("Gelo", "Chuvisco gelado"),
    57: ("Gelo", "Chuvisco gelado forte"),
    61: ("Chuva", "Chuva fraca"),
    63: ("Chuva", "Chuva"),
    65: ("Chuva", "Chuva forte"),
    66: ("Gelo", "Chuva gelada"),
    67: ("Gelo", "Chuva gelada forte"),
    71: ("Neve", "Neve fraca"),
    73: ("Neve", "Neve"),
    75: ("Neve", "Neve forte"),
    77: ("Neve", "Grãos de neve"),
    80: ("Aguaceiros", "Aguaceiros fracos"),
    81: ("Aguaceiros", "Aguaceiros"),
    82: ("Aguaceiros", "Aguaceiros fortes"),
    85: ("Neve", "Aguaceiros de neve"),
    86: ("Neve", "Aguaceiros de neve fortes"),
    95: ("Trovoada", "Trovoada"),
    96: ("Trovoada", "Trovoada com granizo"),
    99: ("Trovoada", "Trovoada forte com granizo"),
}

SOKRASHENO = {
    1: "Predom. limpo",
    57: "Chuvisco gelado f.",
    86: "Aguaceiros de neve f.",
    96: "Trovoada c/ granizo",
    99: "Trovoada forte c/ granizo",
}
