#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  Итальянский: слова программы и слова погоды.
#  Часть проекта EOne screen.
#
#  Автор: EOne
#  Лицензия: CC BY-NC-SA 4.0 — использование в коммерческих целях
#  запрещено без письменного разрешения автора. См. файл LICENSE.
#
"""yazyk_it.py - итальянский. Устройство описано в yazyk_es.py.

ПЕРЕВОД СДЕЛАН С ПОМОЩЬЮ ИИ и носителем языка не проверялся. Русский
и английский написаны автором, остальные пять - нет. Если вы говорите
на этом языке и видите ошибку или корявость, поправьте: строку можно
менять прямо здесь, а ключ трогать нельзя.

"""

SLOVAR = {
    # Готовые надписи, которые всегда по-английски:
    # они просят {weather_en}, а не {weather}.
    "Weather short  Rain": "Meteo breve, sempre in inglese  Rain",
    "Weather full  Light rain": "Meteo dettagliato, sempre in inglese  Light rain",
    "Weather and temperature  Rain  12 °C": "Meteo e temperatura, sempre in inglese  Rain  12 °C",
    "Weather full and temperature": "Meteo dettagliato e temperatura, sempre in inglese",
    "Weather: feels like  10 °C": "Meteo: percepita, sempre in inglese  10 °C",
    "Weather: wind  4 km/h": "Meteo: vento, sempre in inglese  4 km/h",
    "Weather: humidity  78 %": "Meteo: umidità, sempre in inglese  78 %",
    "Weather: everything": "Meteo: tutto insieme, sempre in inglese",
    # Значения движка: подпись видит человек, а в тему уходит
    # русское слово - его подставляет сама программа.
    "плавно": "morbido",
    "средне": "medio",
    "резко": "netto",

    'Главная': 'Home',
    'Темы': 'Temi',
    'Настройки': 'Impostazioni',
    'экран водянки': 'schermo della pompa AIO',
    'экран выключен': 'schermo spento',
    'экран: {} · {:.0f} кадр/с': 'schermo: {} · {:.0f} fps',
    'переход {:.0f} с': 'transizione {:.0f} s',
    'тема отправлена на экран': 'tema inviato allo schermo',
    'перезапускаю экран…': 'riavvio lo schermo…',
    'сбой обновления: {}': 'aggiornamento non riuscito: {}',
    '{} — экран выключен': '{} — schermo spento',
    '{} — {} ({:.1f} кадр/с, {})': '{} — {} ({:.1f} fps, {})',
    'Включить или выключить экран': 'Accendi o spegni lo schermo',
    'Показать окно': 'Mostra la finestra',
    'Выход': 'Esci',
    'Пауза': 'Pausa',
    'Продолжить': 'Riprendi',
    'Перечитать тему': 'Rileggi il tema',
    '{} · {} — {} ({:.1f} кадр/с, тема {})': '{} · {} — {} ({:.1f} fps, tema {})',
    'по солнцу': 'in base al sole',
    'как в Windows': 'come Windows',
    'всегда ночная': 'sempre notte',
    'всегда дневная': 'sempre giorno',
    'запускается': 'in avvio',
    'остановлена': 'ferma',
    'на паузе': 'in pausa',
    'слишком много сбоев': 'troppi errori',
    'Сохранить правки?': 'Salvare le modifiche?',
    'Несохранённые правки пропадут. Продолжить?': 'Le modifiche non salvate andranno perse. Continuare?',
    'Это не похоже на тему: нет слоёв.': 'Non sembra un tema: mancano i livelli.',
    'Моя тема': 'Il mio tema',
    'Сейчас на экране': 'Sullo schermo ora',
    'Что показывать': 'Cosa mostrare',
    'Погода на экране': 'Meteo sullo schermo',
    'Включить экран': 'Accendi lo schermo',
    'Выключить экран': 'Spegni lo schermo',
    'Перезапустить': 'Riavvia',
    'выключен': 'spento',
    'работает': 'attivo',
    'работает · {:.0f} кадр/с': 'attivo · {:.0f} fps',
    '(прогноз не пришёл)': '(previsioni non arrivate)',
    'готовлю кадры фона': 'preparo i fotogrammi di sfondo',
    'тема: ': 'tema: ',
    'погода': 'meteo',
    'днём': 'di giorno',
    'ночью': 'di notte',
    'восход {}   закат {}   сейчас {:.0f} % дня': 'alba {}   tramonto {}   ora {:.0f} % del giorno',
    '   (прогноз не пришёл)': '   (previsioni non arrivate)',
    'отправлено кадров {}': 'fotogrammi inviati {}',
    'сбоев {}': 'errori {}',
    '{:g} кадр/с': '{:g} fps',
    'не удалось собрать кадр: {}': 'impossibile comporre il fotogramma: {}',
    'кадры фона не листаются, чтобы окно не тратило лишнего': 'i fotogrammi di sfondo non scorrono qui, per non appesantire la finestra',
    'Начать или прекратить вывод картинки на экран водянки.': "Avvia o interrompi l'invio dell'immagine allo schermo della pompa AIO.",
    'Придержать вывод, не закрывая порт. Экран замрёт на последнем кадре.': "Sospende l'invio senza chiudere la porta. Lo schermo resta fermo sull'ultimo fotogramma.",
    'Заново открыть порт и поздороваться с экраном. Выручает, если картинка сбилась или порт подвис.': "Riapre la porta e saluta di nuovo lo schermo. Utile se l'immagine si è rovinata o la porta si è bloccata.",
    'Яркость подсветки экрана водянки. Уходит на экран, когда отпустишь ползунок.': 'Luminosità della retroilluminazione dello schermo. Viene inviata quando rilasci il cursore.',
    'По солнцу': 'In base al sole',
    'Как в Windows': 'Come Windows',
    'Ночь': 'Notte',
    'День': 'Giorno',
    'Светлеет на рассвете и темнеет на закате, по времени восхода и заката в твоём городе.': "Si schiarisce all'alba e si scurisce al tramonto, secondo gli orari di alba e tramonto della tua città.",
    'Следит за оформлением Windows: светлая тема — дневной вид, тёмная — ночной.': 'Segue il tema di Windows: chiaro vuol dire vista giorno, scuro vuol dire vista notte.',
    'Всегда ночной вид, независимо от времени.': "Sempre vista notte, qualunque sia l'ora.",
    'Всегда дневной вид, независимо от времени.': "Sempre vista giorno, qualunque sia l'ora.",
    'По прогнозу': 'Dalle previsioni',
    'Ясно': 'Sereno',
    'Пасмурно': 'Nuvoloso',
    'Дождь': 'Pioggia',
    'Гроза': 'Temporale',
    'Снег': 'Neve',
    'Метель': 'Bufera di neve',
    'Туман': 'Nebbia',
    'Мороз': 'Gelo',
    'Жара': 'Caldo',
    'Показывать настоящий прогноз.': 'Mostra le previsioni reali.',
    'Показать «{}» так, будто оно за окном: {:+.0f} {}, ветер {:.0f} {}. Прогноз никуда не девается.': 'Mostra «{}» come se fosse fuori: {:+.0f} {}, vento {:.0f} {}. Le previsioni restano lì, non si perdono.',
    'Показывать дождь, снег, туман и грозу на дневной теме.': 'Mostra pioggia, neve, nebbia e temporali nella vista giorno.',
    'То же на ночной. Звёзды и метеоры останутся в любом случае.': 'Lo stesso di notte. Stelle e meteore restano comunque.',
    '{}: {}, {:.0f} {}, ветер {:.0f} {}   ·   небо — {}': '{}: {}, {:.0f} {}, vento {:.0f} {}   ·   cielo — {}',
    'км/ч': 'km/h',
    'м/с': 'm/s',
    'миль/ч': 'mph',
    'выдумано': 'inventato',
    'за окном': 'fuori',
    'нет данных': 'nessun dato',
    'ничего': 'niente',
    'ясно': 'sereno',
    'облака': 'nuvole',
    'серость': 'grigiore',
    'дождь': 'pioggia',
    'снег': 'neve',
    'гроза': 'temporale',
    'туман': 'nebbia',
    'Мои темы': 'I miei temi',
    'Создать тему': 'Nuovo tema',
    'Редактор': 'Editor',
    'Всё, что лежит рядом с программой. Отсюда тему отправляют на экран, правят, копируют и упаковывают для пересылки.': "Tutto ciò che si trova accanto al programma. Da qui il tema si invia allo schermo, si modifica, si copia e si comprime per l'invio.",
    'Обновить': 'Aggiorna',
    'Из папки…': 'Da una cartella…',
    'Из архива…': 'Da un archivio…',
    'На экран': 'Sullo schermo',
    'Изменить': 'Modifica',
    'Открыть в редакторе': "Apri nell'editor",
    'Переименовать': 'Rinomina',
    'открыта': 'aperto',
    'нет предпросмотра': 'nessuna anteprima',
    '{} слоёв · {} · {:g} кадр/с': '{} livelli · {} · {:g} fps',
    'автор: {}   ·   {}': 'autore: {}   ·   {}',
    'Сделать эту тему текущей: она уйдёт на экран водянки и откроется на главной.': 'Rende questo tema attivo: passa allo schermo della pompa AIO e si apre nella Home.',
    'Открыть тему в редакторе: слои, надписи, цвета, дневной и ночной вид.': "Apre il tema nell'editor: livelli, testi, colori, vista giorno e notte.",
    'Сменить название темы. Папка на диске получит то же имя — тема и папка ходят вместе.': 'Cambia il nome del tema. La cartella sul disco prende lo stesso nome — tema e cartella viaggiano insieme.',
    'Название, автор и пояснение к теме. Эти строки уедут вместе с ней к другому человеку. Название меняет и имя папки на диске.': "Nome, autore e descrizione del tema. Questi testi viaggiano con lui verso un'altra persona. Il nome cambia anche quello della cartella sul disco.",
    'Копия темы целиком, вместе с кадрами и шрифтами. Спросит имя. Оригинал не пострадает.': "Una copia completa del tema, con fotogrammi e font. Chiederà un nome. L'originale resta intatto.",
    'Упаковать тему в один файл, чтобы переслать. Всё, на что она ссылается, попадёт внутрь.': 'Comprime il tema in un unico file da inviare. Tutto ciò a cui fa riferimento finisce dentro.',
    'Картинка для показа: ночь и день рядом, с именем, автором и списком умений. Чтобы выложить или прислать.': "Un'immagine di presentazione: notte e giorno affiancati, con nome, autore e le funzioni del tema. Per pubblicarla o inviarla.",
    'Убрать тему из витрины. Папка остаётся на диске и переименовывается с точки — вернуть можно в проводнике.': 'Toglie il tema dalla vetrina. La cartella resta sul disco e viene rinominata con un punto davanti — si può ripristinare da Esplora file.',
    'Новая тема': 'Nuovo tema',
    'Как её назвать?': 'Come lo chiamiamo?',
    'Переименовать тему': 'Rinomina il tema',
    'Новое название:': 'Nuovo nome:',
    'Копия темы': 'Copia del tema',
    'Как назвать копию?': 'Come chiamare la copia?',
    'Копирую тему': 'Copio il tema',
    ' — копия': ' — copia',
    'Скопировать': 'Copia',
    'Создать': 'Crea',
    'Отмена': 'Annulla',
    'Сохранить': 'Salva',
    'Упаковываю тему': 'Comprimo il tema',
    'Упаковать тему': 'Comprimi il tema',
    'Куда упаковать тему': 'Dove comprimere il tema',
    'Архив с темой': 'Archivio del tema',
    'Папка с темой': 'Cartella del tema',
    'В папке нет описания темы.': "Nella cartella non c'è la descrizione del tema.",
    'Распаковываю тему': 'Estraggo il tema',
    'Открыть архив': "Apri l'archivio",
    'Тема добавлена. Открыть её?': 'Tema aggiunto. Aprirlo?',
    'Картинка для показа': 'Immagine di presentazione',
    'Убрать тему': 'Rimuovi il tema',
    'Эта тема сейчас открыта. Откройте другую и попробуйте снова.': 'Questo tema è aperto ora. Aprine un altro e riprova.',
    'Убрать «{}» из витрины?\n\nПапка останется на диске — она просто получит точку в начале имени. Вернуть можно переименованием в проводнике.': 'Togliere «{}» dalla vetrina?\n\nLa cartella resterà sul disco — riceverà solo un punto davanti al nome. Si può ripristinare rinominandola da Esplora file.',
    'Готово, файлов внутри: {}.\n{}\n\nПоказать в папке?': "Fatto, file all'interno: {}.\n{}\n\nMostrare nella cartella?",
    'Готово:\n{}\n\nОткрыть копию?': 'Fatto:\n{}\n\nAprire la copia?',
    'Готово:\n{}\n\nОткрыть её?': 'Fatto:\n{}\n\nAprirlo?',
    'Описание темы': 'Descrizione del tema',
    'Что увидят другие': 'Cosa vedranno gli altri',
    'эти строки уедут вместе с темой': 'questi testi viaggiano insieme al tema',
    'Название': 'Nome',
    'Автор': 'Autore',
    'Описание': 'Descrizione',
    '{} из {}   {}': '{} di {}   {}',
    'имя не может быть пустым': 'il nome non può essere vuoto',
    'в архиве нет описания темы': "nell'archivio non c'è la descrizione del tema",
    'без названия': 'senza nome',
    'тема': 'tema',
    'День и ночь': 'Giorno e notte',
    'Картинки': 'Immagini',
    'Движение': 'Movimento',
    'Погода': 'Meteo',
    'Видео': 'Grafica',
    'Процессор': 'Processore',
    'Осмотр машины': 'Controllo del PC',
    'что на этой машине есть, что отвечает и чего не хватает': "cosa c'è su questo PC, cosa risponde e cosa manca",
    'Что на этой машине': "Cosa c'è su questo PC",
    'те же проверки, что делает start.bat перед первым запуском. Опрос датчиков занимает несколько секунд.': "gli stessi controlli che fa start.bat prima del primo avvio. L'interrogazione dei sensori richiede qualche secondo.",
    'что на этой машине отвечает, а что молчит. Опрос датчиков занимает несколько секунд.': "cosa risponde su questo PC e cosa resta muto. L'interrogazione dei sensori richiede qualche secondo.",
    'Осмотреть': 'Controlla',
    '  смотрю…': '  controllo…',
    'Осмотр ещё не делался.': 'Il controllo non è ancora stato fatto.',
    'всё в порядке': 'tutto a posto',
    'важных замечаний: {}': 'avvisi importanti: {}',
    'команда в буфере обмена': 'comando copiato negli appunti',
    'не вышло': 'non è andata',
    'Оформление программы': 'Aspetto del programma',
    'Единицы и время': 'Unità e ora',
    'Сборка кадра': 'Composizione del fotogramma',
    'это про машину, а не про тему: настройка остаётся при смене темы': "riguarda il PC, non il tema: l'impostazione resta anche cambiando tema",
    'В один поток': 'Un thread',
    'В два потока': 'Due thread',
    'В четыре': 'Quattro',
    'Пусть решит сама': 'Decide il programma',
    'Кадр собирается кусками, и куски друг о друге не знают — их можно готовить разом. Картинка выходит та же до последней точки, проверено. Но выигрыш во времени невелик и на быстрой машине теряется в разбросе: если панель и так укладывается в отпущенное время, кадров в секунду не прибавится. Смысл — уложиться на слабой машине.': "Il fotogramma si compone a pezzi, e i pezzi non sanno nulla l'uno dell'altro — si possono preparare tutti insieme. L'immagine risulta identica fino all'ultimo punto, è stato verificato. Ma il guadagno di tempo è piccolo e su un PC veloce si perde nella variabilità: se il pannello rientra già nel tempo previsto, gli fps non aumentano. Serve soprattutto per farcela su un PC lento.",
    'в чём показывать градусы, время и дату — и в окне, и на экране': 'in che unità mostrare gradi, ora e data — sia nella finestra sia sullo schermo',
    'Градусы': 'Gradi',
    'Ветер': 'Vento',
    'и в окне, и в надписях на экране': 'sia nella finestra sia nelle scritte sullo schermo',
    'и температура железа, и погода': 'sia le temperature del PC sia il meteo',
    'Цельсий': 'Celsius',
    'Фаренгейт': 'Fahrenheit',
    'Часы': 'Orologio',
    'двенадцать часов дописывают AM и PM': 'il formato a 12 ore aggiunge AM e PM',
    '24 часа': '24 ore',
    '12 часов': '12 ore',
    'Порядок чисел в дате': 'Ordine dei numeri nella data',
    'день, месяц и год': 'giorno, mese e anno',
    'Неделя начинается': 'La settimana inizia',
    'по этому дню тема считает номер дня': 'il tema conta il numero del giorno a partire da qui',
    'с понедельника': 'di lunedì',
    'с воскресенья': 'di domenica',
    'Как это будет выглядеть': 'Come apparirà',
    'по умолчанию всё берётся из самой Windows: какие единицы и форматы там выбраны, такие и здесь': 'di norma tutto viene preso da Windows: le unità e i formati scelti lì valgono anche qui',
    'Тема может брать готовые {time}, {date} и {deg} — они идут по этой настройке. А может писать свой вид через {now:…} — тогда настройка его не тронет.': "Il tema può usare {time}, {date} e {deg} già pronti — seguono questa impostazione. Oppure può scrivere il proprio formato con {now:…} — in quel caso l'impostazione non lo tocca.",
    'Запуск': 'Avvio',
    'Датчики': 'Sensori',
    'Погода и адрес': 'Meteo e indirizzo',
    'Производительность': 'Prestazioni',
    'О программе': 'Informazioni',
    'кто это написал и на каких условиях этим можно пользоваться': "chi l'ha scritto e a quali condizioni si può usare",
    'как выглядит само окно программы, а не картинка на экране': "come appare la finestra del programma, non l'immagine sullo schermo",
    'что делать при включении компьютера и при закрытии окна': "cosa fare all'avvio del PC e alla chiusura della finestra",
    'откуда берутся значения и что из этого читается сейчас': 'da dove arrivano i valori e cosa si legge adesso',
    'чем платим за плавность: памятью, процессором, качеством': 'cosa si paga per la fluidità: memoria, processore, qualità',
    'откуда брать прогноз, восход и закат': 'da dove prendere previsioni, alba e tramonto',
    'Светлое или тёмное': 'Chiaro o scuro',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за темой панели.': '«Come Windows» segue il tema di sistema, «Come lo schermo» segue il tema del pannello.',
    'Как на экране': 'Come lo schermo',
    'Светлое': 'Chiaro',
    'Тёмное': 'Scuro',
    'Язык': 'Lingua',
    'Смена языка': 'Cambio lingua',
    'В теме есть несохранённые правки. Сохранить их?': 'Il tema ha modifiche non salvate. Salvarle?',
    'Изменения применятся при следующем запуске.': 'Le modifiche avranno effetto al prossimo avvio.',
    'Ярлык на рабочем столе': 'Collegamento sul desktop',
    'чтобы запускать не из папки, а с рабочего стола': 'per avviarlo dal desktop invece che dalla cartella',
    'Не получилось. Рабочий стол может быть закрыт для записи.': 'Non è riuscito. Il desktop potrebbe essere protetto in scrittura.',
    'Запускать вместе с Windows': 'Avvia con Windows',
    'через app.bat, чтобы поднялись права на температуру': 'tramite app.bat, per ottenere i permessi necessari alla temperatura',
    'Язык темы': 'Lingua del tema',
    'Как в окне': 'Come la finestra',
    'на нём говорит панель на экране водянки: погода, подпись ветра, названия слоёв в редакторе': "è la lingua del pannello sullo schermo della pompa AIO: meteo, unità del vento, nomi dei livelli nell'editor",
    'Запускать при входе в систему': "Avvia all'accesso al sistema",
    'записью .desktop в автозапуске': "con un file .desktop nell'avvio automatico",
    'Открывать сразу свёрнутым в трей': 'Apri già ridotto nella tray',
    'окно не мешает, панель работает': "la finestra non è d'intralcio, il pannello funziona comunque",
    'Сразу включать экран': 'Accendi subito lo schermo',
    'не нажимать кнопку каждый раз': 'senza dover premere il pulsante ogni volta',
    'Крестик прячет в трей, а не закрывает': 'La X nasconde nella tray invece di chiudere',
    'иначе панель погаснет вместе с окном': 'altrimenti il pannello si spegne insieme alla finestra',
    'Автозапуск': 'Avvio automatico',
    'Не удалось изменить запись в реестре.': 'Non è stato possibile modificare la voce nel registro.',
    'Что опрашивать': 'Cosa interrogare',
    'выключенный источник не опрашивается вообще — это и есть экономия': 'una fonte spenta non viene interrogata affatto — è proprio questo il risparmio',
    'Что читается прямо сейчас': 'Cosa si legge adesso',
    'значения как есть, до перевода в выбранные единицы: температуры здесь всегда в Цельсиях, на них настраивается реакция слоёв': 'i valori così come sono, prima della conversione nelle unità scelte: qui le temperature sono sempre in Celsius, ed è su questi valori che si impostano le reazioni dei livelli',
    'Процессор, память, диски, сеть': 'Processore, memoria, dischi, rete',
    'почти бесплатно': 'quasi gratis',
    'Видеокарта': 'Scheda video',
    'через nvidia-smi': 'tramite nvidia-smi',
    'Температуры': 'Temperature',
    'нужны права администратора': 'servono i permessi di amministratore',
    'их отдаёт само ядро': 'li fornisce direttamente il kernel',
    'через nvidia-smi или /sys/class/drm': 'tramite nvidia-smi o /sys/class/drm',
    'Погода, восход и закат': 'Meteo, alba e tramonto',
    'нужен интернет': 'serve internet',
    'Место': 'Luogo',
    'по нему берётся прогноз, а заодно время восхода и заката — от них панель светлеет и темнеет': 'da qui si prendono le previsioni, e con esse gli orari di alba e tramonto — sono loro a far schiarire e scurire il pannello',
    'Название города на любом языке. Нажми «Найти» и выбери из списка.': "Nome della città in qualsiasi lingua. Premi «Cerca» e scegli dall'elenco.",
    'Найти': 'Cerca',
    'По адресу в сети': 'Con un indirizzo di rete',
    'Выбрать это место': 'Scegli questo luogo',
    '  ищу…': '  cerco…',
    '  ничего не нашлось': '  nessun risultato',
    '  не вышло: {}': '  non è andata: {}',
    'место: {}': 'luogo: {}',
    'Сейчас: {}   ({:.3f}, {:.3f}) {}': 'Ora: {}   ({:.3f}, {:.3f}) {}',
    'Место не выбрано — прогноза не будет, а восход и закат возьмутся запасные: 07:00 и 20:00.': 'Nessun luogo scelto — non ci saranno previsioni, e alba e tramonto useranno i valori di riserva: 07:00 e 20:00.',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за тем, день сейчас на панели или ночь.': '«Come Windows» segue il tema di sistema, «Come lo schermo» segue se sul pannello è giorno o notte.',
    'Сейчас: {}   ({:.3f}, {:.3f})\n{}': 'Ora: {}   ({:.3f}, {:.3f})\n{}',
    'ночь': 'notte',
    'и день': 'e giorno',
    'Проверить, как тема выглядит в дождь или метель, можно на главной — ряд справа от выбора дня и ночи.': 'Per vedere come appare il tema con pioggia o neve, usa la Home — la riga a destra della scelta giorno/notte.',
    'Источник прогноза': 'Fonte delle previsioni',
    'Без ключа и без регистрации': 'Senza chiave né registrazione',
    'По ключу службы': 'Con la chiave del servizio',
    'свой источник': 'una fonte personalizzata',
    'Где что лежит в ответе': 'Dove si trova cosa nella risposta',
    'В адресе можно писать {lat}, {lon} и {key} — программа подставит место и ключ. Нажмите «Спросить службу»: ответ разберётся на пути, и останется выбрать нужные из списков.': "Nell'indirizzo puoi scrivere {lat}, {lon} e {key} — il programma inserirà luogo e chiave. Premi «Interroga il servizio»: la risposta verrà scomposta in percorsi, e non resterà che scegliere quelli giusti dagli elenchi.",
    'Спросить службу': 'Interroga il servizio',
    'Температура': 'Temperatura',
    'Состояние погоды числом': 'Condizione meteo come numero',
    'Ощущается как': 'Percepita',
    'Влажность': 'Umidità',
    'Минимум за сутки': 'Minima del giorno',
    'Максимум за сутки': 'Massima del giorno',
    'Восход': 'Alba',
    'Закат': 'Tramonto',
    'Ветер в': 'Vento in',
    'Восход записан как': "L'alba è scritta come",
    'iso — 2026-08-13T05:08, unix — число секунд, 12h — 05:08 AM, 24h — 05:08': 'iso — 2026-08-13T05:08, unix — numero di secondi, 12h — 05:08 AM, 24h — 05:08',
    'Числа состояния': 'Numeri di stato',
    'wmo — служба уже отдаёт коды по стандарту ВМО. Своя таблица чисел прописывается в weather.json, см. справочник.': 'wmo — il servizio restituisce già i codici secondo lo standard WMO. Una tabella personalizzata dei numeri si scrive in weather.json, vedi il manuale.',
    'служба ответила, полей нашлось: {}. Выберите нужные из списков и нажмите «Проверить».': 'il servizio ha risposto, campi trovati: {}. Scegli quelli giusti dagli elenchi e premi «Verifica».',
    'Впишите адрес службы.': "Scrivi l'indirizzo del servizio.",
    'по умолчанию Open-Meteo: без ключа и без регистрации. Другие службы отвечают по-своему, поэтому у каждой свой переходник — выберите нужную, и программа сама переведёт её ответ в понятный панели вид.': 'di norma Open-Meteo: senza chiave né registrazione. Gli altri servizi rispondono a modo loro, quindi ognuno ha il proprio adattatore — scegli quello giusto e il programma tradurrà da sé la risposta in un formato che il pannello capisce.',
    'Ключ': 'Chiave',
    'Ключ выдаёт сама служба при регистрации. Он хранится в weather.json рядом с программой.': 'La chiave la fornisce il servizio stesso alla registrazione. Viene salvata in weather.json accanto al programma.',
    'Адрес': 'Indirizzo',
    'Пусто — обычный адрес выбранной службы. Свой нужен для зеркала или своего сервера: полный адрес без вопросов и параметров, их программа допишет сама.': "Vuoto significa l'indirizzo normale del servizio scelto. Un indirizzo personalizzato serve per un mirror o un server proprio: l'indirizzo completo senza punto interrogativo né parametri, li aggiunge il programma.",
    'Проверить': 'Verifica',
    'Обычный': 'Predefinito',
    '  спрашиваю…': '  interrogo…',
    'Сначала выберите место — без него спрашивать не о чем.': "Scegli prima un luogo — senza non c'è nulla da chiedere.",
    '{} отвечает: {}, {:.0f} {}, ветер {:.0f} {}. Записано.': '{} risponde: {}, {:.0f} {}, vento {:.0f} {}. Salvato.',
    '\nВосхода и заката эта служба не даёт — считаем их сами по координатам.': '\nQuesto servizio non fornisce alba e tramonto — li calcoliamo noi dalle coordinate.',
    'Не отвечает или отвечает не тем: {}': 'Non risponde, o risponde in modo sbagliato: {}',
    'Картинка и нагрузка': 'Immagine e carico',
    'эти значения хранятся внутри темы': 'questi valori sono salvati dentro il tema',
    'Кадров в секунду': 'Fotogrammi al secondo',
    'ниже 0.5 нельзя: экран уснёт': 'non si può scendere sotto 0.5: lo schermo si addormenterebbe',
    'Качество JPEG': 'Qualità JPEG',
    '1–100, влияет на размер кадра': '1–100, influisce sulla dimensione del fotogramma',
    'Сглаживание': 'Antialiasing',
    '2 или 3, больше — плавнее края': '2 o 3, più alto vuol dire bordi più morbidi',
    'Переход день/ночь, секунд': 'Transizione giorno/notte, secondi',
    'сколько длится смена вида': 'quanto dura il cambio di vista',
    'Сжимать кадры фона в памяти': 'Comprimi i fotogrammi di sfondo in memoria',
    'Сжатие без потерь: картинка та же до последнего бита, памяти уходит втрое меньше. Плата — около семи десятых миллисекунды на кадр. Переключение заставляет заново разобрать все кадры фона: на тяжёлой теме экран замрёт на несколько секунд.': "Compressione senza perdite: l'immagine resta identica fino all'ultimo bit e la memoria usata è un terzo. Il costo è di circa sette decimi di millisecondo per fotogramma. Cambiare l'opzione fa ricomporre tutti i fotogrammi di sfondo: con un tema pesante lo schermo si ferma per qualche secondo.",
    '      сейчас программа занимает {:.0f} МБ': '      ora il programma occupa {:.0f} MB',
    'Экран выключен': 'Lo schermo è spento',
    'Включите вывод на главной — здесь будет видно, сколько кадров получается на самом деле.': "Attiva l'uscita nella Home — qui si vedrà quanti fotogrammi si ottengono davvero.",
    'Задано {:g}, выходит {:.1f} кадр/с': 'Impostato {:g}, si ottengono {:.1f} fps',
    'Только запустились, счёт ещё набирается.': 'Appena avviato, il conteggio si sta ancora accumulando.',
    'Успевает.': 'Ce la fa.',
    'Не успевает: {:.0f} %. Упирается либо в отрисовку — тогда помогут меньше сглаживание и меньше живых слоёв, — либо в канал до экрана: тогда снижайте качество JPEG, кадр станет легче.': 'Non ce la fa: {:.0f} %. Il collo di bottiglia è nel disegno — allora aiutano meno antialiasing e meno livelli attivi — oppure nel canale verso lo schermo: allora abbassa la qualità JPEG, il fotogramma diventerà più leggero.',
    'версия {} · автор {}': 'versione {} · di {}',
    'Открытая замена штатной программе для экрана водянки: контроллер TXW818, панель ST7701S, 960x480 по COM-порту.': "Un'alternativa open al programma di serie per lo schermo della pompa AIO: controller TXW818, pannello ST7701S, 960x480 via porta COM.",
    'Лицензия': 'Licenza',
    'Пользоваться, копировать и переделывать — можно.': 'Usarlo, copiarlo e modificarlo è permesso.',
    'Зарабатывать на этом — нельзя.': 'Guadagnarci sopra no.',
    'Переделанное раздавать на тех же условиях и с указанием автора.': "Le versioni modificate vanno distribuite alle stesse condizioni e citando l'autore.",
    'Условия распространяются и на программу, и на темы, которые с ней идут. Про коммерческое использование договариваются с автором письменно.': "Le condizioni valgono sia per il programma sia per i temi che lo accompagnano. Per l'uso commerciale bisogna accordarsi per iscritto con l'autore.",
    'Открыть файл лицензии': 'Apri il file della licenza',
    'Полный текст в сети': 'Testo completo online',
    'Файла LICENSE нет рядом с программой.': 'Il file LICENSE non è accanto al programma.',
    '      Наш файл — пересказ для человека. Юридическую силу имеет полный текст на сайте Creative Commons.': "      Il nostro file è una spiegazione in parole semplici. Il valore legale ce l'ha solo il testo integrale sul sito di Creative Commons.",
    'Чужое': 'Non nostro',
    'Температуры читает LibreHardwareMonitor — четыре файла .dll рядом с программой. Библиотека принадлежит своим авторам и идёт по своей лицензии, MPL 2.0.': 'Le temperature le legge LibreHardwareMonitor — quattro file .dll accanto al programma. La libreria appartiene ai suoi autori e ha una licenza propria, MPL 2.0.',
    'Не удалось открыть файл: {}': 'Impossibile aprire il file: {}',
    'Загрузка процессора, %': 'Carico processore, %',
    'Температура процессора': 'Temperatura processore',
    'Частота процессора, ГГц': 'Frequenza processore, GHz',
    'Потребление процессора, Вт': 'Consumo processore, W',
    'Обороты вентилятора ЦП': 'Giri ventola CPU',
    'Загрузка видеокарты, %': 'Carico scheda video, %',
    'Температура видеокарты': 'Temperatura scheda video',
    'Потребление видеокарты, Вт': 'Consumo scheda video, W',
    'Загрузка видеопамяти, %': 'Carico memoria video, %',
    'Занято видеопамяти, ГБ': 'Memoria video usata, GB',
    'Частота видеокарты, МГц': 'Frequenza scheda video, MHz',
    'Вентилятор видеокарты, %': 'Ventola scheda video, %',
    'Загрузка ОЗУ, %': 'Carico RAM, %',
    'Занято ОЗУ, ГБ': 'RAM usata, GB',
    'Свободно ОЗУ, ГБ': 'RAM libera, GB',
    'Загрузка диска, %': 'Carico disco, %',
    'Свободно на диске, ГБ': 'Spazio libero su disco, GB',
    'Приём из сети, МБ/с': 'Rete in entrata, MB/s',
    'Отдача в сеть, МБ/с': 'Rete in uscita, MB/s',
    'Температура платы': 'Temperatura scheda madre',
    'Погода: температура': 'Meteo: temperatura',
    'Погода: ощущается как': 'Meteo: percepita',
    'Погода: влажность, %': 'Meteo: umidità, %',
    'Погода: ветер, км/ч': 'Meteo: vento, km/h',
    '— свой текст —': '— testo personalizzato —',
    'Загрузка процессора  23%': 'Carico processore  23%',
    'Температура процессора  67 °C': 'Temperatura processore  67 °C',
    'Частота процессора  4.85 ГГц': 'Frequenza processore  4.85 GHz',
    'Потребление процессора  142 Вт': 'Consumo processore  142 W',
    'Загрузка видеокарты  41%': 'Carico scheda video  41%',
    'Температура видеокарты  51 °C': 'Temperatura scheda video  51 °C',
    'Потребление видеокарты  186 Вт': 'Consumo scheda video  186 W',
    'Видеопамять  9.9 ГБ': 'Memoria video  9.9 GB',
    'Видеопамять  9.9 / 16 ГБ': 'Memoria video  9.9 / 16 GB',
    'Загрузка ОЗУ  28%': 'Carico RAM  28%',
    'ОЗУ  17.0 / 64 ГБ': 'RAM  17.0 / 64 GB',
    'Свободно на диске  231 ГБ': 'Spazio libero su disco  231 GB',
    'Приём из сети  11.4 МБ/с': 'Rete in entrata  11.4 MB/s',
    'Отдача в сеть  2.3 МБ/с': 'Rete in uscita  2.3 MB/s',
    'Время работы  5ч 49м': 'Tempo di attività  5h 49m',
    'Часы  как выбрано в настройках': 'Orologio  come impostato',
    'Часы с секундами  как выбрано в настройках': 'Orologio con i secondi  come impostato',
    'Дата  как выбрано в настройках': 'Data  come impostato',
    'Дата коротко  как выбрано в настройках': 'Data breve  come impostato',
    'Погода: температура со знаком настройки  12 °C': 'Meteo: temperatura con il segno impostato  12 °C',
    'Часы  14:30': 'Orologio  14:30',
    'Часы с секундами  14:30:45': 'Orologio con i secondi  14:30:45',
    'Часы 12-часовые  02:30 PM': 'Orologio 12 ore  02:30 PM',
    'Часы 12-часовые с секундами  02:30:45 PM': 'Orologio 12 ore con i secondi  02:30:45 PM',
    'Дата  03.08.2026': 'Data  03.08.2026',
    'Дата  03.08.26': 'Data  03.08.26',
    'Дата  2026-08-03': 'Data  2026-08-03',
    'Дата  03 August': 'Data  03 August',
    'День недели  Monday': 'Giorno della settimana  Monday',
    'Погода кратко  Дождь': 'Meteo breve  Pioggia',
    'Погода подробно  Небольшой дождь': 'Meteo dettagliato  Pioggia leggera',
    'Погода и температура  Дождь  12 °C': 'Meteo e temperatura  Pioggia  12 °C',
    'Погода подробно и температура': 'Meteo dettagliato e temperatura',
    'Погода: только температура  12 °C': 'Meteo: solo temperatura  12 °C',
    'Погода: ощущается как  10 °C': 'Meteo: percepita  10 °C',
    'Погода: минимум и максимум  8…15 °C': 'Meteo: minima e massima  8…15 °C',
    'Погода: ветер  4 км/ч': 'Meteo: vento  4 km/h',
    'Погода: влажность  78 %': 'Meteo: umidità  78 %',
    'Погода: город и температура': 'Meteo: città e temperatura',
    'Погода: всё вместе': 'Meteo: tutto insieme',
    'по центру': 'al centro',
    'слева, по середине': 'a sinistra, al centro',
    'справа, по середине': 'a destra, al centro',
    'слева сверху': 'in alto a sinistra',
    'по центру сверху': 'in alto al centro',
    'справа сверху': 'in alto a destra',
    'слева снизу': 'in basso a sinistra',
    'по центру снизу': 'in basso al centro',
    'справа снизу': 'in basso a destra',
    'слева направо': 'da sinistra a destra',
    'справа налево': 'da destra a sinistra',
    'снизу вверх': "dal basso verso l'alto",
    'сверху вниз': "dall'alto verso il basso",
    'сверху': 'in alto',
    'снизу': 'in basso',
    'слева': 'a sinistra',
    'справа': 'a destra',
    'заполнить с обрезкой': 'riempi e ritaglia',
    'вписать целиком': 'adatta senza ritagliare',
    'растянуть': 'stira',
    'как есть': "così com'è",
    'нет': 'nessuno',
    'по диагонали': 'in diagonale',
    'текст': 'testo',
    'прямоугольник': 'rettangolo',
    'квадрат': 'quadrato',
    'овал': 'ovale',
    'круг': 'cerchio',
    'линия': 'linea',
    'стрелка': 'freccia',
    'звезда': 'stella',
    'полоса': 'barra',
    'кольцо': 'anello',
    'картинка': 'immagine',
    'туда-обратно': 'avanti e indietro',
    'по кругу': 'a ciclo',
    'затухание': 'dissolvenza',
    'движение': 'movimento',
    'поворот': 'rotazione',
    'цвет': 'colore',
    'размер': 'dimensione',
    'Arial обычный': 'Arial normale',
    'Arial жирный': 'Arial grassetto',
    'Segoe UI обычный': 'Segoe UI normale',
    'Segoe UI жирный': 'Segoe UI grassetto',
    'Consolas обычный': 'Consolas normale',
    'Consolas жирный': 'Consolas grassetto',
    'Tahoma обычный': 'Tahoma normale',
    'Tahoma жирный': 'Tahoma grassetto',
    'Verdana обычный': 'Verdana normale',
    'Verdana жирный': 'Verdana grassetto',
    'Calibri обычный': 'Calibri normale',
    'Calibri жирный': 'Calibri grassetto',
    'Искать по названию, типу и тексту слоя. Рядом — показывать все слои, только видимые ночью или только днём.': 'Cerca per nome, tipo e testo del livello. Accanto: mostra tutti i livelli, solo quelli visibili di notte o solo quelli visibili di giorno.',
    'Подпись для себя, в списке слева. На картинку не влияет.': "Un'etichetta solo per te, nell'elenco a sinistra. Non influisce sull'immagine.",
    'Отступ слева, в точках. Начало координат — левый верхний угол.': "Distanza da sinistra, in punti. L'origine delle coordinate è l'angolo in alto a sinistra.",
    'Отступ сверху, в точках.': "Distanza dall'alto, in punti.",
    'Куда линия приходит по горизонтали.': 'Dove arriva la linea in orizzontale.',
    'Куда линия приходит по вертикали.': 'Dove arriva la linea in verticale.',
    'Наклон слоя в градусах, по часовой стрелке.': 'Inclinazione del livello in gradi, in senso orario.',
    'Растянуть слой вширь. 1 — как есть, 2 — вдвое шире.': "Allunga il livello in larghezza. 1 — così com'è, 2 — il doppio più largo.",
    'Растянуть слой ввысь. 1 — как есть, 0.5 — вдвое ниже.': "Allunga il livello in altezza. 1 — così com'è, 0.5 — la metà.",
    'Насколько слой прозрачен: 0 — не видно совсем, 1 — плотно.': 'Quanto è trasparente il livello: 0 — invisibile, 1 — pieno.',
    'Что написать. В фигурных скобках подставляются показания: {cpu_load:.0f}% даст «37%».': 'Cosa scrivere. Tra parentesi graffe si inseriscono le letture: {cpu_load:.0f}% darà «37%».',
    'Готовые надписи: часы, дата, погода, загрузка. Выбери — и текст подставится сам.': 'Testi già pronti: orologio, data, meteo, carico. Scegline uno e il testo si compila da solo.',
    'Файл шрифта. Любой из системы или положенный рядом с темой.': 'File del font. Uno qualsiasi dal sistema, oppure messo accanto al tema.',
    'Высота букв в точках.': 'Altezza delle lettere in punti.',
    'Влезть в ширину': 'Adatta alla larghezza',
    'Влезть в столько точек по ширине. Длинная надпись сама уменьшится, короткая останется как есть. 0 — не ужимать, тогда длинное уедет за край.': 'Adatta a questa larghezza in punti. Un testo lungo si rimpicciolisce da solo, uno corto resta invariato. 0 — non restringere, e il testo lungo uscirà dal bordo.',
    'Цвет букв.': 'Colore delle lettere.',
    'За какую точку слой держится координатами. По центру — удобно для цифр, что меняют длину.': 'Il punto del livello a cui si riferiscono le coordinate. Al centro è comodo per i numeri che cambiano lunghezza.',
    'Цвет обводки. Помогает читать надпись поверх пёстрой картинки.': "Colore del contorno. Aiuta a leggere il testo sopra un'immagine variopinta.",
    'Толщина обводки букв в точках.': 'Spessore del contorno delle lettere in punti.',
    'Ширина слоя в точках.': 'Larghezza del livello in punti.',
    'Высота слоя в точках.': 'Altezza del livello in punti.',
    'Скругление углов. 0 — прямые углы.': 'Arrotondamento degli angoli. 0 — angoli retti.',
    'Основной цвет заливки.': 'Colore principale di riempimento.',
    'Второй цвет: заливка станет переходом от первого ко второму.': 'Secondo colore: il riempimento diventa un gradiente dal primo al secondo.',
    'В какую сторону идёт переход между двумя цветами.': 'In che direzione va il gradiente tra i due colori.',
    'Толщина линии или окантовки в точках.': 'Spessore della linea o del bordo in punti.',
    'Откуда берётся число: загрузка, температура, погода.': 'Da dove arriva il numero: carico, temperatura, meteo.',
    'Какому значению соответствует пустая полоса или дуга.': "A quale valore corrisponde la barra o l'arco vuoto.",
    'Какому значению соответствует полная полоса или дуга.': "A quale valore corrisponde la barra o l'arco pieno.",
    'В какую сторону растёт заполнение.': 'In che direzione cresce il riempimento.',
    'Цвет незаполненной части. Можно не задавать.': 'Colore della parte non riempita. Si può lasciare vuoto.',
    'Радиус в точках. Координаты — это центр, а не угол.': 'Raggio in punti. Le coordinate indicano il centro, non un angolo.',
    'Радиус впадин между лучами звезды.': 'Raggio degli avvallamenti tra le punte della stella.',
    'Сколько лучей у звезды.': 'Quante punte ha la stella.',
    'Повернуть звезду на столько градусов.': 'Ruota la stella di questi gradi.',
    'Толщина дуги в точках.': "Spessore dell'arco in punti.",
    'С какой стороны у кольца вырез.': "Da che parte è il taglio dell'anello.",
    'Ширина выреза в градусах. 60 — небольшой, 180 — половина круга.': 'Ampiezza del taglio in gradi. 60 è piccolo, 180 è mezzo cerchio.',
    'Заполнять дугу с другого конца, навстречу обычному.': "Riempie l'arco dall'altra estremità, in senso contrario al solito.",
    'Скруглить концы — дуга или линия смотрится мягче.': "Arrotonda le estremità — l'arco o la linea appaiono più morbidi.",
    'Размер наконечника стрелки в точках.': 'Dimensione della punta della freccia in punti.',
    'Файл картинки или папка с кадрами. Папка листается как ролик.': 'File immagine o cartella di fotogrammi. Una cartella scorre come un filmato.',
    'Что делать, если картинка не совпала с отведённым местом.': "Cosa fare se l'immagine non coincide con lo spazio assegnato.",
    'Своя частота листания кадров. Ставь ту, с которой резал ролик, иначе он поедет быстрее или медленнее задуманного.': 'Frequenza di scorrimento personalizzata. Imposta quella con cui è stato montato il filmato, altrimenti andrà più veloce o più lento del previsto.',
    'Включи, если PNG выгружены из DaVinci: там цвет уже умножен на прозрачность, и без этого по мягкому краю пойдёт тёмная каёмка.': 'Attiva se i PNG sono esportati da DaVinci: lì il colore è già moltiplicato per la trasparenza, e senza questa opzione i bordi morbidi avranno un alone scuro.',
    'Поднять непрозрачность, если объект вырезался полупрозрачным и выглядит блёклым. 1 — не трогать, 1.5 — заметно плотнее.': "Aumenta l'opacità se l'oggetto è stato ritagliato semitrasparente e appare sbiadito. 1 — lascia com'è, 1.5 — decisamente più pieno.",
    'Поворот, °': 'Rotazione, °',
    'Шире': 'Più largo',
    'Выше': 'Più alto',
    'Прозрачность': 'Trasparenza',
    'Второй цвет': 'Secondo colore',
    'Переход цвета': 'Gradiente colore',
    'Готовая надпись': 'Testo pronto',
    'Текст': 'Testo',
    'Шрифт': 'Font',
    'Размер': 'Dimensione',
    'Цвет': 'Colore',
    'Держится за': 'Ancorato a',
    'Обводка': 'Contorno',
    'Толщина обводки': 'Spessore contorno',
    'Ширина': 'Larghezza',
    'Высота': 'Altezza',
    'Скругление': 'Arrotondamento',
    'Заливка': 'Riempimento',
    'Окантовка': 'Bordo',
    'Толщина': 'Spessore',
    'Наконечник': 'Punta freccia',
    'Мягкие концы': 'Estremità morbide',
    'X конца': 'X finale',
    'Y конца': 'Y finale',
    'Радиус': 'Raggio',
    'Радиус впадин': 'Raggio avvallamenti',
    'Лучей': 'Punte',
    'Наклон, °': 'Inclinazione, °',
    'Показание': 'Lettura',
    'Пусто при': 'Vuoto a',
    'Полно при': 'Pieno a',
    'Направление': 'Direzione',
    'Цвет заполнения': 'Colore riempimento',
    'Цвет пустоты': 'Colore vuoto',
    'Толщина дуги': 'Spessore arco',
    'Вырез': 'Taglio',
    'Вырез, °': 'Taglio, °',
    'Наоборот': 'Al contrario',
    'Картинка': 'Immagine',
    'Как вписать': 'Come adattare',
    'PNG из DaVinci': 'PNG da DaVinci',
    'Плотнее': 'Più pieno',
    'Что показывает': 'Cosa mostra',
    'Где и какого размера': 'Dove e quanto grande',
    'Как выглядит': 'Come appare',
    'Прочее': 'Altro',
    'новый текст': 'nuovo testo',
    'новый прямоугольник': 'nuovo rettangolo',
    'новый квадрат': 'nuovo quadrato',
    'новый овал': 'nuovo ovale',
    'новый круг': 'nuovo cerchio',
    'новая линия': 'nuova linea',
    'новая стрелка': 'nuova freccia',
    'новая звезда': 'nuova stella',
    'новая полоса': 'nuova barra',
    'новое кольцо': 'nuovo anello',
    'новая картинка': 'nuova immagine',
    'слой': 'livello',
    'блок': 'blocco',
    ' копия': ' copia',
    '←  К темам': '←  Ai temi',
    'Сохранить как…': 'Salva come…',
    'Вернуть с диска': 'Ricarica dal disco',
    'Открыть тему…': 'Apri un tema…',
    'Описание темы…': 'Dettagli del tema…',
    '●  Магнит': '●  Magnete',
    '○  Магнит': '○  Magnete',
    '●  Сетка {}': '●  Griglia {}',
    '○  Сетка': '○  Griglia',
    'Выровнять:': 'Allinea:',
    'К левому краю экрана': 'Al bordo sinistro dello schermo',
    'По центру экрана вбок': 'Al centro orizzontale dello schermo',
    'К правому краю экрана': 'Al bordo destro dello schermo',
    'К верхнему краю экрана': 'Al bordo superiore dello schermo',
    'По центру экрана вниз': 'Al centro verticale dello schermo',
    'К нижнему краю экрана': 'Al bordo inferiore dello schermo',
    'Размер:': 'Dimensione:',
    'Уменьшить выбранные слои на десятую часть': 'Rimpicciolisce i livelli scelti di un decimo',
    'Увеличить выбранные слои на десятую часть': 'Ingrandisce i livelli scelti di un decimo',
    '. Работает и на нескольких сразу: выдели их в списке с Ctrl или Shift.': ". Funziona anche su più livelli insieme: selezionali nell'elenco con Ctrl o Shift.",
    'Показать на экране': 'Mostra sullo schermo',
    'Остановить показ': 'Interrompi la visualizzazione',
    'Слои · нижние перекрываются верхними': 'Livelli · quelli sotto sono coperti da quelli sopra',
    'все': 'tutti',
    'день': 'giorno',
    'Скрыть': 'Nascondi',
    'Копия': 'Copia',
    'Удалить': 'Elimina',
    'Добавить:': 'Aggiungi:',
    'Режим правки:': 'Modalità di modifica:',
    'Ночной вид': 'Vista notte',
    'Переход': 'Transizione',
    'Дневной вид': 'Vista giorno',
    'Прокрутка перехода:': 'Scorri la transizione:',
    'Двигается только выбранный слой. Стрелки — на пиксель, Shift+стрелки — на десять.\nМагнит притягивает к краям и центрам соседей; Alt при перетаскивании временно его отключает.\nНесколько слоёв разом: Ctrl+щелчок или Shift+щелчок в списке.\nCtrl+Z отменить · Ctrl+Y вернуть · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S сохранить · Delete удалить': "Si muove solo il livello selezionato. Le frecce spostano di un pixel, Shift+frecce di dieci.\nIl magnete attira verso i bordi e i centri dei vicini; Alt durante il trascinamento lo disattiva temporaneamente.\nPiù livelli insieme: Ctrl+clic o Shift+clic nell'elenco.\nCtrl+Z annulla · Ctrl+Y ripeti · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S salva · Delete elimina",
    'Тип блока': 'Tipo di blocco',
    'Экран': 'Schermo',
    'Фон под всеми блоками:': 'Sfondo sotto tutti i blocchi:',
    'Убрать дневной': 'Rimuovi giorno',
    'нет дневного — фон ночной круглые сутки': 'senza sfondo giorno — resta il notturno h24',
    'Сжимать кадры фона': 'Comprimi i fotogrammi di sfondo',
    'памяти вчетверо меньше, картинка та же': 'un quarto della memoria, stessa immagine',
    'кадры фона будут сжаты — готовлю заново': 'i fotogrammi di sfondo saranno compressi — li preparo di nuovo',
    'кадры фона будут распакованы — готовлю заново': 'i fotogrammi di sfondo saranno decompressi — li preparo di nuovo',
    'Здесь настраивается только движение.\nЧто именно меняется — задаётся\nв ночном и дневном видах.': 'Qui si imposta solo il movimento.\nCosa cambia esattamente si definisce\nnelle viste notte e giorno.',
    'Правки уходят в дневной вид': 'Le modifiche vanno nella vista giorno',
    'Сбросить': 'Ripristina',
    'Переход к дневному виду': 'Transizione verso la vista giorno',
    'настроен': 'impostato',
    'не настроен': 'non impostato',
    'Что меняется:': 'Cosa cambia:',
    'Отрезок перехода, %': 'Tratto della transizione, %',
    'Начало': 'Inizio',
    'Середина': 'Centro',
    'Окончание': 'Fine',
    'Повтор по времени': 'Ripeti nel tempo',
    'Период, секунд': 'Periodo, secondi',
    'Как повторять': 'Come ripetere',
    'Показать в момент': 'Mostra al momento',
    'сброс': 'ripristino',
    'Реакция на датчик': 'Reazione a una lettura',
    'Датчик': 'Lettura',
    'Начинает меняться при': 'Inizia a cambiare a',
    'Полностью при': 'Al massimo a',
    'Показать при значении': 'Mostra al valore',
    'отменять нечего': 'niente da annullare',
    'отменено': 'annullato',
    'возвращать нечего': 'niente da ripetere',
    'возвращено': 'ripetuto',
    'слой скопирован': 'livello copiato',
    'слой вырезан': 'livello tagliato',
    'в буфере нет слоя': "non c'è nessun livello negli appunti",
    'слой вставлен': 'livello incollato',
    'магнит включён': 'magnete attivo',
    'магнит выключен': 'magnete disattivato',
    'сетка выключена': 'griglia disattivata',
    'сетка по {} точек': 'griglia ogni {} punti',
    'размер {:+.0f} % у {} слоёв': 'dimensione {:+.0f} % su {} livelli',
    'показано {} из {}': 'mostrati {} di {}',
    'X {}  Y {}   (без магнита)': 'X {}  Y {}   (senza magnete)',
    'X {}  Y {}{}': 'X {}  Y {}{}',
    '   ({} слоёв)': '   ({} livelli)',
    'шрифт скопирован в папку fonts': 'font copiato nella cartella fonts',
    'не смог скопировать: {}': 'impossibile copiarlo: {}',
    'переименовано, папка тоже': 'rinominato, anche la cartella',
    'папку переименовать не вышло: {}': 'non è stato possibile rinominare la cartella: {}',
    'описание изменено, не забудь сохранить': 'descrizione modificata, ricordati di salvare',
    'дневной вид блока сброшен': 'vista giorno del blocco ripristinata',
    'ошибка: {}': 'errore: {}',
    'сохранено': 'salvato',
    'открыто: ': 'aperto: ',
    'экран не найден': 'schermo non trovato',
    'показ прерван: {}': 'visualizzazione interrotta: {}',
    '{} · редактор · {} — {}': '{} · editor · {} — {}',
    'Удалить слой «{}»?': 'Eliminare il livello «{}»?',
    'Удалить выбранные слои ({} шт.)?': 'Eliminare i livelli scelti ({})?',
    'Выбери файл шрифта': 'Scegli un file font',
    'Шрифты': 'Font',
    'Папка с кадрами (Отмена - выбрать файл)': 'Cartella di fotogrammi (Annulla per scegliere un file)',
    'Открыть': 'Apri',
    'Вернуть': 'Ricarica',
    'Папка с темой (Отмена — выбрать файл)': 'Cartella del tema (Annulla per scegliere un file)',
    'В папке нет файлов описания темы (.json).\n\nФайл темы должен лежать рядом с папками кадров.': 'Nella cartella non ci sono file di descrizione del tema (.json).\n\nIl file del tema deve trovarsi accanto alle cartelle dei fotogrammi.',
    'Какой файл темы открыть': 'Quale file del tema aprire',
    'Файл темы': 'File del tema',
    'Описание панели': 'File del pannello',
    'Не удалось прочитать файл:\n{}': 'Impossibile leggere il file:\n{}',
    'Это не похоже на тему: нет раздела layers.': 'Non sembra un tema: manca la sezione layers.',
    'Тема ссылается на то, чего нет рядом с её файлом:\n\n  ': 'Il tema fa riferimento a elementi che non sono accanto al suo file:\n\n  ',
    '\n\nПеренеси эти папки в {}': '\n\nSposta queste cartelle in {}',
    'Не найден файл описания: {}': 'File di descrizione non trovato: {}',
    'осмотр машины': 'controllo del PC',
    '[д/н] ': '[s/n] ',
    'прервано': 'interrotto',
    'язык уже выбран': 'la lingua è già impostata',
    'язык Windows подсказывал другой: {}': "la lingua di Windows suggeriva un'altra: {}",
    'язык выбран по языку Windows': 'la lingua è presa da Windows',
    'поменять можно в Настройках -> Оформление программы': 'si può cambiare in Impostazioni -> Aspetto del programma',
    'Библиотеки': 'Librerie',
    'сборка кадров и всё рисование': 'composizione dei fotogrammi e tutto il disegno',
    'загрузка процессора, память, диски, сеть': 'carico processore, memoria, dischi, rete',
    'разговор с экраном по COM-порту': 'comunicazione con lo schermo via porta COM',
    'само окно программы': 'la finestra del programma stessa',
    'температура процессора, видеокарты AMD и Intel': 'temperatura di processore, schede video AMD e Intel',
    'переходы цвета и мягкие края': 'gradienti di colore e bordi morbidi',
    'значок рядом с часами': "l'icona accanto all'orologio",
    'переустанови Python, отметив «tcl/tk and IDLE»': 'reinstalla Python spuntando «tcl/tk and IDLE»',
    'Поставить всё разом:': 'Installa tutto insieme:',
    'Без обязательных библиотек осматривать дальше нечего.': "Senza le librerie obbligatorie non c'è altro da controllare.",
    'Права': 'Permessi',
    'права администратора есть': 'i permessi di amministratore ci sono',
    'прав администратора нет': 'non ci sono i permessi di amministratore',
    'без них температуры процессора не будет вовсе': 'senza di essi la temperatura del processore non ci sarà affatto',
    'запусти start.bat, а программу - через app.bat': 'avvia start.bat, e il programma tramite app.bat',
    'Библиотека датчиков': 'La libreria dei sensori',
    'нет рядом с программой': 'non è accanto al programma',
    'возьми из архива LibreHardwareMonitor и положи сюда': "prendila dall'archivio LibreHardwareMonitor e mettila qui",
    'все четыре файла на месте': 'tutti e quattro i file sono al loro posto',
    'снял пометку «из интернета»': 'rimosso il contrassegno «da internet»',
    'помечен как скачанный из интернета': 'contrassegnato come scaricato da internet',
    'Свойства файла -> галочка «Разблокировать»': 'Proprietà del file -> la casella «Sblocca»',
    'пометки «из интернета» ни на одном нет': 'nessuno di essi ha il contrassegno «da internet»',
    'Железо': 'Hardware',
    'процессор': 'processore',
    'видеокарта': 'scheda video',
    'название выяснить не удалось': 'non è stato possibile scoprire il nome',
    'ядер {}, потоков {}': 'core {}, thread {}',
    'оперативной памяти {:.0f} ГБ': '{:.0f} GB di memoria',
    'системный диск {}': 'disco di sistema {}',
    'опрашиваю железо, это занимает несколько секунд…': "interrogo l'hardware, richiede qualche secondo…",
    'загрузка процессора': 'carico del processore',
    'температура процессора': 'temperatura del processore',
    'частота процессора': 'frequenza del processore',
    'загрузка памяти': 'carico della memoria',
    'загрузка диска': 'carico del disco',
    'приём из сети': 'rete in entrata',
    'загрузка видеокарты': 'carico della scheda video',
    'температура видеокарты': 'temperatura della scheda video',
    'занято видеопамяти': 'memoria video usata',
    'потребление видеокарты': 'consumo della scheda video',
    'не читается': 'non leggibile',
    'температура читается': 'la temperatura è leggibile',
    'выбран датчик: ': 'sensore scelto: ',
    'источник открылся, но отдаёт нули': 'la fonte si è aperta ma restituisce zero',
    'библиотека отдаёт нули по всем ядрам: нет прав администратора': 'la libreria restituisce zero su tutti i core: mancano i permessi di amministratore',
    'так бывает без прав администратора: запусти start.bat': 'succede senza i permessi di amministratore: avvia start.bat',
    'источник не найден': 'nessuna fonte trovata',
    'запусти программу через app.bat': 'avvia il programma tramite app.bat',
    'нужны права администратора и четыре .dll рядом': 'servono i permessi di amministratore e i quattro file .dll accanto',
    'видеокарта читается': 'la scheda video è leggibile',
    'нет источника показаний': "non c'è nessuna fonte di letture",
    'положи System.Numerics.Vectors.dll рядом с программой': 'metti System.Numerics.Vectors.dll accanto al programma',
    'нужен для видеокарт не Nvidia — на месте': 'serve per le schede video non Nvidia — presente',
    'нужен, чтобы читать видеокарту не Nvidia': 'serve per leggere una scheda video non Nvidia',
    'особых прав не нужно': 'non servono permessi speciali',
    'температуры читает ядро, оно их и так отдаёт': 'le temperature le legge il kernel, che le fornisce comunque',
    'температуры читает ядро, библиотека датчиков не нужна': 'le temperature le legge il kernel, la libreria dei sensori non serve',
    'ядро Linux': 'il kernel Linux',
    'ядро Linux (drm)': 'il kernel Linux (drm)',
    'ядро не отдаёт температур: нет /sys/class/hwmon': 'il kernel non fornisce temperature: manca /sys/class/hwmon',
    'ядро не отдаёт показаний видеокарты: нет /sys/class/drm': 'il kernel non fornisce letture della scheda video: manca /sys/class/drm',
    'ядро не выложило /sys/class/hwmon: посмотри, загружен ли модуль датчиков процессора': 'il kernel non ha esposto /sys/class/hwmon: verifica se il modulo dei sensori del processore è caricato',
    'для Nvidia нужен nvidia-smi, для AMD - драйвер amdgpu в /sys/class/drm': 'per Nvidia serve nvidia-smi, per AMD il driver amdgpu in /sys/class/drm',
    'библиотеке не хватает файла System.Numerics.Vectors.dll — без него показаний видеокарты не будет. Возьми его из архива LibreHardwareMonitor': "alla libreria manca il file System.Numerics.Vectors.dll — senza di esso non ci saranno letture della scheda video. Prendilo dall'archivio LibreHardwareMonitor",
    'для Nvidia хватит драйвера, для AMD и Intel нужна библиотека датчиков и права': 'per Nvidia basta il driver, per AMD e Intel servono la libreria dei sensori e i permessi',
    'psutil (процессор, память, диски, сеть): ': 'psutil (processore, memoria, dischi, rete): ',
    'есть': 'presente',
    'НЕ УСТАНОВЛЕН': 'NON INSTALLATO',
    'процессор: ': 'processore: ',
    'видеокарта: ': 'scheda video: ',
    'показания видеокарты: ': 'letture scheda video: ',
    'показания видеокарты: НЕТ — ': 'letture scheda video: NESSUNA — ',
    'показания видеокарты: НЕТ — нет ни nvidia-smi, ни LibreHardwareMonitorLib.dll': "letture scheda video: NESSUNA — non c'è né nvidia-smi né LibreHardwareMonitorLib.dll",
    'температура процессора: читается ({})': 'temperatura processore: leggibile ({})',
    'библиотека напрямую': 'la libreria direttamente',
    'через WMI': 'tramite WMI',
    'способ не указан': 'il metodo non è indicato',
    ', вспомогательных сборок: {}': ', assembly ausiliari: {}',
    '  выбран датчик: ': '  sensore scelto: ',
    '  все найденные датчики процессора:': '  tutti i sensori del processore trovati:',
    'температура процессора: НЕТ — ': 'temperatura processore: NESSUNA — ',
    '  ВНИМАНИЕ: программа запущена без прав администратора.': '  ATTENZIONE: il programma è avviato senza permessi di amministratore.',
    '  Температуру процессора без них прочитать невозможно в принципе:': '  Senza di essi è impossibile in linea di principio leggere la temperatura del processore:',
    '  Windows не даёт доступ к регистрам процессора обычным программам.': "  Windows non concede ai programmi comuni l'accesso ai registri del processore.",
    '  Права администратора есть. Положи рядом LibreHardwareMonitorLib.dll': '  I permessi di amministratore ci sono. Metti accanto LibreHardwareMonitorLib.dll',
    '  и HidSharp.dll, либо запусти саму LibreHardwareMonitor в фоне.': '  e HidSharp.dll, oppure avvia LibreHardwareMonitor stesso in background.',
    'рядом нет LibreHardwareMonitorLib.dll (положи её в папку с программой)': 'LibreHardwareMonitorLib.dll non è accanto (mettila nella cartella del programma)',
    'библиотека есть, но нет pythonnet. Выполни: pip install pythonnet': "la libreria c'è, ma manca pythonnet. Esegui: pip install pythonnet",
    'библиотека заблокирована Windows как скачанная из интернета. Свойства файла -> галочка «Разблокировать»': 'Windows ha bloccato la libreria come scaricata da internet. Proprietà del file -> la casella «Sblocca»',
    'погода: получена{}{}': 'meteo: ricevuto{}{}',
    ' от ': ' da ',
    ' для ': ' per ',
    '  восход и закат: ': '  alba e tramonto: ',
    'погода: НЕТ — ': 'meteo: NESSUNO — ',
    'ещё не загружена': 'non ancora caricata',
    'не выбрано место — укажи город в настройках, раздел «Погода»': 'nessun luogo scelto — indica la città nelle impostazioni, sezione «Meteo»',
    'не смог заглянуть в порты': 'non è stato possibile controllare le porte',
    'экран найден': 'schermo trovato',
    'ни на одном COM-порту': 'su nessuna porta COM',
    'проверь кабель от помпы к разъёму USB на плате': 'controlla il cavo dalla pompa al connettore USB sulla scheda',
    'а вот что на портах есть:': "ma ecco cosa c'è sulle porte:",
    'COM-портов не найдено вообще': 'non è stata trovata nessuna porta COM',
    'погода выключена в настройках': 'il meteo è disattivato nelle impostazioni',
    'прогноз получен': 'previsioni ricevute',
    'восход {}   закат {}   ({})': 'alba {}   tramonto {}   ({})',
    'свой расчёт': 'calcolo interno',
    'прогноза нет': 'nessuna previsione',
    'источник не ответил': 'la fonte non ha risposto',
    'проверь интернет и место в Настройках -> Погода и адрес': 'controlla internet e il luogo in Impostazioni -> Meteo e indirizzo',
    'не смог просмотреть темы': 'non è stato possibile scorrere i temi',
    'названия железа нигде не вписаны руками': 'nessun nome hardware è scritto a mano da nessuna parte',
    '«{}»: {} слоёв с вписанным названием': '«{}»: {} livelli con un nome scritto a mano',
    'Заменить, чтобы тема сама называла ваше железо?': 'Sostituirli, così il tema chiamerà da solo il tuo hardware?',
    'оставил как было': 'lasciato invariato',
    'тема поправлена': 'tema corretto',
    'не смог записать тему': 'non è stato possibile scrivere il tema',
    'Записываю в настройки': 'Scrivo nelle impostazioni',
    'железо записано': 'hardware registrato',
    'опрос nvidia-smi': 'interrogazione di nvidia-smi',
    'включён': 'attivo',
    'выключен, он тут не нужен': 'disattivato, qui non serve',
    'Температуру прочитать нечем. Выключить её опрос?': "Non c'è modo di leggere la temperatura. Disattivare la sua interrogazione?",
    'опрос температур выключен': 'interrogazione delle temperature disattivata',
    'Итог': 'In sintesi',
    'Всё на месте. Запускай app.bat.': 'Tutto è a posto. Avvia app.bat.',
    'Без этого программа будет работать не полностью:': 'Senza questo il programma non funzionerà del tutto:',
    'Мелочи, жить можно:': 'Dettagli minori, si può convivere:',
    'Когда поправишь - запусти start.bat ещё раз.': 'Quando avrai sistemato, avvia di nuovo start.bat.',
}

POGODA = {
    0: ("Sereno", "Sereno"),
    1: ("Sereno", "Prevalentemente sereno"),
    2: ("Nuvole", "Parzialmente nuvoloso"),
    3: ("Coperto", "Coperto"),
    45: ("Nebbia", "Nebbia"),
    48: ("Nebbia", "Nebbia gelata"),
    51: ("Pioviggine", "Pioviggine debole"),
    53: ("Pioviggine", "Pioviggine"),
    55: ("Pioviggine", "Pioviggine forte"),
    56: ("Gelo", "Pioviggine gelata"),
    57: ("Gelo", "Pioviggine gelata forte"),
    61: ("Pioggia", "Pioggia debole"),
    63: ("Pioggia", "Pioggia"),
    65: ("Pioggia", "Pioggia forte"),
    66: ("Gelo", "Pioggia gelata"),
    67: ("Gelo", "Pioggia gelata forte"),
    71: ("Neve", "Neve debole"),
    73: ("Neve", "Neve"),
    75: ("Neve", "Neve forte"),
    77: ("Neve", "Granuli di neve"),
    80: ("Rovesci", "Rovesci deboli"),
    81: ("Rovesci", "Rovesci"),
    82: ("Rovesci", "Rovesci forti"),
    85: ("Neve", "Rovesci di neve"),
    86: ("Neve", "Rovesci di neve forti"),
    95: ("Temporale", "Temporale"),
    96: ("Temporale", "Temporale con grandine"),
    99: ("Temporale", "Temporale forte con grandine"),
}

SOKRASHENO = {
    1: "Preval. sereno",
    2: "Parz. nuvoloso",
    57: "Pioviggine gel. forte",
    67: "Pioggia gel. forte",
    96: "Temporale c/ grandine",
    99: "Temporale forte c/ grand.",
}
