#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  Французский: слова программы и слова погоды.
#  Часть проекта EOne screen.
#
#  Автор: EOne
#  Лицензия: CC BY-NC-SA 4.0 — использование в коммерческих целях
#  запрещено без письменного разрешения автора. См. файл LICENSE.
#
"""yazyk_fr.py - французский. Устройство описано в yazyk_es.py.

ПЕРЕВОД СДЕЛАН С ПОМОЩЬЮ ИИ и носителем языка не проверялся. Русский
и английский написаны автором, остальные пять - нет. Если вы говорите
на этом языке и видите ошибку или корявость, поправьте: строку можно
менять прямо здесь, а ключ трогать нельзя.

"""

SLOVAR = {
    # Готовые надписи, которые всегда по-английски:
    # они просят {weather_en}, а не {weather}.
    "Weather short  Rain": "Météo courte, toujours en anglais  Rain",
    "Weather full  Light rain": "Météo détaillée, toujours en anglais  Light rain",
    "Weather and temperature  Rain  12 °C": "Météo et température, toujours en anglais  Rain  12 °C",
    "Weather full and temperature": "Météo détaillée et température, toujours en anglais",
    "Weather: feels like  10 °C": "Météo : ressenti, toujours en anglais  10 °C",
    "Weather: wind  4 km/h": "Météo : vent, toujours en anglais  4 km/h",
    "Weather: humidity  78 %": "Météo : humidité, toujours en anglais  78 %",
    "Weather: everything": "Météo : tout ensemble, toujours en anglais",
    # Значения движка: подпись видит человек, а в тему уходит
    # русское слово - его подставляет сама программа.
    "плавно": "doux",
    "средне": "moyen",
    "резко": "net",

    'Главная': 'Accueil',
    'Темы': 'Thèmes',
    'Настройки': 'Réglages',
    'экран водянки': 'écran de la watercooling',
    'экран выключен': 'écran éteint',
    'экран: {} · {:.0f} кадр/с': 'écran : {} · {:.0f} im/s',
    'переход {:.0f} с': 'transition {:.0f} s',
    'тема отправлена на экран': "thème envoyé à l'écran",
    'перезапускаю экран…': "redémarrage de l'écran…",
    'сбой обновления: {}': 'échec de la mise à jour : {}',
    '{} — экран выключен': '{} — écran éteint',
    '{} — {} ({:.1f} кадр/с, {})': '{} — {} ({:.1f} im/s, {})',
    'Включить или выключить экран': "Allumer ou éteindre l'écran",
    'Показать окно': 'Afficher la fenêtre',
    'Выход': 'Quitter',
    'Пауза': 'Pause',
    'Продолжить': 'Reprendre',
    'Перечитать тему': 'Recharger le thème',
    '{} · {} — {} ({:.1f} кадр/с, тема {})': '{} · {} — {} ({:.1f} im/s, thème {})',
    'по солнцу': 'selon le soleil',
    'как в Windows': 'comme Windows',
    'всегда ночная': 'toujours nuit',
    'всегда дневная': 'toujours jour',
    'запускается': 'démarrage',
    'остановлена': 'arrêtée',
    'на паузе': 'en pause',
    'слишком много сбоев': "trop d'échecs",
    'Сохранить правки?': 'Enregistrer les modifications ?',
    'Несохранённые правки пропадут. Продолжить?': 'Les modifications non enregistrées seront perdues. Continuer ?',
    'Это не похоже на тему: нет слоёв.': 'Cela ne ressemble pas à un thème : aucun calque.',
    'Моя тема': 'Mon thème',
    'Сейчас на экране': "En ce moment à l'écran",
    'Что показывать': 'Quoi afficher',
    'Погода на экране': "Météo à l'écran",
    'Включить экран': "Allumer l'écran",
    'Выключить экран': "Éteindre l'écran",
    'Перезапустить': 'Redémarrer',
    'выключен': 'éteint',
    'работает': 'en marche',
    'работает · {:.0f} кадр/с': 'en marche · {:.0f} im/s',
    '(прогноз не пришёл)': '(prévisions non reçues)',
    'готовлю кадры фона': 'préparation des images de fond',
    'тема: ': 'thème : ',
    'погода': 'météo',
    'днём': 'le jour',
    'ночью': 'la nuit',
    'восход {}   закат {}   сейчас {:.0f} % дня': 'lever {}   coucher {}   actuellement {:.0f} % du jour',
    '   (прогноз не пришёл)': '   (prévisions non reçues)',
    'отправлено кадров {}': 'images envoyées {}',
    'сбоев {}': 'erreurs {}',
    '{:g} кадр/с': '{:g} im/s',
    'не удалось собрать кадр: {}': "impossible de construire l'image : {}",
    'кадры фона не листаются, чтобы окно не тратило лишнего': 'les images de fond ne défilent pas ici, pour alléger la fenêtre',
    'Начать или прекратить вывод картинки на экран водянки.': "Démarrer ou arrêter l'envoi de l'image vers l'écran de la watercooling.",
    'Придержать вывод, не закрывая порт. Экран замрёт на последнем кадре.': "Suspendre l'envoi sans fermer le port. L'écran se fige sur la dernière image.",
    'Заново открыть порт и поздороваться с экраном. Выручает, если картинка сбилась или порт подвис.': "Rouvrir le port et se reconnecter à l'écran. Utile si l'image est décalée ou si le port se bloque.",
    'Яркость подсветки экрана водянки. Уходит на экран, когда отпустишь ползунок.': "Luminosité du rétroéclairage de l'écran de la watercooling. Appliquée quand vous relâchez le curseur.",
    'По солнцу': 'Selon le soleil',
    'Как в Windows': 'Comme Windows',
    'Ночь': 'Nuit',
    'День': 'Jour',
    'Светлеет на рассвете и темнеет на закате, по времени восхода и заката в твоём городе.': "S'éclaircit à l'aube et s'assombrit au crépuscule, selon le lever et le coucher du soleil de votre ville.",
    'Следит за оформлением Windows: светлая тема — дневной вид, тёмная — ночной.': 'Suit le thème de Windows : clair donne la vue de jour, sombre donne la vue de nuit.',
    'Всегда ночной вид, независимо от времени.': "Toujours la vue de nuit, quelle que soit l'heure.",
    'Всегда дневной вид, независимо от времени.': "Toujours la vue de jour, quelle que soit l'heure.",
    'По прогнозу': 'Selon les prévisions',
    'Ясно': 'Dégagé',
    'Пасмурно': 'Couvert',
    'Дождь': 'Pluie',
    'Гроза': 'Orage',
    'Снег': 'Neige',
    'Метель': 'Tempête de neige',
    'Туман': 'Brouillard',
    'Мороз': 'Gel',
    'Жара': 'Canicule',
    'Показывать настоящий прогноз.': 'Afficher les prévisions réelles.',
    'Показать «{}» так, будто оно за окном: {:+.0f} {}, ветер {:.0f} {}. Прогноз никуда не девается.': "Afficher « {} » comme si c'était dehors : {:+.0f} {}, vent {:.0f} {}. Les prévisions restent en place.",
    'Показывать дождь, снег, туман и грозу на дневной теме.': 'Afficher pluie, neige, brouillard et orages sur le thème de jour.',
    'То же на ночной. Звёзды и метеоры останутся в любом случае.': 'Pareil pour la nuit. Étoiles et météores restent dans tous les cas.',
    '{}: {}, {:.0f} {}, ветер {:.0f} {}   ·   небо — {}': '{} : {}, {:.0f} {}, vent {:.0f} {}   ·   ciel — {}',
    'км/ч': 'km/h',
    'м/с': 'm/s',
    'миль/ч': 'mi/h',
    'выдумано': 'inventé',
    'за окном': 'dehors',
    'нет данных': 'aucune donnée',
    'ничего': 'rien',
    'ясно': 'dégagé',
    'облака': 'nuages',
    'серость': 'grisaille',
    'дождь': 'pluie',
    'снег': 'neige',
    'гроза': 'orage',
    'туман': 'brouillard',
    'Мои темы': 'Mes thèmes',
    'Создать тему': 'Nouveau thème',
    'Редактор': 'Éditeur',
    'Всё, что лежит рядом с программой. Отсюда тему отправляют на экран, правят, копируют и упаковывают для пересылки.': "Tout ce qui se trouve à côté du programme. C'est ici qu'un thème part vers l'écran, se modifie, se copie et s'empaquette pour l'envoyer.",
    'Обновить': 'Actualiser',
    'Из папки…': 'Depuis un dossier…',
    'Из архива…': 'Depuis une archive…',
    'На экран': "Vers l'écran",
    'Изменить': 'Modifier',
    'Открыть в редакторе': "Ouvrir dans l'éditeur",
    'Переименовать': 'Renommer',
    'открыта': 'ouverte',
    'нет предпросмотра': 'aucun aperçu',
    '{} слоёв · {} · {:g} кадр/с': '{} calques · {} · {:g} im/s',
    'автор: {}   ·   {}': 'auteur : {}   ·   {}',
    'Сделать эту тему текущей: она уйдёт на экран водянки и откроется на главной.': "Faire de ce thème le thème actif : il part vers l'écran de la watercooling et s'ouvre sur l'accueil.",
    'Открыть тему в редакторе: слои, надписи, цвета, дневной и ночной вид.': "Ouvrir le thème dans l'éditeur : calques, textes, couleurs, vues de jour et de nuit.",
    'Сменить название темы. Папка на диске получит то же имя — тема и папка ходят вместе.': 'Changer le nom du thème. Le dossier sur le disque prend le même nom — thème et dossier vont toujours ensemble.',
    'Название, автор и пояснение к теме. Эти строки уедут вместе с ней к другому человеку. Название меняет и имя папки на диске.': 'Nom, auteur et description du thème. Ces informations partent avec lui vers une autre personne. Le nom change aussi celui du dossier sur le disque.',
    'Копия темы целиком, вместе с кадрами и шрифтами. Спросит имя. Оригинал не пострадает.': "Copie complète du thème, avec ses images et polices. Un nom sera demandé. L'original reste intact.",
    'Упаковать тему в один файл, чтобы переслать. Всё, на что она ссылается, попадёт внутрь.': "Empaqueter le thème dans un seul fichier à envoyer. Tout ce qu'il utilise y est inclus.",
    'Картинка для показа: ночь и день рядом, с именем, автором и списком умений. Чтобы выложить или прислать.': "Une image de présentation : nuit et jour côte à côte, avec le nom, l'auteur et ce que le thème sait faire. Pour la publier ou l'envoyer.",
    'Убрать тему из витрины. Папка остаётся на диске и переименовывается с точки — вернуть можно в проводнике.': "Retirer le thème de la vitrine. Le dossier reste sur le disque, renommé avec un point devant — on peut le restaurer dans l'explorateur.",
    'Новая тема': 'Nouveau thème',
    'Как её назвать?': "Comment l'appeler ?",
    'Переименовать тему': 'Renommer le thème',
    'Новое название:': 'Nouveau nom :',
    'Копия темы': 'Copie du thème',
    'Как назвать копию?': 'Comment appeler la copie ?',
    'Копирую тему': 'Copie du thème en cours',
    ' — копия': ' — copie',
    'Скопировать': 'Copier',
    'Создать': 'Créer',
    'Отмена': 'Annuler',
    'Сохранить': 'Enregistrer',
    'Упаковываю тему': 'Empaquetage du thème en cours',
    'Упаковать тему': 'Empaqueter le thème',
    'Куда упаковать тему': 'Où empaqueter le thème',
    'Архив с темой': 'Archive du thème',
    'Папка с темой': 'Dossier du thème',
    'В папке нет описания темы.': 'Le dossier ne contient aucune description de thème.',
    'Распаковываю тему': 'Décompression du thème en cours',
    'Открыть архив': "Ouvrir l'archive",
    'Тема добавлена. Открыть её?': "Le thème a été ajouté. L'ouvrir ?",
    'Картинка для показа': 'Image de présentation',
    'Убрать тему': 'Retirer le thème',
    'Эта тема сейчас открыта. Откройте другую и попробуйте снова.': 'Ce thème est actuellement ouvert. Ouvrez-en un autre et réessayez.',
    'Убрать «{}» из витрины?\n\nПапка останется на диске — она просто получит точку в начале имени. Вернуть можно переименованием в проводнике.': "Retirer « {} » de la vitrine ?\n\nLe dossier restera sur le disque — il recevra simplement un point au début de son nom. Vous pourrez le restaurer en le renommant dans l'explorateur.",
    'Готово, файлов внутри: {}.\n{}\n\nПоказать в папке?': "Terminé, fichiers à l'intérieur : {}.\n{}\n\nAfficher dans le dossier ?",
    'Готово:\n{}\n\nОткрыть копию?': 'Terminé :\n{}\n\nOuvrir la copie ?',
    'Готово:\n{}\n\nОткрыть её?': "Terminé :\n{}\n\nL'ouvrir ?",
    'Описание темы': 'Description du thème',
    'Что увидят другие': 'Ce que les autres verront',
    'эти строки уедут вместе с темой': 'ces informations partent avec le thème',
    'Название': 'Nom',
    'Автор': 'Auteur',
    'Описание': 'Description',
    '{} из {}   {}': '{} sur {}   {}',
    'имя не может быть пустым': 'le nom ne peut pas être vide',
    'в архиве нет описания темы': "l'archive ne contient aucune description de thème",
    'без названия': 'sans nom',
    'тема': 'thème',
    'День и ночь': 'Jour et nuit',
    'Картинки': 'Images',
    'Движение': 'Mouvement',
    'Погода': 'Météo',
    'Видео': 'Graphismes',
    'Процессор': 'Processeur',
    'Осмотр машины': 'Inspection de la machine',
    'что на этой машине есть, что отвечает и чего не хватает': 'ce que cette machine a, ce qui répond et ce qui manque',
    'Что на этой машине': 'Ce que cette machine a',
    'те же проверки, что делает start.bat перед первым запуском. Опрос датчиков занимает несколько секунд.': 'les mêmes vérifications que start.bat effectue avant le premier lancement. Interroger les capteurs prend quelques secondes.',
    'что на этой машине отвечает, а что молчит. Опрос датчиков занимает несколько секунд.': 'ce qui répond sur cette machine et ce qui reste muet. Interroger les capteurs prend quelques secondes.',
    'Осмотреть': 'Inspecter',
    '  смотрю…': '  inspection…',
    'Осмотр ещё не делался.': "Aucune inspection n'a encore été faite.",
    'всё в порядке': 'tout est en ordre',
    'важных замечаний: {}': 'remarques importantes : {}',
    'команда в буфере обмена': 'la commande est dans le presse-papiers',
    'не вышло': "ça n'a pas marché",
    'Оформление программы': 'Apparence du programme',
    'Единицы и время': 'Unités et heure',
    'Сборка кадра': "Construction de l'image",
    'это про машину, а не про тему: настройка остаётся при смене темы': "c'est un réglage lié à la machine, pas au thème : il reste en place quand vous changez de thème",
    'В один поток': 'Sur un thread',
    'В два потока': 'Sur deux threads',
    'В четыре': 'Sur quatre',
    'Пусть решит сама': 'Laisser le programme décider',
    'Кадр собирается кусками, и куски друг о друге не знают — их можно готовить разом. Картинка выходит та же до последней точки, проверено. Но выигрыш во времени невелик и на быстрой машине теряется в разбросе: если панель и так укладывается в отпущенное время, кадров в секунду не прибавится. Смысл — уложиться на слабой машине.': "L'image est construite par morceaux, et les morceaux s'ignorent entre eux — ils peuvent être préparés en même temps. Le résultat est rigoureusement identique, cela a été vérifié. Mais le gain de temps est faible et, sur une machine rapide, se perd dans les écarts de mesure : si le panneau tient déjà dans le temps imparti, il n'y aura pas plus d'images par seconde. L'intérêt est de tenir sur une machine faible.",
    'в чём показывать градусы, время и дату — и в окне, и на экране': "dans quelles unités afficher les degrés, l'heure et la date — dans la fenêtre comme à l'écran",
    'Градусы': 'Degrés',
    'Ветер': 'Vent',
    'и в окне, и в надписях на экране': "dans la fenêtre comme dans les textes à l'écran",
    'и температура железа, и погода': 'aussi bien la température du matériel que la météo',
    'Цельсий': 'Celsius',
    'Фаренгейт': 'Fahrenheit',
    'Часы': 'Horloge',
    'двенадцать часов дописывают AM и PM': 'le format 12 heures ajoute AM et PM',
    '24 часа': '24 heures',
    '12 часов': '12 heures',
    'Порядок чисел в дате': 'Ordre des chiffres dans la date',
    'день, месяц и год': 'jour, mois et année',
    'Неделя начинается': 'La semaine commence',
    'по этому дню тема считает номер дня': 'le thème calcule le numéro du jour à partir de celui-ci',
    'с понедельника': 'le lundi',
    'с воскресенья': 'le dimanche',
    'Как это будет выглядеть': 'À quoi ça ressemblera',
    'по умолчанию всё берётся из самой Windows: какие единицы и форматы там выбраны, такие и здесь': 'par défaut, tout vient de Windows lui-même : les unités et formats choisis là-bas sont repris ici',
    'Тема может брать готовые {time}, {date} и {deg} — они идут по этой настройке. А может писать свой вид через {now:…} — тогда настройка его не тронет.': "Le thème peut utiliser les valeurs toutes prêtes {time}, {date} et {deg} — elles suivent ce réglage. Ou bien il peut définir son propre format via {now:…} — dans ce cas, le réglage n'y touche pas.",
    'Запуск': 'Démarrage',
    'Датчики': 'Capteurs',
    'Погода и адрес': 'Météo et adresse',
    'Производительность': 'Performances',
    'О программе': 'À propos',
    'кто это написал и на каких условиях этим можно пользоваться': "qui a écrit ce programme et sous quelles conditions on peut l'utiliser",
    'как выглядит само окно программы, а не картинка на экране': "à quoi ressemble la fenêtre du programme elle-même, pas l'image à l'écran",
    'что делать при включении компьютера и при закрытии окна': "que faire au démarrage de l'ordinateur et à la fermeture de la fenêtre",
    'откуда берутся значения и что из этого читается сейчас': "d'où viennent les valeurs et ce qui est lu actuellement",
    'чем платим за плавность: памятью, процессором, качеством': 'ce que coûte la fluidité : mémoire, processeur, qualité',
    'откуда брать прогноз, восход и закат': "d'où viennent les prévisions, le lever et le coucher du soleil",
    'Светлое или тёмное': 'Clair ou sombre',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за темой панели.': "« Comme Windows » suit le thème du système, « Comme l'écran » suit le thème du panneau.",
    'Как на экране': "Comme l'écran",
    'Светлое': 'Clair',
    'Тёмное': 'Sombre',
    'Язык': 'Langue',
    'Смена языка': 'Changement de langue',
    'В теме есть несохранённые правки. Сохранить их?': 'Le thème a des modifications non enregistrées. Les enregistrer ?',
    'Изменения применятся при следующем запуске.': 'Les modifications prendront effet au prochain démarrage.',
    'Ярлык на рабочем столе': 'Un raccourci sur le bureau',
    'чтобы запускать не из папки, а с рабочего стола': 'pour lancer le programme depuis le bureau plutôt que le dossier',
    'Не получилось. Рабочий стол может быть закрыт для записи.': 'Échec. Le bureau est peut-être protégé en écriture.',
    'Запускать вместе с Windows': 'Démarrer avec Windows',
    'через app.bat, чтобы поднялись права на температуру': 'via app.bat, pour obtenir les droits nécessaires à la température',
    'Язык темы': 'Langue du thème',
    'Как в окне': 'Comme la fenêtre',
    'на нём говорит панель на экране водянки: погода, подпись ветра, названия слоёв в редакторе': "c'est la langue du panneau sur l'écran de la watercooling : météo, unité du vent, noms des calques dans l'éditeur",
    'Запускать при входе в систему': "Démarrer à l'ouverture de session",
    'записью .desktop в автозапуске': 'via un fichier .desktop dans le démarrage automatique',
    'Открывать сразу свёрнутым в трей': 'Démarrer réduit dans la barre système',
    'окно не мешает, панель работает': 'la fenêtre ne gêne pas, le panneau fonctionne',
    'Сразу включать экран': "Allumer l'écran tout de suite",
    'не нажимать кнопку каждый раз': "pas besoin d'appuyer sur le bouton à chaque fois",
    'Крестик прячет в трей, а не закрывает': 'La croix réduit dans la barre système au lieu de fermer',
    'иначе панель погаснет вместе с окном': "sinon le panneau s'éteint avec la fenêtre",
    'Автозапуск': 'Démarrage automatique',
    'Не удалось изменить запись в реестре.': "Impossible de modifier l'entrée du registre.",
    'Что опрашивать': 'Quoi interroger',
    'выключенный источник не опрашивается вообще — это и есть экономия': "une source désactivée n'est jamais interrogée — c'est là toute l'économie",
    'Что читается прямо сейчас': 'Ce qui est lu en ce moment',
    'значения как есть, до перевода в выбранные единицы: температуры здесь всегда в Цельсиях, на них настраивается реакция слоёв': "les valeurs brutes, avant conversion dans les unités choisies : les températures sont toujours en Celsius ici, c'est sur elles que se règle la réaction des calques",
    'Процессор, память, диски, сеть': 'Processeur, mémoire, disques, réseau',
    'почти бесплатно': 'presque gratuit',
    'Видеокарта': 'Carte graphique',
    'через nvidia-smi': 'via nvidia-smi',
    'Температуры': 'Températures',
    'нужны права администратора': 'droits administrateur requis',
    'их отдаёт само ядро': 'le noyau les fournit lui-même',
    'через nvidia-smi или /sys/class/drm': 'via nvidia-smi ou /sys/class/drm',
    'Погода, восход и закат': 'Météo, lever et coucher du soleil',
    'нужен интернет': 'internet requis',
    'Место': 'Lieu',
    'по нему берётся прогноз, а заодно время восхода и заката — от них панель светлеет и темнеет': "les prévisions en dépendent, ainsi que l'heure du lever et du coucher du soleil — c'est ce qui éclaircit et assombrit le panneau",
    'Название города на любом языке. Нажми «Найти» и выбери из списка.': "Le nom de la ville, dans n'importe quelle langue. Appuyez sur « Rechercher » et choisissez dans la liste.",
    'Найти': 'Rechercher',
    'По адресу в сети': 'Par adresse réseau',
    'Выбрать это место': 'Utiliser ce lieu',
    '  ищу…': '  recherche…',
    '  ничего не нашлось': '  rien trouvé',
    '  не вышло: {}': '  échec : {}',
    'место: {}': 'lieu : {}',
    'Сейчас: {}   ({:.3f}, {:.3f}) {}': 'Actuellement : {}   ({:.3f}, {:.3f}) {}',
    'Место не выбрано — прогноза не будет, а восход и закат возьмутся запасные: 07:00 и 20:00.': "Aucun lieu choisi — il n'y aura pas de prévisions, et le lever et le coucher du soleil prendront les valeurs par défaut : 07:00 et 20:00.",
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за тем, день сейчас на панели или ночь.': "« Comme Windows » suit le thème du système, « Comme l'écran » suit si le panneau est en jour ou en nuit.",
    'Сейчас: {}   ({:.3f}, {:.3f})\n{}': 'Actuellement : {}   ({:.3f}, {:.3f})\n{}',
    'ночь': 'nuit',
    'и день': 'et jour',
    'Проверить, как тема выглядит в дождь или метель, можно на главной — ряд справа от выбора дня и ночи.': "Pour voir à quoi ressemble un thème sous la pluie ou la neige, direction l'accueil — la rangée à droite du choix jour/nuit.",
    'Источник прогноза': 'Source des prévisions',
    'Без ключа и без регистрации': 'Sans clé ni inscription',
    'По ключу службы': 'Avec la clé du service',
    'свой источник': 'votre propre source',
    'Где что лежит в ответе': 'Où se trouve quoi dans la réponse',
    'В адресе можно писать {lat}, {lon} и {key} — программа подставит место и ключ. Нажмите «Спросить службу»: ответ разберётся на пути, и останется выбрать нужные из списков.': "Dans l'adresse, on peut écrire {lat}, {lon} et {key} — le programme y mettra le lieu et la clé. Cliquez sur « Interroger le service » : la réponse sera décomposée en chemins, il ne restera qu'à choisir les bons dans les listes.",
    'Спросить службу': 'Interroger le service',
    'Температура': 'Température',
    'Состояние погоды числом': 'État météo, en chiffre',
    'Ощущается как': 'Ressenti',
    'Влажность': 'Humidité',
    'Минимум за сутки': 'Minimum du jour',
    'Максимум за сутки': 'Maximum du jour',
    'Восход': 'Lever du soleil',
    'Закат': 'Coucher du soleil',
    'Ветер в': 'Vent en',
    'Восход записан как': 'Le lever est écrit comme',
    'iso — 2026-08-13T05:08, unix — число секунд, 12h — 05:08 AM, 24h — 05:08': 'iso — 2026-08-13T05:08, unix — un nombre de secondes, 12h — 05:08 AM, 24h — 05:08',
    'Числа состояния': "Codes d'état",
    'wmo — служба уже отдаёт коды по стандарту ВМО. Своя таблица чисел прописывается в weather.json, см. справочник.': 'wmo — le service fournit déjà les codes selon la norme OMM. Une table de correspondance personnalisée se définit dans weather.json, voir la référence.',
    'служба ответила, полей нашлось: {}. Выберите нужные из списков и нажмите «Проверить».': "le service a répondu, champs trouvés : {}. Choisissez ceux qu'il faut dans les listes et cliquez sur « Vérifier ».",
    'Впишите адрес службы.': "Indiquez l'adresse du service.",
    'по умолчанию Open-Meteo: без ключа и без регистрации. Другие службы отвечают по-своему, поэтому у каждой свой переходник — выберите нужную, и программа сама переведёт её ответ в понятный панели вид.': 'par défaut, Open-Meteo : sans clé ni inscription. Les autres services répondent chacun à leur façon, donc chacun a son propre adaptateur — choisissez le bon et le programme traduira lui-même sa réponse dans un format compris par le panneau.',
    'Ключ': 'Clé',
    'Ключ выдаёт сама служба при регистрации. Он хранится в weather.json рядом с программой.': "La clé est fournie par le service lors de l'inscription. Elle est conservée dans weather.json, à côté du programme.",
    'Адрес': 'Adresse',
    'Пусто — обычный адрес выбранной службы. Свой нужен для зеркала или своего сервера: полный адрес без вопросов и параметров, их программа допишет сама.': "Vide : l'adresse habituelle du service choisi. Une adresse personnalisée sert pour un miroir ou un serveur perso : l'adresse complète, sans point d'interrogation ni paramètres, que le programme ajoutera lui-même.",
    'Проверить': 'Vérifier',
    'Обычный': 'Standard',
    '  спрашиваю…': '  interrogation…',
    'Сначала выберите место — без него спрашивать не о чем.': "Choisissez d'abord un lieu — sans lui, il n'y a rien à demander.",
    '{} отвечает: {}, {:.0f} {}, ветер {:.0f} {}. Записано.': '{} répond : {}, {:.0f} {}, vent {:.0f} {}. Enregistré.',
    '\nВосхода и заката эта служба не даёт — считаем их сами по координатам.': '\nCe service ne fournit ni lever ni coucher du soleil — nous les calculons nous-mêmes à partir des coordonnées.',
    'Не отвечает или отвечает не тем: {}': "Ne répond pas, ou répond n'importe quoi : {}",
    'Картинка и нагрузка': 'Image et charge',
    'эти значения хранятся внутри темы': 'ces valeurs sont stockées dans le thème',
    'Кадров в секунду': 'Images par seconde',
    'ниже 0.5 нельзя: экран уснёт': "pas moins de 0,5 : l'écran s'endormirait",
    'Качество JPEG': 'Qualité JPEG',
    '1–100, влияет на размер кадра': "1 à 100, influe sur la taille de l'image",
    'Сглаживание': 'Anticrénelage',
    '2 или 3, больше — плавнее края': "2 ou 3, plus c'est élevé, plus les bords sont lisses",
    'Переход день/ночь, секунд': 'Transition jour/nuit, secondes',
    'сколько длится смена вида': 'durée du changement de vue',
    'Сжимать кадры фона в памяти': 'Compresser les images de fond en mémoire',
    'Сжатие без потерь: картинка та же до последнего бита, памяти уходит втрое меньше. Плата — около семи десятых миллисекунды на кадр. Переключение заставляет заново разобрать все кадры фона: на тяжёлой теме экран замрёт на несколько секунд.': "Compression sans perte : l'image reste identique au bit près, et la mémoire utilisée est divisée par trois. Le coût est d'environ sept dixièmes de milliseconde par image. Le changement de réglage force à retraiter toutes les images de fond : sur un thème lourd, l'écran se fige pendant quelques secondes.",
    '      сейчас программа занимает {:.0f} МБ': '      le programme occupe actuellement {:.0f} Mo',
    'Экран выключен': "L'écran est éteint",
    'Включите вывод на главной — здесь будет видно, сколько кадров получается на самом деле.': "Activez l'envoi depuis l'accueil — vous verrez ici combien d'images sont réellement obtenues.",
    'Задано {:g}, выходит {:.1f} кадр/с': 'Réglé sur {:g}, obtient {:.1f} im/s',
    'Только запустились, счёт ещё набирается.': 'Ça vient de démarrer, le compte se construit encore.',
    'Успевает.': 'Ça suit.',
    'Не успевает: {:.0f} %. Упирается либо в отрисовку — тогда помогут меньше сглаживание и меньше живых слоёв, — либо в канал до экрана: тогда снижайте качество JPEG, кадр станет легче.': "Ça ne suit pas : {:.0f} %. Le goulot est soit le dessin — réduisez alors l'anticrénelage et le nombre de calques animés —, soit le lien vers l'écran : baissez alors la qualité JPEG pour alléger l'image.",
    'версия {} · автор {}': 'version {} · par {}',
    'Открытая замена штатной программе для экрана водянки: контроллер TXW818, панель ST7701S, 960x480 по COM-порту.': "Une alternative libre au logiciel d'origine pour écran de watercooling : contrôleur TXW818, dalle ST7701S, 960x480 via port COM.",
    'Лицензия': 'Licence',
    'Пользоваться, копировать и переделывать — можно.': 'Utiliser, copier et modifier : autorisé.',
    'Зарабатывать на этом — нельзя.': 'En tirer un profit : interdit.',
    'Переделанное раздавать на тех же условиях и с указанием автора.': "Ce qui est modifié doit être partagé aux mêmes conditions, en citant l'auteur.",
    'Условия распространяются и на программу, и на темы, которые с ней идут. Про коммерческое использование договариваются с автором письменно.': "Ces conditions s'appliquent au programme comme aux thèmes qui l'accompagnent. Pour un usage commercial, un accord écrit avec l'auteur est nécessaire.",
    'Открыть файл лицензии': 'Ouvrir le fichier de licence',
    'Полный текст в сети': 'Texte complet en ligne',
    'Файла LICENSE нет рядом с программой.': "Le fichier LICENSE n'est pas à côté du programme.",
    '      Наш файл — пересказ для человека. Юридическую силу имеет полный текст на сайте Creative Commons.': "      Notre fichier n'est qu'un résumé en langage clair. Seul le texte complet sur le site de Creative Commons a valeur légale.",
    'Чужое': 'Composants tiers',
    'Температуры читает LibreHardwareMonitor — четыре файла .dll рядом с программой. Библиотека принадлежит своим авторам и идёт по своей лицензии, MPL 2.0.': 'Les températures sont lues par LibreHardwareMonitor — quatre fichiers .dll à côté du programme. Cette bibliothèque appartient à ses propres auteurs et suit sa propre licence, MPL 2.0.',
    'Не удалось открыть файл: {}': "Impossible d'ouvrir le fichier : {}",
    'Загрузка процессора, %': 'Charge processeur, %',
    'Температура процессора': 'Température processeur',
    'Частота процессора, ГГц': 'Fréquence processeur, GHz',
    'Потребление процессора, Вт': 'Consommation processeur, W',
    'Обороты вентилятора ЦП': 'Vitesse du ventilateur CPU',
    'Загрузка видеокарты, %': 'Charge carte graphique, %',
    'Температура видеокарты': 'Température carte graphique',
    'Потребление видеокарты, Вт': 'Consommation carte graphique, W',
    'Загрузка видеопамяти, %': 'Charge mémoire vidéo, %',
    'Занято видеопамяти, ГБ': 'Mémoire vidéo utilisée, Go',
    'Частота видеокарты, МГц': 'Fréquence carte graphique, MHz',
    'Вентилятор видеокарты, %': 'Ventilateur carte graphique, %',
    'Загрузка ОЗУ, %': 'Charge RAM, %',
    'Занято ОЗУ, ГБ': 'RAM utilisée, Go',
    'Свободно ОЗУ, ГБ': 'RAM libre, Go',
    'Загрузка диска, %': 'Charge disque, %',
    'Свободно на диске, ГБ': 'Espace disque libre, Go',
    'Приём из сети, МБ/с': 'Réception réseau, Mo/s',
    'Отдача в сеть, МБ/с': 'Émission réseau, Mo/s',
    'Температура платы': 'Température carte mère',
    'Погода: температура': 'Météo : température',
    'Погода: ощущается как': 'Météo : ressenti',
    'Погода: влажность, %': 'Météo : humidité, %',
    'Погода: ветер, км/ч': 'Météo : vent, km/h',
    '— свой текст —': '— texte personnalisé —',
    'Загрузка процессора  23%': 'Charge processeur  23%',
    'Температура процессора  67 °C': 'Température processeur  67 °C',
    'Частота процессора  4.85 ГГц': 'Fréquence processeur  4.85 GHz',
    'Потребление процессора  142 Вт': 'Consommation processeur  142 W',
    'Загрузка видеокарты  41%': 'Charge carte graphique  41%',
    'Температура видеокарты  51 °C': 'Température carte graphique  51 °C',
    'Потребление видеокарты  186 Вт': 'Consommation carte graphique  186 W',
    'Видеопамять  9.9 ГБ': 'Mémoire vidéo  9.9 Go',
    'Видеопамять  9.9 / 16 ГБ': 'Mémoire vidéo  9.9 / 16 Go',
    'Загрузка ОЗУ  28%': 'Charge RAM  28%',
    'ОЗУ  17.0 / 64 ГБ': 'RAM  17.0 / 64 Go',
    'Свободно на диске  231 ГБ': 'Espace disque libre  231 Go',
    'Приём из сети  11.4 МБ/с': 'Réception réseau  11.4 Mo/s',
    'Отдача в сеть  2.3 МБ/с': 'Émission réseau  2.3 Mo/s',
    'Время работы  5ч 49м': 'Temps de fonctionnement  5h 49m',
    'Часы  как выбрано в настройках': 'Horloge  selon les réglages',
    'Часы с секундами  как выбрано в настройках': 'Horloge avec secondes  selon les réglages',
    'Дата  как выбрано в настройках': 'Date  selon les réglages',
    'Дата коротко  как выбрано в настройках': 'Date courte  selon les réglages',
    'Погода: температура со знаком настройки  12 °C': 'Météo : température selon le réglage  12 °C',
    'Часы  14:30': 'Horloge  14:30',
    'Часы с секундами  14:30:45': 'Horloge avec secondes  14:30:45',
    'Часы 12-часовые  02:30 PM': 'Horloge 12 heures  02:30 PM',
    'Часы 12-часовые с секундами  02:30:45 PM': 'Horloge 12 heures avec secondes  02:30:45 PM',
    'Дата  03.08.2026': 'Date  03.08.2026',
    'Дата  03.08.26': 'Date  03.08.26',
    'Дата  2026-08-03': 'Date  2026-08-03',
    'Дата  03 August': 'Date  03 août',
    'День недели  Monday': 'Jour de la semaine  lundi',
    'Погода кратко  Дождь': 'Météo courte  Pluie',
    'Погода подробно  Небольшой дождь': 'Météo détaillée  Pluie faible',
    'Погода и температура  Дождь  12 °C': 'Météo et température  Pluie  12 °C',
    'Погода подробно и температура': 'Météo détaillée et température',
    'Погода: только температура  12 °C': 'Météo : température seule  12 °C',
    'Погода: ощущается как  10 °C': 'Météo : ressenti  10 °C',
    'Погода: минимум и максимум  8…15 °C': 'Météo : min et max  8…15 °C',
    'Погода: ветер  4 км/ч': 'Météo : vent  4 km/h',
    'Погода: влажность  78 %': 'Météo : humidité  78 %',
    'Погода: город и температура': 'Météo : ville et température',
    'Погода: всё вместе': 'Météo : tout ensemble',
    'по центру': 'au centre',
    'слева, по середине': 'gauche, milieu',
    'справа, по середине': 'droite, milieu',
    'слева сверху': 'en haut à gauche',
    'по центру сверху': 'en haut au centre',
    'справа сверху': 'en haut à droite',
    'слева снизу': 'en bas à gauche',
    'по центру снизу': 'en bas au centre',
    'справа снизу': 'en bas à droite',
    'слева направо': 'de gauche à droite',
    'справа налево': 'de droite à gauche',
    'снизу вверх': 'de bas en haut',
    'сверху вниз': 'de haut en bas',
    'сверху': 'en haut',
    'снизу': 'en bas',
    'слева': 'à gauche',
    'справа': 'à droite',
    'заполнить с обрезкой': 'remplir avec recadrage',
    'вписать целиком': 'insérer en entier',
    'растянуть': 'étirer',
    'как есть': 'tel quel',
    'нет': 'aucun',
    'по диагонали': 'en diagonale',
    'текст': 'texte',
    'прямоугольник': 'rectangle',
    'квадрат': 'carré',
    'овал': 'ovale',
    'круг': 'cercle',
    'линия': 'ligne',
    'стрелка': 'flèche',
    'звезда': 'étoile',
    'полоса': 'barre',
    'кольцо': 'anneau',
    'картинка': 'image',
    'туда-обратно': 'aller-retour',
    'по кругу': 'en boucle',
    'затухание': 'fondu',
    'движение': 'déplacement',
    'поворот': 'rotation',
    'цвет': 'couleur',
    'размер': 'taille',
    'Arial обычный': 'Arial normal',
    'Arial жирный': 'Arial gras',
    'Segoe UI обычный': 'Segoe UI normal',
    'Segoe UI жирный': 'Segoe UI gras',
    'Consolas обычный': 'Consolas normal',
    'Consolas жирный': 'Consolas gras',
    'Tahoma обычный': 'Tahoma normal',
    'Tahoma жирный': 'Tahoma gras',
    'Verdana обычный': 'Verdana normal',
    'Verdana жирный': 'Verdana gras',
    'Calibri обычный': 'Calibri normal',
    'Calibri жирный': 'Calibri gras',
    'Искать по названию, типу и тексту слоя. Рядом — показывать все слои, только видимые ночью или только днём.': 'Rechercher par nom, type ou texte du calque. À côté : afficher tous les calques, seulement ceux visibles la nuit, ou seulement le jour.',
    'Подпись для себя, в списке слева. На картинку не влияет.': "Une étiquette pour vous, dans la liste de gauche. Sans effet sur l'image.",
    'Отступ слева, в точках. Начало координат — левый верхний угол.': "Décalage depuis la gauche, en points. L'origine est le coin supérieur gauche.",
    'Отступ сверху, в точках.': 'Décalage depuis le haut, en points.',
    'Куда линия приходит по горизонтали.': 'Où la ligne arrive horizontalement.',
    'Куда линия приходит по вертикали.': 'Où la ligne arrive verticalement.',
    'Наклон слоя в градусах, по часовой стрелке.': 'Inclinaison du calque en degrés, dans le sens horaire.',
    'Растянуть слой вширь. 1 — как есть, 2 — вдвое шире.': 'Étirer le calque en largeur. 1 : tel quel, 2 : deux fois plus large.',
    'Растянуть слой ввысь. 1 — как есть, 0.5 — вдвое ниже.': 'Étirer le calque en hauteur. 1 : tel quel, 0.5 : deux fois moins haut.',
    'Насколько слой прозрачен: 0 — не видно совсем, 1 — плотно.': 'Degré de transparence du calque : 0 — invisible, 1 — opaque.',
    'Что написать. В фигурных скобках подставляются показания: {cpu_load:.0f}% даст «37%».': 'Le texte à afficher. Les accolades insèrent une valeur : {cpu_load:.0f}% donnera « 37% ».',
    'Готовые надписи: часы, дата, погода, загрузка. Выбери — и текст подставится сам.': 'Textes tout prêts : horloge, date, météo, charge. Choisissez-en un et le texte se remplit tout seul.',
    'Файл шрифта. Любой из системы или положенный рядом с темой.': "Fichier de police. N'importe laquelle du système, ou placée à côté du thème.",
    'Высота букв в точках.': 'Hauteur des lettres en points.',
    'Влезть в ширину': 'Tenir dans la largeur',
    'Влезть в столько точек по ширине. Длинная надпись сама уменьшится, короткая останется как есть. 0 — не ужимать, тогда длинное уедет за край.': 'Tenir dans cette largeur, en points. Un texte long se réduit tout seul, un texte court reste inchangé. 0 : pas de réduction, un texte trop long dépassera du cadre.',
    'Цвет букв.': 'Couleur des lettres.',
    'За какую точку слой держится координатами. По центру — удобно для цифр, что меняют длину.': 'Le point du calque auquel se rattachent les coordonnées. Le centre est pratique pour des chiffres dont la longueur change.',
    'Цвет обводки. Помогает читать надпись поверх пёстрой картинки.': 'Couleur du contour. Aide à lire un texte sur une image chargée.',
    'Толщина обводки букв в точках.': 'Épaisseur du contour des lettres, en points.',
    'Ширина слоя в точках.': 'Largeur du calque en points.',
    'Высота слоя в точках.': 'Hauteur du calque en points.',
    'Скругление углов. 0 — прямые углы.': 'Arrondi des angles. 0 : angles droits.',
    'Основной цвет заливки.': 'Couleur principale de remplissage.',
    'Второй цвет: заливка станет переходом от первого ко второму.': 'Une seconde couleur : le remplissage devient un dégradé de la première vers la seconde.',
    'В какую сторону идёт переход между двумя цветами.': 'Dans quel sens va le dégradé entre les deux couleurs.',
    'Толщина линии или окантовки в точках.': 'Épaisseur de la ligne ou de la bordure, en points.',
    'Откуда берётся число: загрузка, температура, погода.': "D'où vient le chiffre : charge, température, météo.",
    'Какому значению соответствует пустая полоса или дуга.': "La valeur pour laquelle la barre ou l'arc est vide.",
    'Какому значению соответствует полная полоса или дуга.': "La valeur pour laquelle la barre ou l'arc est plein.",
    'В какую сторону растёт заполнение.': 'Dans quel sens le remplissage progresse.',
    'Цвет незаполненной части. Можно не задавать.': 'Couleur de la partie non remplie. Facultatif.',
    'Радиус в точках. Координаты — это центр, а не угол.': 'Rayon en points. Les coordonnées désignent le centre, pas un coin.',
    'Радиус впадин между лучами звезды.': "Rayon des creux entre les branches de l'étoile.",
    'Сколько лучей у звезды.': "Nombre de branches de l'étoile.",
    'Повернуть звезду на столько градусов.': "Faire pivoter l'étoile de cet angle, en degrés.",
    'Толщина дуги в точках.': "Épaisseur de l'arc en points.",
    'С какой стороны у кольца вырез.': "De quel côté se trouve l'ouverture de l'anneau.",
    'Ширина выреза в градусах. 60 — небольшой, 180 — половина круга.': "Largeur de l'ouverture en degrés. 60 : petite, 180 : un demi-cercle.",
    'Заполнять дугу с другого конца, навстречу обычному.': "Remplir l'arc depuis l'autre extrémité, à contre-sens de l'habitude.",
    'Скруглить концы — дуга или линия смотрится мягче.': "Arrondir les extrémités — l'arc ou la ligne paraît plus doux.",
    'Размер наконечника стрелки в точках.': 'Taille de la pointe de flèche en points.',
    'Файл картинки или папка с кадрами. Папка листается как ролик.': "Fichier image ou dossier d'images. Un dossier défile comme une animation.",
    'Что делать, если картинка не совпала с отведённым местом.': "Que faire si l'image ne correspond pas à l'espace prévu.",
    'Своя частота листания кадров. Ставь ту, с которой резал ролик, иначе он поедет быстрее или медленнее задуманного.': "Sa propre cadence de défilement. Réglez-la sur celle du montage d'origine, sinon l'animation ira plus vite ou plus lentement que prévu.",
    'Включи, если PNG выгружены из DaVinci: там цвет уже умножен на прозрачность, и без этого по мягкому краю пойдёт тёмная каёмка.': 'Activez ceci pour des PNG exportés depuis DaVinci : leur couleur est déjà multipliée par la transparence, sans quoi un liseré sombre apparaît sur les bords doux.',
    'Поднять непрозрачность, если объект вырезался полупрозрачным и выглядит блёклым. 1 — не трогать, 1.5 — заметно плотнее.': "Augmenter l'opacité si l'objet détouré est semi-transparent et paraît terne. 1 : inchangé, 1.5 : nettement plus dense.",
    'Поворот, °': 'Rotation, °',
    'Шире': 'Plus large',
    'Выше': 'Plus haut',
    'Прозрачность': 'Transparence',
    'Второй цвет': 'Seconde couleur',
    'Переход цвета': 'Dégradé de couleur',
    'Готовая надпись': 'Texte prédéfini',
    'Текст': 'Texte',
    'Шрифт': 'Police',
    'Размер': 'Taille',
    'Цвет': 'Couleur',
    'Держится за': 'Ancré sur',
    'Обводка': 'Contour',
    'Толщина обводки': 'Épaisseur du contour',
    'Ширина': 'Largeur',
    'Высота': 'Hauteur',
    'Скругление': 'Arrondi',
    'Заливка': 'Remplissage',
    'Окантовка': 'Bordure',
    'Толщина': 'Épaisseur',
    'Наконечник': 'Pointe',
    'Мягкие концы': 'Extrémités arrondies',
    'X конца': "X d'arrivée",
    'Y конца': "Y d'arrivée",
    'Радиус': 'Rayon',
    'Радиус впадин': 'Rayon des creux',
    'Лучей': 'Branches',
    'Наклон, °': 'Inclinaison, °',
    'Показание': 'Valeur',
    'Пусто при': 'Vide à',
    'Полно при': 'Plein à',
    'Направление': 'Direction',
    'Цвет заполнения': 'Couleur de remplissage',
    'Цвет пустоты': 'Couleur du vide',
    'Толщина дуги': "Épaisseur de l'arc",
    'Вырез': 'Ouverture',
    'Вырез, °': 'Ouverture, °',
    'Наоборот': "À l'inverse",
    'Картинка': 'Image',
    'Как вписать': 'Ajustement',
    'PNG из DaVinci': 'PNG issu de DaVinci',
    'Плотнее': 'Plus dense',
    'Что показывает': "Ce qu'il affiche",
    'Где и какого размера': 'Où et de quelle taille',
    'Как выглядит': 'Apparence',
    'Прочее': 'Divers',
    'новый текст': 'nouveau texte',
    'новый прямоугольник': 'nouveau rectangle',
    'новый квадрат': 'nouveau carré',
    'новый овал': 'nouvel ovale',
    'новый круг': 'nouveau cercle',
    'новая линия': 'nouvelle ligne',
    'новая стрелка': 'nouvelle flèche',
    'новая звезда': 'nouvelle étoile',
    'новая полоса': 'nouvelle barre',
    'новое кольцо': 'nouvel anneau',
    'новая картинка': 'nouvelle image',
    'слой': 'calque',
    'блок': 'bloc',
    ' копия': ' copie',
    '←  К темам': '←  Aux thèmes',
    'Сохранить как…': 'Enregistrer sous…',
    'Вернуть с диска': 'Recharger depuis le disque',
    'Открыть тему…': 'Ouvrir un thème…',
    'Описание темы…': 'Détails du thème…',
    '●  Магнит': '●  Aimant',
    '○  Магнит': '○  Aimant',
    '●  Сетка {}': '●  Grille {}',
    '○  Сетка': '○  Grille',
    'Выровнять:': 'Aligner :',
    'К левому краю экрана': "Contre le bord gauche de l'écran",
    'По центру экрана вбок': "Au centre horizontal de l'écran",
    'К правому краю экрана': "Contre le bord droit de l'écran",
    'К верхнему краю экрана': "Contre le bord haut de l'écran",
    'По центру экрана вниз': "Au centre vertical de l'écran",
    'К нижнему краю экрана': "Contre le bord bas de l'écran",
    'Размер:': 'Taille :',
    'Уменьшить выбранные слои на десятую часть': "Réduire les calques choisis d'un dixième",
    'Увеличить выбранные слои на десятую часть': "Agrandir les calques choisis d'un dixième",
    '. Работает и на нескольких сразу: выдели их в списке с Ctrl или Shift.': '. Fonctionne aussi sur plusieurs à la fois : sélectionnez-les dans la liste avec Ctrl ou Shift.',
    'Показать на экране': "Afficher à l'écran",
    'Остановить показ': "Arrêter l'affichage",
    'Слои · нижние перекрываются верхними': 'Calques · les inférieurs sont recouverts par les supérieurs',
    'все': 'tous',
    'день': 'jour',
    'Скрыть': 'Masquer',
    'Копия': 'Copie',
    'Удалить': 'Supprimer',
    'Добавить:': 'Ajouter :',
    'Режим правки:': "Mode d'édition :",
    'Ночной вид': 'Vue de nuit',
    'Переход': 'Transition',
    'Дневной вид': 'Vue de jour',
    'Прокрутка перехода:': 'Parcourir la transition :',
    'Двигается только выбранный слой. Стрелки — на пиксель, Shift+стрелки — на десять.\nМагнит притягивает к краям и центрам соседей; Alt при перетаскивании временно его отключает.\nНесколько слоёв разом: Ctrl+щелчок или Shift+щелчок в списке.\nCtrl+Z отменить · Ctrl+Y вернуть · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S сохранить · Delete удалить': "Seul le calque sélectionné se déplace. Les flèches déplacent d'un pixel, Shift+flèches de dix.\nL'aimant attire vers les bords et les centres des voisins ; Alt pendant le glissement le désactive temporairement.\nPlusieurs calques à la fois : Ctrl+clic ou Shift+clic dans la liste.\nCtrl+Z annuler · Ctrl+Y rétablir · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S enregistrer · Suppr supprimer",
    'Тип блока': 'Type de bloc',
    'Экран': 'Écran',
    'Фон под всеми блоками:': 'Fond sous tous les blocs :',
    'Убрать дневной': 'Retirer le jour',
    'нет дневного — фон ночной круглые сутки': 'pas de fond de jour — le fond de nuit reste toute la journée',
    'Сжимать кадры фона': 'Compresser les images de fond',
    'памяти вчетверо меньше, картинка та же': 'quatre fois moins de mémoire, image identique',
    'кадры фона будут сжаты — готовлю заново': 'les images de fond vont être compressées — préparation en cours',
    'кадры фона будут распакованы — готовлю заново': 'les images de fond vont être décompressées — préparation en cours',
    'Здесь настраивается только движение.\nЧто именно меняется — задаётся\nв ночном и дневном видах.': 'Seul le mouvement se règle ici.\nCe qui change exactement se définit\ndans les vues de nuit et de jour.',
    'Правки уходят в дневной вид': 'Les modifications vont dans la vue de jour',
    'Сбросить': 'Réinitialiser',
    'Переход к дневному виду': 'Transition vers la vue de jour',
    'настроен': 'configuré',
    'не настроен': 'non configuré',
    'Что меняется:': 'Ce qui change :',
    'Отрезок перехода, %': 'Segment de la transition, %',
    'Начало': 'Début',
    'Середина': 'Milieu',
    'Окончание': 'Fin',
    'Повтор по времени': 'Répétition périodique',
    'Период, секунд': 'Période, secondes',
    'Как повторять': 'Mode de répétition',
    'Показать в момент': 'Afficher au moment',
    'сброс': 'réinitialisation',
    'Реакция на датчик': 'Réaction à une valeur',
    'Датчик': 'Valeur',
    'Начинает меняться при': 'Commence à changer à',
    'Полностью при': 'Complet à',
    'Показать при значении': 'Afficher pour la valeur',
    'отменять нечего': 'rien à annuler',
    'отменено': 'annulé',
    'возвращать нечего': 'rien à rétablir',
    'возвращено': 'rétabli',
    'слой скопирован': 'calque copié',
    'слой вырезан': 'calque coupé',
    'в буфере нет слоя': 'aucun calque dans le presse-papiers',
    'слой вставлен': 'calque collé',
    'магнит включён': 'aimant activé',
    'магнит выключен': 'aimant désactivé',
    'сетка выключена': 'grille désactivée',
    'сетка по {} точек': 'grille tous les {} points',
    'размер {:+.0f} % у {} слоёв': 'taille {:+.0f} % sur {} calques',
    'показано {} из {}': '{} affichés sur {}',
    'X {}  Y {}   (без магнита)': 'X {}  Y {}   (sans aimant)',
    'X {}  Y {}{}': 'X {}  Y {}{}',
    '   ({} слоёв)': '   ({} calques)',
    'шрифт скопирован в папку fonts': 'police copiée dans le dossier fonts',
    'не смог скопировать: {}': 'impossible de copier : {}',
    'переименовано, папка тоже': 'renommé, le dossier aussi',
    'папку переименовать не вышло: {}': 'impossible de renommer le dossier : {}',
    'описание изменено, не забудь сохранить': "description modifiée, n'oubliez pas d'enregistrer",
    'дневной вид блока сброшен': 'la vue de jour du bloc a été réinitialisée',
    'ошибка: {}': 'erreur : {}',
    'сохранено': 'enregistré',
    'открыто: ': 'ouvert : ',
    'экран не найден': 'écran introuvable',
    'показ прерван: {}': 'affichage interrompu : {}',
    '{} · редактор · {} — {}': '{} · éditeur · {} — {}',
    'Удалить слой «{}»?': 'Supprimer le calque « {} » ?',
    'Удалить выбранные слои ({} шт.)?': 'Supprimer les calques sélectionnés ({} au total) ?',
    'Выбери файл шрифта': 'Choisissez un fichier de police',
    'Шрифты': 'Polices',
    'Папка с кадрами (Отмена - выбрать файл)': "Dossier d'images (Annuler pour choisir un fichier)",
    'Открыть': 'Ouvrir',
    'Вернуть': 'Recharger',
    'Папка с темой (Отмена — выбрать файл)': 'Dossier du thème (Annuler pour choisir un fichier)',
    'В папке нет файлов описания темы (.json).\n\nФайл темы должен лежать рядом с папками кадров.': "Le dossier ne contient aucun fichier de description de thème (.json).\n\nLe fichier du thème doit se trouver à côté des dossiers d'images.",
    'Какой файл темы открыть': 'Quel fichier de thème ouvrir',
    'Файл темы': 'Fichier de thème',
    'Описание панели': 'Fichier du panneau',
    'Не удалось прочитать файл:\n{}': 'Impossible de lire le fichier :\n{}',
    'Это не похоже на тему: нет раздела layers.': 'Cela ne ressemble pas à un thème : aucune section layers.',
    'Тема ссылается на то, чего нет рядом с её файлом:\n\n  ': 'Le thème pointe vers des éléments absents à côté de son fichier :\n\n  ',
    '\n\nПеренеси эти папки в {}': '\n\nDéplacez ces dossiers vers {}',
    'Не найден файл описания: {}': 'Fichier de description introuvable : {}',
    'осмотр машины': 'inspection de la machine',
    '[д/н] ': '[o/n] ',
    'прервано': 'interrompu',
    'язык уже выбран': 'la langue est déjà choisie',
    'язык Windows подсказывал другой: {}': 'Windows suggérait une autre langue : {}',
    'язык выбран по языку Windows': 'la langue est reprise de Windows',
    'поменять можно в Настройках -> Оформление программы': 'modifiable dans Réglages -> Apparence du programme',
    'Библиотеки': 'Bibliothèques',
    'сборка кадров и всё рисование': 'construction des images et tout le dessin',
    'загрузка процессора, память, диски, сеть': 'charge processeur, mémoire, disques, réseau',
    'разговор с экраном по COM-порту': "communication avec l'écran via le port COM",
    'само окно программы': 'la fenêtre du programme elle-même',
    'температура процессора, видеокарты AMD и Intel': 'température du processeur, des cartes graphiques AMD et Intel',
    'переходы цвета и мягкие края': 'dégradés de couleur et bords doux',
    'значок рядом с часами': "icône près de l'horloge",
    'переустанови Python, отметив «tcl/tk and IDLE»': 'réinstallez Python en cochant « tcl/tk and IDLE »',
    'Поставить всё разом:': "Tout installer d'un coup :",
    'Без обязательных библиотек осматривать дальше нечего.': "Sans les bibliothèques obligatoires, il n'y a rien de plus à inspecter.",
    'Права': 'Droits',
    'права администратора есть': 'les droits administrateur sont présents',
    'прав администратора нет': 'aucun droit administrateur',
    'без них температуры процессора не будет вовсе': "sans eux, il n'y aura aucune température processeur",
    'запусти start.bat, а программу - через app.bat': 'lancez start.bat, puis le programme via app.bat',
    'Библиотека датчиков': 'La bibliothèque de capteurs',
    'нет рядом с программой': 'absente à côté du programme',
    'возьми из архива LibreHardwareMonitor и положи сюда': "prenez-la dans l'archive LibreHardwareMonitor et placez-la ici",
    'все четыре файла на месте': 'les quatre fichiers sont en place',
    'снял пометку «из интернета»': "la marque « provient d'internet » a été retirée",
    'помечен как скачанный из интернета': 'marqué comme téléchargé depuis internet',
    'Свойства файла -> галочка «Разблокировать»': 'Propriétés du fichier -> case « Débloquer »',
    'пометки «из интернета» ни на одном нет': "aucun n'a la marque « provient d'internet »",
    'Железо': 'Le matériel',
    'процессор': 'processeur',
    'видеокарта': 'carte graphique',
    'название выяснить не удалось': 'impossible de déterminer le nom',
    'ядер {}, потоков {}': '{} cœurs, {} threads',
    'оперативной памяти {:.0f} ГБ': '{:.0f} Go de mémoire vive',
    'системный диск {}': 'disque système {}',
    'опрашиваю железо, это занимает несколько секунд…': 'interrogation du matériel, cela prend quelques secondes…',
    'загрузка процессора': 'charge processeur',
    'температура процессора': 'température processeur',
    'частота процессора': 'fréquence processeur',
    'загрузка памяти': 'charge mémoire',
    'загрузка диска': 'charge disque',
    'приём из сети': 'réception réseau',
    'загрузка видеокарты': 'charge carte graphique',
    'температура видеокарты': 'température carte graphique',
    'занято видеопамяти': 'mémoire vidéo utilisée',
    'потребление видеокарты': 'consommation carte graphique',
    'не читается': 'illisible',
    'температура читается': 'la température est lisible',
    'выбран датчик: ': 'capteur choisi : ',
    'источник открылся, но отдаёт нули': "la source s'est ouverte mais ne renvoie que des zéros",
    'библиотека отдаёт нули по всем ядрам: нет прав администратора': 'la bibliothèque renvoie des zéros sur tous les cœurs : droits administrateur absents',
    'так бывает без прав администратора: запусти start.bat': 'cela arrive sans droits administrateur : lancez start.bat',
    'источник не найден': 'aucune source trouvée',
    'запусти программу через app.bat': 'lancez le programme via app.bat',
    'нужны права администратора и четыре .dll рядом': 'droits administrateur et quatre fichiers .dll à côté nécessaires',
    'видеокарта читается': 'la carte graphique est lisible',
    'нет источника показаний': 'aucune source de valeurs',
    'положи System.Numerics.Vectors.dll рядом с программой': 'placez System.Numerics.Vectors.dll à côté du programme',
    'нужен для видеокарт не Nvidia — на месте': 'nécessaire pour les cartes non-Nvidia — en place',
    'нужен, чтобы читать видеокарту не Nvidia': 'nécessaire pour lire une carte graphique non-Nvidia',
    'особых прав не нужно': 'aucun droit particulier requis',
    'температуры читает ядро, оно их и так отдаёт': 'les températures sont lues par le noyau, qui les fournit de toute façon',
    'температуры читает ядро, библиотека датчиков не нужна': "les températures sont lues par le noyau, la bibliothèque de capteurs n'est pas nécessaire",
    'ядро Linux': 'le noyau Linux',
    'ядро Linux (drm)': 'le noyau Linux (drm)',
    'ядро не отдаёт температур: нет /sys/class/hwmon': 'le noyau ne fournit aucune température : /sys/class/hwmon absent',
    'ядро не отдаёт показаний видеокарты: нет /sys/class/drm': 'le noyau ne fournit aucune valeur de carte graphique : /sys/class/drm absent',
    'ядро не выложило /sys/class/hwmon: посмотри, загружен ли модуль датчиков процессора': "le noyau n'a pas exposé /sys/class/hwmon : vérifiez si le module de capteurs du processeur est chargé",
    'для Nvidia нужен nvidia-smi, для AMD - драйвер amdgpu в /sys/class/drm': 'pour Nvidia, nvidia-smi est nécessaire ; pour AMD, le pilote amdgpu dans /sys/class/drm',
    'библиотеке не хватает файла System.Numerics.Vectors.dll — без него показаний видеокарты не будет. Возьми его из архива LibreHardwareMonitor': "il manque le fichier System.Numerics.Vectors.dll à la bibliothèque — sans lui, aucune valeur de carte graphique. Prenez-le dans l'archive LibreHardwareMonitor",
    'для Nvidia хватит драйвера, для AMD и Intel нужна библиотека датчиков и права': 'pour Nvidia, le pilote suffit ; pour AMD et Intel, la bibliothèque de capteurs et les droits sont nécessaires',
    'psutil (процессор, память, диски, сеть): ': 'psutil (processeur, mémoire, disques, réseau) : ',
    'есть': 'présent',
    'НЕ УСТАНОВЛЕН': 'NON INSTALLÉ',
    'процессор: ': 'processeur : ',
    'видеокарта: ': 'carte graphique : ',
    'показания видеокарты: ': 'valeurs de la carte graphique : ',
    'показания видеокарты: НЕТ — ': 'valeurs de la carte graphique : AUCUNE — ',
    'показания видеокарты: НЕТ — нет ни nvidia-smi, ни LibreHardwareMonitorLib.dll': 'valeurs de la carte graphique : AUCUNE — ni nvidia-smi ni LibreHardwareMonitorLib.dll',
    'температура процессора: читается ({})': 'température processeur : lisible ({})',
    'библиотека напрямую': 'la bibliothèque directement',
    'через WMI': 'via WMI',
    'способ не указан': 'méthode non précisée',
    ', вспомогательных сборок: {}': ', assemblages auxiliaires : {}',
    '  выбран датчик: ': '  capteur choisi : ',
    '  все найденные датчики процессора:': '  tous les capteurs processeur trouvés :',
    'температура процессора: НЕТ — ': 'température processeur : AUCUNE — ',
    '  ВНИМАНИЕ: программа запущена без прав администратора.': '  ATTENTION : le programme est lancé sans droits administrateur.',
    '  Температуру процессора без них прочитать невозможно в принципе:': '  Sans eux, la température processeur ne peut tout simplement pas être lue :',
    '  Windows не даёт доступ к регистрам процессора обычным программам.': "  Windows n'autorise pas les programmes ordinaires à accéder aux registres du processeur.",
    '  Права администратора есть. Положи рядом LibreHardwareMonitorLib.dll': '  Les droits administrateur sont présents. Placez LibreHardwareMonitorLib.dll à côté',
    '  и HidSharp.dll, либо запусти саму LibreHardwareMonitor в фоне.': '  et HidSharp.dll, ou lancez LibreHardwareMonitor lui-même en arrière-plan.',
    'рядом нет LibreHardwareMonitorLib.dll (положи её в папку с программой)': 'LibreHardwareMonitorLib.dll est absent à côté (placez-le dans le dossier du programme)',
    'библиотека есть, но нет pythonnet. Выполни: pip install pythonnet': 'la bibliothèque est présente, mais pythonnet manque. Exécutez : pip install pythonnet',
    'библиотека заблокирована Windows как скачанная из интернета. Свойства файла -> галочка «Разблокировать»': 'la bibliothèque est bloquée par Windows comme téléchargée depuis internet. Propriétés du fichier -> case « Débloquer »',
    'погода: получена{}{}': 'météo : reçue{}{}',
    ' от ': ' depuis ',
    ' для ': ' pour ',
    '  восход и закат: ': '  lever et coucher du soleil : ',
    'погода: НЕТ — ': 'météo : AUCUNE — ',
    'ещё не загружена': 'pas encore chargée',
    'не выбрано место — укажи город в настройках, раздел «Погода»': 'aucun lieu choisi — indiquez une ville dans les réglages, section « Météo »',
    'не смог заглянуть в порты': "impossible d'examiner les ports",
    'экран найден': 'écran trouvé',
    'ни на одном COM-порту': 'sur aucun port COM',
    'проверь кабель от помпы к разъёму USB на плате': 'vérifiez le câble entre la pompe et le connecteur USB de la carte',
    'а вот что на портах есть:': 'voici en revanche ce que les ports proposent :',
    'COM-портов не найдено вообще': "aucun port COM n'a été trouvé",
    'погода выключена в настройках': 'la météo est désactivée dans les réglages',
    'прогноз получен': 'prévisions reçues',
    'восход {}   закат {}   ({})': 'lever {}   coucher {}   ({})',
    'свой расчёт': 'calcul interne',
    'прогноза нет': 'aucune prévision',
    'источник не ответил': "la source n'a pas répondu",
    'проверь интернет и место в Настройках -> Погода и адрес': 'vérifiez internet et le lieu dans Réglages -> Météo et adresse',
    'не смог просмотреть темы': 'impossible de parcourir les thèmes',
    'названия железа нигде не вписаны руками': "aucun nom de matériel n'est écrit à la main nulle part",
    '«{}»: {} слоёв с вписанным названием': '« {} » : {} calques avec un nom écrit en dur',
    'Заменить, чтобы тема сама называла ваше железо?': 'Remplacer pour que le thème nomme lui-même votre matériel ?',
    'оставил как было': 'laissé tel quel',
    'тема поправлена': 'thème corrigé',
    'не смог записать тему': "impossible d'enregistrer le thème",
    'Записываю в настройки': 'Écriture dans les réglages',
    'железо записано': 'le matériel a été enregistré',
    'опрос nvidia-smi': 'interrogation de nvidia-smi',
    'включён': 'activé',
    'выключен, он тут не нужен': 'désactivé, inutile ici',
    'Температуру прочитать нечем. Выключить её опрос?': 'Rien ne peut lire la température. Désactiver son interrogation ?',
    'опрос температур выключен': "l'interrogation des températures est désactivée",
    'Итог': 'Bilan',
    'Всё на месте. Запускай app.bat.': 'Tout est en place. Lancez app.bat.',
    'Без этого программа будет работать не полностью:': 'Sans cela, le programme ne fonctionnera pas complètement :',
    'Мелочи, жить можно:': 'Détails mineurs, on peut vivre avec :',
    'Когда поправишь - запусти start.bat ещё раз.': 'Une fois corrigé, relancez start.bat.',
}

POGODA = {
    0: ("Dégagé", "Ciel dégagé"),
    1: ("Dégagé", "Plutôt dégagé"),
    2: ("Nuages", "Partiellement nuageux"),
    3: ("Couvert", "Couvert"),
    45: ("Brouillard", "Brouillard"),
    48: ("Brouillard", "Brouillard givrant"),
    51: ("Bruine", "Bruine faible"),
    53: ("Bruine", "Bruine"),
    55: ("Bruine", "Bruine forte"),
    56: ("Verglas", "Bruine verglaçante"),
    57: ("Verglas", "Bruine verglaçante forte"),
    61: ("Pluie", "Pluie faible"),
    63: ("Pluie", "Pluie"),
    65: ("Pluie", "Pluie forte"),
    66: ("Verglas", "Pluie verglaçante"),
    67: ("Verglas", "Pluie verglaçante forte"),
    71: ("Neige", "Neige faible"),
    73: ("Neige", "Neige"),
    75: ("Neige", "Neige forte"),
    77: ("Neige", "Grains de neige"),
    80: ("Averses", "Averses faibles"),
    81: ("Averses", "Averses"),
    82: ("Averses", "Averses fortes"),
    85: ("Neige", "Averses de neige"),
    86: ("Neige", "Averses de neige fortes"),
    95: ("Orage", "Orage"),
    96: ("Orage", "Orage avec grêle"),
    99: ("Orage", "Orage violent avec grêle"),
}

SOKRASHENO = {
    2: "Partiel. nuageux",
    57: "Bruine vergl. forte",
    67: "Pluie vergl. forte",
    86: "Averses de neige f.",
    99: "Orage violent, grêle",
}
