#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  Немецкий: слова программы и слова погоды.
#  Часть проекта EOne screen.
#
#  Автор: EOne
#  Лицензия: CC BY-NC-SA 4.0 — использование в коммерческих целях
#  запрещено без письменного разрешения автора. См. файл LICENSE.
#
"""yazyk_de.py - немецкий. Устройство описано в yazyk_es.py.

ПЕРЕВОД СДЕЛАН С ПОМОЩЬЮ ИИ и носителем языка не проверялся. Русский
и английский написаны автором, остальные пять - нет. Если вы говорите
на этом языке и видите ошибку или корявость, поправьте: строку можно
менять прямо здесь, а ключ трогать нельзя.

"""

SLOVAR = {
    # Готовые надписи, которые всегда по-английски:
    # они просят {weather_en}, а не {weather}.
    "Weather short  Rain": "Wetter kurz, immer Englisch  Rain",
    "Weather full  Light rain": "Wetter ausführlich, immer Englisch  Light rain",
    "Weather and temperature  Rain  12 °C": "Wetter und Temperatur, immer Englisch  Rain  12 °C",
    "Weather full and temperature": "Wetter ausführlich und Temperatur, immer Englisch",
    "Weather: feels like  10 °C": "Wetter: gefühlt wie, immer Englisch  10 °C",
    "Weather: wind  4 km/h": "Wetter: Wind, immer Englisch  4 km/h",
    "Weather: humidity  78 %": "Wetter: Luftfeuchtigkeit, immer Englisch  78 %",
    "Weather: everything": "Wetter: alles zusammen, immer Englisch",
    # Значения движка: подпись видит человек, а в тему уходит
    # русское слово - его подставляет сама программа.
    "плавно": "weich",
    "средне": "mittel",
    "резко": "hart",

    'Главная': 'Startseite',
    'Темы': 'Themen',
    'Настройки': 'Einstellungen',
    'экран водянки': 'Wasserkühlungs-Bildschirm',
    'экран выключен': 'Bildschirm aus',
    'экран: {} · {:.0f} кадр/с': 'Bildschirm: {} · {:.0f} Bilder/s',
    'переход {:.0f} с': 'Übergang {:.0f} s',
    'тема отправлена на экран': 'Thema an den Bildschirm gesendet',
    'перезапускаю экран…': 'Bildschirm wird neu gestartet…',
    'сбой обновления: {}': 'Fehler beim Aktualisieren: {}',
    '{} — экран выключен': '{} — Bildschirm aus',
    '{} — {} ({:.1f} кадр/с, {})': '{} — {} ({:.1f} Bilder/s, {})',
    'Включить или выключить экран': 'Bildschirm ein- oder ausschalten',
    'Показать окно': 'Fenster anzeigen',
    'Выход': 'Beenden',
    'Пауза': 'Pause',
    'Продолжить': 'Weiter',
    'Перечитать тему': 'Thema neu einlesen',
    '{} · {} — {} ({:.1f} кадр/с, тема {})': '{} · {} — {} ({:.1f} Bilder/s, Thema {})',
    'по солнцу': 'nach der Sonne',
    'как в Windows': 'wie in Windows',
    'всегда ночная': 'immer Nacht',
    'всегда дневная': 'immer Tag',
    'запускается': 'startet',
    'остановлена': 'gestoppt',
    'на паузе': 'pausiert',
    'слишком много сбоев': 'zu viele Fehler',
    'Сохранить правки?': 'Änderungen speichern?',
    'Несохранённые правки пропадут. Продолжить?': 'Nicht gespeicherte Änderungen gehen verloren. Fortfahren?',
    'Это не похоже на тему: нет слоёв.': 'Das sieht nicht nach einem Thema aus: keine Ebenen.',
    'Моя тема': 'Mein Thema',
    'Сейчас на экране': 'Gerade auf dem Bildschirm',
    'Что показывать': 'Was angezeigt wird',
    'Погода на экране': 'Wetter auf dem Bildschirm',
    'Включить экран': 'Bildschirm einschalten',
    'Выключить экран': 'Bildschirm ausschalten',
    'Перезапустить': 'Neu starten',
    'выключен': 'aus',
    'работает': 'läuft',
    'работает · {:.0f} кадр/с': 'läuft · {:.0f} Bilder/s',
    '(прогноз не пришёл)': '(keine Vorhersage angekommen)',
    'готовлю кадры фона': 'Hintergrundbilder werden vorbereitet',
    'тема: ': 'Thema: ',
    'погода': 'Wetter',
    'днём': 'tagsüber',
    'ночью': 'nachts',
    'восход {}   закат {}   сейчас {:.0f} % дня': 'Aufgang {}   Untergang {}   jetzt {:.0f} % des Tages',
    '   (прогноз не пришёл)': '   (keine Vorhersage angekommen)',
    'отправлено кадров {}': 'gesendete Bilder {}',
    'сбоев {}': 'Fehler {}',
    '{:g} кадр/с': '{:g} Bilder/s',
    'не удалось собрать кадр: {}': 'Bild konnte nicht erstellt werden: {}',
    'кадры фона не листаются, чтобы окно не тратило лишнего': 'Hintergrundbilder laufen hier nicht mit, damit das Fenster nichts unnötig verbraucht',
    'Начать или прекратить вывод картинки на экран водянки.': 'Bildausgabe an den Wasserkühlungs-Bildschirm starten oder stoppen.',
    'Придержать вывод, не закрывая порт. Экран замрёт на последнем кадре.': 'Ausgabe anhalten, ohne den Port zu schließen. Der Bildschirm bleibt beim letzten Bild stehen.',
    'Заново открыть порт и поздороваться с экраном. Выручает, если картинка сбилась или порт подвис.': 'Port neu öffnen und den Bildschirm neu begrüßen. Hilft, wenn das Bild durcheinander ist oder der Port hängt.',
    'Яркость подсветки экрана водянки. Уходит на экран, когда отпустишь ползунок.': 'Helligkeit der Beleuchtung des Wasserkühlungs-Bildschirms. Wird übernommen, sobald du den Regler loslässt.',
    'По солнцу': 'Nach der Sonne',
    'Как в Windows': 'Wie in Windows',
    'Ночь': 'Nacht',
    'День': 'Tag',
    'Светлеет на рассвете и темнеет на закате, по времени восхода и заката в твоём городе.': 'Wird bei Sonnenaufgang heller und bei Sonnenuntergang dunkler, nach den Zeiten in deiner Stadt.',
    'Следит за оформлением Windows: светлая тема — дневной вид, тёмная — ночной.': 'Folgt dem Windows-Design: helles Design zeigt die Tagesansicht, dunkles die Nachtansicht.',
    'Всегда ночной вид, независимо от времени.': 'Immer die Nachtansicht, unabhängig von der Uhrzeit.',
    'Всегда дневной вид, независимо от времени.': 'Immer die Tagesansicht, unabhängig von der Uhrzeit.',
    'По прогнозу': 'Nach Vorhersage',
    'Ясно': 'Klar',
    'Пасмурно': 'Bewölkt',
    'Дождь': 'Regen',
    'Гроза': 'Gewitter',
    'Снег': 'Schnee',
    'Метель': 'Schneesturm',
    'Туман': 'Nebel',
    'Мороз': 'Frost',
    'Жара': 'Hitze',
    'Показывать настоящий прогноз.': 'Echte Vorhersage anzeigen.',
    'Показать «{}» так, будто оно за окном: {:+.0f} {}, ветер {:.0f} {}. Прогноз никуда не девается.': '„{}“ so anzeigen, als wäre es gerade draußen: {:+.0f} {}, Wind {:.0f} {}. Die Vorhersage bleibt dabei erhalten.',
    'Показывать дождь, снег, туман и грозу на дневной теме.': 'Regen, Schnee, Nebel und Gewitter im Tag-Design anzeigen.',
    'То же на ночной. Звёзды и метеоры останутся в любом случае.': 'Dasselbe für die Nacht. Sterne und Meteore bleiben in jedem Fall.',
    '{}: {}, {:.0f} {}, ветер {:.0f} {}   ·   небо — {}': '{}: {}, {:.0f} {}, Wind {:.0f} {}   ·   Himmel — {}',
    'км/ч': 'km/h',
    'м/с': 'm/s',
    'миль/ч': 'mph',
    'выдумано': 'erfunden',
    'за окном': 'draußen',
    'нет данных': 'keine Daten',
    'ничего': 'nichts',
    'ясно': 'klar',
    'облака': 'Wolken',
    'серость': 'Grau',
    'дождь': 'Regen',
    'снег': 'Schnee',
    'гроза': 'Gewitter',
    'туман': 'Nebel',
    'Мои темы': 'Meine Themen',
    'Создать тему': 'Neues Thema',
    'Редактор': 'Editor',
    'Всё, что лежит рядом с программой. Отсюда тему отправляют на экран, правят, копируют и упаковывают для пересылки.': 'Alles, was neben dem Programm liegt. Von hier aus wird ein Thema an den Bildschirm gesendet, bearbeitet, kopiert und zum Versenden verpackt.',
    'Обновить': 'Aktualisieren',
    'Из папки…': 'Aus einem Ordner…',
    'Из архива…': 'Aus einem Archiv…',
    'На экран': 'Auf den Bildschirm',
    'Изменить': 'Bearbeiten',
    'Открыть в редакторе': 'Im Editor öffnen',
    'Переименовать': 'Umbenennen',
    'открыта': 'geöffnet',
    'нет предпросмотра': 'keine Vorschau',
    '{} слоёв · {} · {:g} кадр/с': '{} Ebenen · {} · {:g} Bilder/s',
    'автор: {}   ·   {}': 'Autor: {}   ·   {}',
    'Сделать эту тему текущей: она уйдёт на экран водянки и откроется на главной.': 'Dieses Thema zum aktuellen machen: Es geht an den Wasserkühlungs-Bildschirm und öffnet sich auf der Startseite.',
    'Открыть тему в редакторе: слои, надписи, цвета, дневной и ночной вид.': 'Thema im Editor öffnen: Ebenen, Beschriftungen, Farben, Tag- und Nachtansicht.',
    'Сменить название темы. Папка на диске получит то же имя — тема и папка ходят вместе.': 'Themennamen ändern. Der Ordner auf der Festplatte bekommt denselben Namen — Thema und Ordner gehören zusammen.',
    'Название, автор и пояснение к теме. Эти строки уедут вместе с ней к другому человеку. Название меняет и имя папки на диске.': 'Name, Autor und Beschreibung des Themas. Diese Angaben reisen mit dem Thema mit. Der Name ändert auch den Ordnernamen auf der Festplatte.',
    'Копия темы целиком, вместе с кадрами и шрифтами. Спросит имя. Оригинал не пострадает.': 'Vollständige Kopie des Themas, mit Bildern und Schriften. Fragt nach einem Namen. Das Original bleibt unangetastet.',
    'Упаковать тему в один файл, чтобы переслать. Всё, на что она ссылается, попадёт внутрь.': 'Thema zum Versenden in eine Datei packen. Alles, worauf es verweist, kommt mit hinein.',
    'Картинка для показа: ночь и день рядом, с именем, автором и списком умений. Чтобы выложить или прислать.': 'Vorschaubild: Nacht und Tag nebeneinander, mit Name, Autor und Funktionsliste. Zum Teilen oder Versenden.',
    'Убрать тему из витрины. Папка остаётся на диске и переименовывается с точки — вернуть можно в проводнике.': 'Thema aus der Übersicht entfernen. Der Ordner bleibt auf der Festplatte und wird mit einem Punkt umbenannt — im Explorer wiederherstellbar.',
    'Новая тема': 'Neues Thema',
    'Как её назвать?': 'Wie soll es heißen?',
    'Переименовать тему': 'Thema umbenennen',
    'Новое название:': 'Neuer Name:',
    'Копия темы': 'Themenkopie',
    'Как назвать копию?': 'Wie soll die Kopie heißen?',
    'Копирую тему': 'Thema wird kopiert',
    ' — копия': ' — Kopie',
    'Скопировать': 'Kopieren',
    'Создать': 'Erstellen',
    'Отмена': 'Abbrechen',
    'Сохранить': 'Speichern',
    'Упаковываю тему': 'Thema wird gepackt',
    'Упаковать тему': 'Thema packen',
    'Куда упаковать тему': 'Wohin das Thema gepackt werden soll',
    'Архив с темой': 'Themenarchiv',
    'Папка с темой': 'Themenordner',
    'В папке нет описания темы.': 'Im Ordner fehlt die Themenbeschreibung.',
    'Распаковываю тему': 'Thema wird entpackt',
    'Открыть архив': 'Archiv öffnen',
    'Тема добавлена. Открыть её?': 'Thema hinzugefügt. Jetzt öffnen?',
    'Картинка для показа': 'Vorschaubild',
    'Убрать тему': 'Thema entfernen',
    'Эта тема сейчас открыта. Откройте другую и попробуйте снова.': 'Dieses Thema ist gerade geöffnet. Öffne ein anderes und versuch es erneut.',
    'Убрать «{}» из витрины?\n\nПапка останется на диске — она просто получит точку в начале имени. Вернуть можно переименованием в проводнике.': '„{}“ aus der Übersicht entfernen?\n\nDer Ordner bleibt auf der Festplatte — er bekommt nur einen Punkt vor dem Namen. Im Explorer kannst du ihn durch Umbenennen wiederherstellen.',
    'Готово, файлов внутри: {}.\n{}\n\nПоказать в папке?': 'Fertig, Dateien darin: {}.\n{}\n\nIm Ordner anzeigen?',
    'Готово:\n{}\n\nОткрыть копию?': 'Fertig:\n{}\n\nKopie öffnen?',
    'Готово:\n{}\n\nОткрыть её?': 'Fertig:\n{}\n\nÖffnen?',
    'Описание темы': 'Themenbeschreibung',
    'Что увидят другие': 'Was andere sehen',
    'эти строки уедут вместе с темой': 'diese Angaben reisen mit dem Thema mit',
    'Название': 'Name',
    'Автор': 'Autor',
    'Описание': 'Beschreibung',
    '{} из {}   {}': '{} von {}   {}',
    'имя не может быть пустым': 'der Name darf nicht leer sein',
    'в архиве нет описания темы': 'im Archiv fehlt die Themenbeschreibung',
    'без названия': 'ohne Namen',
    'тема': 'Thema',
    'День и ночь': 'Tag und Nacht',
    'Картинки': 'Bilder',
    'Движение': 'Bewegung',
    'Погода': 'Wetter',
    'Видео': 'Grafik',
    'Процессор': 'Prozessor',
    'Осмотр машины': 'Rechner-Check',
    'что на этой машине есть, что отвечает и чего не хватает': 'was dieser Rechner hat, was antwortet und was fehlt',
    'Что на этой машине': 'Was dieser Rechner hat',
    'те же проверки, что делает start.bat перед первым запуском. Опрос датчиков занимает несколько секунд.': 'dieselben Prüfungen wie start.bat vor dem ersten Start. Das Abfragen der Sensoren dauert ein paar Sekunden.',
    'что на этой машине отвечает, а что молчит. Опрос датчиков занимает несколько секунд.': 'was auf diesem Rechner antwortet und was stumm bleibt. Das Abfragen der Sensoren dauert ein paar Sekunden.',
    'Осмотреть': 'Prüfen',
    '  смотрю…': '  prüfe…',
    'Осмотр ещё не делался.': 'Noch nicht geprüft.',
    'всё в порядке': 'alles in Ordnung',
    'важных замечаний: {}': 'wichtige Hinweise: {}',
    'команда в буфере обмена': 'Befehl in der Zwischenablage',
    'не вышло': 'hat nicht geklappt',
    'Оформление программы': 'Programmdesign',
    'Единицы и время': 'Einheiten und Zeit',
    'Сборка кадра': 'Bildaufbau',
    'это про машину, а не про тему: настройка остаётся при смене темы': 'das betrifft den Rechner, nicht das Thema: die Einstellung bleibt beim Themenwechsel erhalten',
    'В один поток': 'Ein Thread',
    'В два потока': 'Zwei Threads',
    'В четыре': 'Vier Threads',
    'Пусть решит сама': 'Automatisch entscheiden',
    'Кадр собирается кусками, и куски друг о друге не знают — их можно готовить разом. Картинка выходит та же до последней точки, проверено. Но выигрыш во времени невелик и на быстрой машине теряется в разбросе: если панель и так укладывается в отпущенное время, кадров в секунду не прибавится. Смысл — уложиться на слабой машине.': 'Ein Bild wird stückweise zusammengesetzt, und die Teile wissen nichts voneinander — sie lassen sich gleichzeitig vorbereiten. Das Bild kommt bis auf den letzten Punkt gleich heraus, das ist geprüft. Der Zeitgewinn ist aber gering und geht auf einem schnellen Rechner in der Schwankung unter: Wenn das Panel die vorgegebene Zeit ohnehin einhält, gibt es nicht mehr Bilder pro Sekunde. Der Sinn liegt darin, es auf einem schwachen Rechner zu schaffen.',
    'в чём показывать градусы, время и дату — и в окне, и на экране': 'in welcher Form Grad, Uhrzeit und Datum angezeigt werden — im Fenster und auf dem Bildschirm',
    'Градусы': 'Grad',
    'Ветер': 'Wind',
    'и в окне, и в надписях на экране': 'im Fenster und in den Beschriftungen auf dem Bildschirm',
    'и температура железа, и погода': 'sowohl Hardwaretemperatur als auch Wetter',
    'Цельсий': 'Celsius',
    'Фаренгейт': 'Fahrenheit',
    'Часы': 'Uhr',
    'двенадцать часов дописывают AM и PM': 'bei zwölf Stunden werden AM und PM angehängt',
    '24 часа': '24 Stunden',
    '12 часов': '12 Stunden',
    'Порядок чисел в дате': 'Reihenfolge im Datum',
    'день, месяц и год': 'Tag, Monat und Jahr',
    'Неделя начинается': 'Woche beginnt',
    'по этому дню тема считает номер дня': 'nach diesem Tag zählt das Thema die Tagesnummer',
    'с понедельника': 'am Montag',
    'с воскресенья': 'am Sonntag',
    'Как это будет выглядеть': 'So sieht es aus',
    'по умолчанию всё берётся из самой Windows: какие единицы и форматы там выбраны, такие и здесь': 'standardmäßig wird alles aus Windows übernommen: welche Einheiten und Formate dort gewählt sind, gelten auch hier',
    'Тема может брать готовые {time}, {date} и {deg} — они идут по этой настройке. А может писать свой вид через {now:…} — тогда настройка его не тронет.': 'Ein Thema kann die fertigen {time}, {date} und {deg} verwenden — sie folgen dieser Einstellung. Oder es schreibt sein eigenes Format über {now:…} — dann bleibt die Einstellung ohne Wirkung.',
    'Запуск': 'Start',
    'Датчики': 'Sensoren',
    'Погода и адрес': 'Wetter und Ort',
    'Производительность': 'Leistung',
    'О программе': 'Über das Programm',
    'кто это написал и на каких условиях этим можно пользоваться': 'wer das geschrieben hat und unter welchen Bedingungen man es nutzen darf',
    'как выглядит само окно программы, а не картинка на экране': 'wie das Programmfenster selbst aussieht, nicht das Bild auf dem Bildschirm',
    'что делать при включении компьютера и при закрытии окна': 'was beim Hochfahren des Rechners und beim Schließen des Fensters passiert',
    'откуда берутся значения и что из этого читается сейчас': 'woher die Werte kommen und was davon gerade gelesen wird',
    'чем платим за плавность: памятью, процессором, качеством': 'was Flüssigkeit kostet: Arbeitsspeicher, Prozessor, Qualität',
    'откуда брать прогноз, восход и закат': 'woher Vorhersage, Sonnenauf- und -untergang kommen',
    'Светлое или тёмное': 'Hell oder dunkel',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за темой панели.': '„Wie in Windows“ folgt dem Systemdesign, „Wie auf dem Bildschirm“ folgt dem Panel-Design.',
    'Как на экране': 'Wie auf dem Bildschirm',
    'Светлое': 'Hell',
    'Тёмное': 'Dunkel',
    'Язык': 'Sprache',
    'Смена языка': 'Sprachwechsel',
    'В теме есть несохранённые правки. Сохранить их?': 'Das Thema hat ungespeicherte Änderungen. Jetzt speichern?',
    'Изменения применятся при следующем запуске.': 'Die Änderungen gelten ab dem nächsten Start.',
    'Ярлык на рабочем столе': 'Verknüpfung auf dem Desktop',
    'чтобы запускать не из папки, а с рабочего стола': 'damit du es vom Desktop statt aus dem Ordner starten kannst',
    'Не получилось. Рабочий стол может быть закрыт для записи.': 'Hat nicht geklappt. Der Desktop ist eventuell schreibgeschützt.',
    'Запускать вместе с Windows': 'Mit Windows starten',
    'через app.bat, чтобы поднялись права на температуру': 'über app.bat, damit die Rechte für die Temperatur gesetzt werden',
    'Язык темы': 'Themensprache',
    'Как в окне': 'Wie im Fenster',
    'на нём говорит панель на экране водянки: погода, подпись ветра, названия слоёв в редакторе': 'in dieser Sprache spricht das Panel auf dem Wasserkühlungs-Bildschirm: Wetter, Windbeschriftung, Ebenennamen im Editor',
    'Запускать при входе в систему': 'Bei der Anmeldung starten',
    'записью .desktop в автозапуске': 'über einen .desktop-Eintrag im Autostart',
    'Открывать сразу свёрнутым в трей': 'Direkt im Tray minimiert starten',
    'окно не мешает, панель работает': 'das Fenster stört nicht, das Panel läuft weiter',
    'Сразу включать экран': 'Bildschirm sofort einschalten',
    'не нажимать кнопку каждый раз': 'ohne jedes Mal den Knopf zu drücken',
    'Крестик прячет в трей, а не закрывает': 'Das Schließen-Kreuz legt ins Tray, statt zu beenden',
    'иначе панель погаснет вместе с окном': 'sonst erlischt das Panel zusammen mit dem Fenster',
    'Автозапуск': 'Autostart',
    'Не удалось изменить запись в реестре.': 'Der Registrierungseintrag konnte nicht geändert werden.',
    'Что опрашивать': 'Was abgefragt wird',
    'выключенный источник не опрашивается вообще — это и есть экономия': 'eine ausgeschaltete Quelle wird gar nicht erst abgefragt — das spart Ressourcen',
    'Что читается прямо сейчас': 'Was gerade gelesen wird',
    'значения как есть, до перевода в выбранные единицы: температуры здесь всегда в Цельсиях, на них настраивается реакция слоёв': 'die Rohwerte, vor der Umrechnung in die gewählten Einheiten: Temperaturen sind hier immer in Celsius, darauf reagieren die Ebenen',
    'Процессор, память, диски, сеть': 'Prozessor, Speicher, Laufwerke, Netzwerk',
    'почти бесплатно': 'so gut wie kostenlos',
    'Видеокарта': 'Grafikkarte',
    'через nvidia-smi': 'über nvidia-smi',
    'Температуры': 'Temperaturen',
    'нужны права администратора': 'Administratorrechte nötig',
    'их отдаёт само ядро': 'die liefert der Kernel selbst',
    'через nvidia-smi или /sys/class/drm': 'über nvidia-smi oder /sys/class/drm',
    'Погода, восход и закат': 'Wetter, Sonnenauf- und -untergang',
    'нужен интернет': 'Internet nötig',
    'Место': 'Ort',
    'по нему берётся прогноз, а заодно время восхода и заката — от них панель светлеет и темнеет': 'danach richtet sich die Vorhersage sowie Sonnenauf- und -untergang — davon hängt ab, wann das Panel heller und dunkler wird',
    'Название города на любом языке. Нажми «Найти» и выбери из списка.': 'Stadtname in jeder Sprache. Drück auf „Suchen“ und wähl aus der Liste.',
    'Найти': 'Suchen',
    'По адресу в сети': 'Über eine Netzwerkadresse',
    'Выбрать это место': 'Diesen Ort wählen',
    '  ищу…': '  suche…',
    '  ничего не нашлось': '  nichts gefunden',
    '  не вышло: {}': '  fehlgeschlagen: {}',
    'место: {}': 'Ort: {}',
    'Сейчас: {}   ({:.3f}, {:.3f}) {}': 'Jetzt: {}   ({:.3f}, {:.3f}) {}',
    'Место не выбрано — прогноза не будет, а восход и закат возьмутся запасные: 07:00 и 20:00.': 'Kein Ort gewählt — es gibt keine Vorhersage, und für Sonnenauf- und -untergang gelten die Standardwerte 07:00 und 20:00.',
    '«Как в Windows» следит за оформлением системы, «Как на экране» — за тем, день сейчас на панели или ночь.': '„Wie in Windows“ folgt dem Systemdesign, „Wie auf dem Bildschirm“ folgt davon, ob das Panel gerade Tag oder Nacht zeigt.',
    'Сейчас: {}   ({:.3f}, {:.3f})\n{}': 'Jetzt: {}   ({:.3f}, {:.3f})\n{}',
    'ночь': 'Nacht',
    'и день': 'und Tag',
    'Проверить, как тема выглядит в дождь или метель, можно на главной — ряд справа от выбора дня и ночи.': 'Wie das Thema bei Regen oder Schneesturm aussieht, siehst du auf der Startseite — die Reihe rechts neben der Tag/Nacht-Wahl.',
    'Источник прогноза': 'Vorhersagequelle',
    'Без ключа и без регистрации': 'Ohne Schlüssel, ohne Anmeldung',
    'По ключу службы': 'Mit Dienst-Schlüssel',
    'свой источник': 'eigene Quelle',
    'Где что лежит в ответе': 'Wo was in der Antwort steht',
    'В адресе можно писать {lat}, {lon} и {key} — программа подставит место и ключ. Нажмите «Спросить службу»: ответ разберётся на пути, и останется выбрать нужные из списков.': 'In die Adresse kannst du {lat}, {lon} und {key} schreiben — das Programm setzt Ort und Schlüssel ein. Klick auf „Dienst abfragen“: Die Antwort wird in Pfade zerlegt, und du wählst die passenden aus den Listen.',
    'Спросить службу': 'Dienst abfragen',
    'Температура': 'Temperatur',
    'Состояние погоды числом': 'Wetterzustand als Zahl',
    'Ощущается как': 'Gefühlt wie',
    'Влажность': 'Luftfeuchtigkeit',
    'Минимум за сутки': 'Tagestief',
    'Максимум за сутки': 'Tageshoch',
    'Восход': 'Aufgang',
    'Закат': 'Untergang',
    'Ветер в': 'Wind in',
    'Восход записан как': 'Aufgang wird geschrieben als',
    'iso — 2026-08-13T05:08, unix — число секунд, 12h — 05:08 AM, 24h — 05:08': 'iso — 2026-08-13T05:08, unix — Anzahl Sekunden, 12h — 05:08 AM, 24h — 05:08',
    'Числа состояния': 'Zustandszahlen',
    'wmo — служба уже отдаёт коды по стандарту ВМО. Своя таблица чисел прописывается в weather.json, см. справочник.': 'wmo — der Dienst liefert bereits Codes nach dem WMO-Standard. Eine eigene Zahlentabelle trägst du in weather.json ein, siehe Referenz.',
    'служба ответила, полей нашлось: {}. Выберите нужные из списков и нажмите «Проверить».': 'Der Dienst hat geantwortet, gefundene Felder: {}. Wähl die passenden aus den Listen und klick auf „Prüfen“.',
    'Впишите адрес службы.': 'Adresse des Dienstes eintragen.',
    'по умолчанию Open-Meteo: без ключа и без регистрации. Другие службы отвечают по-своему, поэтому у каждой свой переходник — выберите нужную, и программа сама переведёт её ответ в понятный панели вид.': 'standardmäßig Open-Meteo: ohne Schlüssel, ohne Anmeldung. Andere Dienste antworten auf ihre eigene Art, deshalb hat jeder seinen eigenen Adapter — wähl den passenden, und das Programm übersetzt die Antwort selbst in ein für das Panel verständliches Format.',
    'Ключ': 'Schlüssel',
    'Ключ выдаёт сама служба при регистрации. Он хранится в weather.json рядом с программой.': 'Den Schlüssel bekommst du beim Dienst selbst, bei der Anmeldung. Er wird in weather.json neben dem Programm gespeichert.',
    'Адрес': 'Adresse',
    'Пусто — обычный адрес выбранной службы. Свой нужен для зеркала или своего сервера: полный адрес без вопросов и параметров, их программа допишет сама.': 'Leer bedeutet die übliche Adresse des gewählten Dienstes. Eine eigene brauchst du für einen Spiegelserver oder eigenen Server: die vollständige Adresse ohne Fragezeichen und Parameter, die fügt das Programm selbst hinzu.',
    'Проверить': 'Prüfen',
    'Обычный': 'Standard',
    '  спрашиваю…': '  frage an…',
    'Сначала выберите место — без него спрашивать не о чем.': 'Wähl zuerst einen Ort — ohne ihn gibt es nichts abzufragen.',
    '{} отвечает: {}, {:.0f} {}, ветер {:.0f} {}. Записано.': '{} antwortet: {}, {:.0f} {}, Wind {:.0f} {}. Gespeichert.',
    '\nВосхода и заката эта служба не даёт — считаем их сами по координатам.': '\nSonnenauf- und -untergang liefert dieser Dienst nicht — wir berechnen sie selbst aus den Koordinaten.',
    'Не отвечает или отвечает не тем: {}': 'Antwortet nicht oder antwortet falsch: {}',
    'Картинка и нагрузка': 'Bild und Last',
    'эти значения хранятся внутри темы': 'diese Werte werden im Thema gespeichert',
    'Кадров в секунду': 'Bilder pro Sekunde',
    'ниже 0.5 нельзя: экран уснёт': 'nicht unter 0.5: sonst schläft der Bildschirm ein',
    'Качество JPEG': 'JPEG-Qualität',
    '1–100, влияет на размер кадра': '1–100, beeinflusst die Bildgröße',
    'Сглаживание': 'Kantenglättung',
    '2 или 3, больше — плавнее края': '2 oder 3, mehr bedeutet weichere Kanten',
    'Переход день/ночь, секунд': 'Übergang Tag/Nacht, Sekunden',
    'сколько длится смена вида': 'wie lange der Ansichtswechsel dauert',
    'Сжимать кадры фона в памяти': 'Hintergrundbilder im Speicher komprimieren',
    'Сжатие без потерь: картинка та же до последнего бита, памяти уходит втрое меньше. Плата — около семи десятых миллисекунды на кадр. Переключение заставляет заново разобрать все кадры фона: на тяжёлой теме экран замрёт на несколько секунд.': 'Verlustfreie Kompression: Das Bild bleibt bis zum letzten Bit gleich, braucht aber dreimal weniger Speicher. Der Preis dafür sind rund sieben Zehntel Millisekunden pro Bild. Beim Umschalten werden alle Hintergrundbilder neu aufbereitet: Bei einem aufwendigen Thema bleibt der Bildschirm dabei ein paar Sekunden stehen.',
    '      сейчас программа занимает {:.0f} МБ': '      das Programm belegt gerade {:.0f} MB',
    'Экран выключен': 'Bildschirm ist aus',
    'Включите вывод на главной — здесь будет видно, сколько кадров получается на самом деле.': 'Schalte die Ausgabe auf der Startseite ein — hier siehst du dann, wie viele Bilder tatsächlich ankommen.',
    'Задано {:g}, выходит {:.1f} кадр/с': 'Eingestellt {:g}, erreicht {:.1f} Bilder/s',
    'Только запустились, счёт ещё набирается.': 'Gerade erst gestartet, die Zählung läuft noch.',
    'Успевает.': 'Kommt mit.',
    'Не успевает: {:.0f} %. Упирается либо в отрисовку — тогда помогут меньше сглаживание и меньше живых слоёв, — либо в канал до экрана: тогда снижайте качество JPEG, кадр станет легче.': 'Kommt nicht hinterher: {:.0f} %. Entweder bremst das Zeichnen — dann helfen weniger Kantenglättung und weniger lebendige Ebenen —, oder die Verbindung zum Bildschirm: dann die JPEG-Qualität senken, damit das Bild leichter wird.',
    'версия {} · автор {}': 'Version {} · von {}',
    'Открытая замена штатной программе для экрана водянки: контроллер TXW818, панель ST7701S, 960x480 по COM-порту.': 'Offener Ersatz für die Standardsoftware eines Wasserkühlungs-Bildschirms: Controller TXW818, Panel ST7701S, 960x480 über COM-Port.',
    'Лицензия': 'Lizenz',
    'Пользоваться, копировать и переделывать — можно.': 'Nutzen, kopieren und verändern — erlaubt.',
    'Зарабатывать на этом — нельзя.': 'Geld damit verdienen — nicht erlaubt.',
    'Переделанное раздавать на тех же условиях и с указанием автора.': 'Veränderte Fassungen unter denselben Bedingungen und mit Namensnennung weitergeben.',
    'Условия распространяются и на программу, и на темы, которые с ней идут. Про коммерческое использование договариваются с автором письменно.': 'Die Bedingungen gelten für das Programm und für die mitgelieferten Themen. Über kommerzielle Nutzung wird schriftlich mit dem Autor vereinbart.',
    'Открыть файл лицензии': 'Lizenzdatei öffnen',
    'Полный текст в сети': 'Vollständiger Text online',
    'Файла LICENSE нет рядом с программой.': 'Die Datei LICENSE liegt nicht neben dem Programm.',
    '      Наш файл — пересказ для человека. Юридическую силу имеет полный текст на сайте Creative Commons.': '      Unsere Datei ist eine Zusammenfassung in einfachen Worten. Rechtlich verbindlich ist nur der vollständige Text auf der Creative-Commons-Website.',
    'Чужое': 'Fremdes',
    'Температуры читает LibreHardwareMonitor — четыре файла .dll рядом с программой. Библиотека принадлежит своим авторам и идёт по своей лицензии, MPL 2.0.': 'Temperaturen liest LibreHardwareMonitor — vier .dll-Dateien neben dem Programm. Die Bibliothek gehört ihren eigenen Autoren und steht unter ihrer eigenen Lizenz, MPL 2.0.',
    'Не удалось открыть файл: {}': 'Datei konnte nicht geöffnet werden: {}',
    'Загрузка процессора, %': 'Prozessorauslastung, %',
    'Температура процессора': 'Prozessortemperatur',
    'Частота процессора, ГГц': 'Prozessortakt, GHz',
    'Потребление процессора, Вт': 'Prozessorverbrauch, W',
    'Обороты вентилятора ЦП': 'Drehzahl des CPU-Lüfters',
    'Загрузка видеокарты, %': 'Grafikkartenauslastung, %',
    'Температура видеокарты': 'Grafikkartentemperatur',
    'Потребление видеокарты, Вт': 'Grafikkartenverbrauch, W',
    'Загрузка видеопамяти, %': 'Grafikspeicherauslastung, %',
    'Занято видеопамяти, ГБ': 'Belegter Grafikspeicher, GB',
    'Частота видеокарты, МГц': 'Grafikkartentakt, MHz',
    'Вентилятор видеокарты, %': 'Grafikkartenlüfter, %',
    'Загрузка ОЗУ, %': 'RAM-Auslastung, %',
    'Занято ОЗУ, ГБ': 'Belegter RAM, GB',
    'Свободно ОЗУ, ГБ': 'Freier RAM, GB',
    'Загрузка диска, %': 'Laufwerksauslastung, %',
    'Свободно на диске, ГБ': 'Freier Speicherplatz, GB',
    'Приём из сети, МБ/с': 'Netzwerk-Empfang, MB/s',
    'Отдача в сеть, МБ/с': 'Netzwerk-Sendung, MB/s',
    'Температура платы': 'Mainboard-Temperatur',
    'Погода: температура': 'Wetter: Temperatur',
    'Погода: ощущается как': 'Wetter: gefühlt wie',
    'Погода: влажность, %': 'Wetter: Luftfeuchtigkeit, %',
    'Погода: ветер, км/ч': 'Wetter: Wind, km/h',
    '— свой текст —': '— eigener Text —',
    'Загрузка процессора  23%': 'Prozessorauslastung  23%',
    'Температура процессора  67 °C': 'Prozessortemperatur  67 °C',
    'Частота процессора  4.85 ГГц': 'Prozessortakt  4.85 GHz',
    'Потребление процессора  142 Вт': 'Prozessorverbrauch  142 W',
    'Загрузка видеокарты  41%': 'Grafikkartenauslastung  41%',
    'Температура видеокарты  51 °C': 'Grafikkartentemperatur  51 °C',
    'Потребление видеокарты  186 Вт': 'Grafikkartenverbrauch  186 W',
    'Видеопамять  9.9 ГБ': 'Grafikspeicher  9.9 GB',
    'Видеопамять  9.9 / 16 ГБ': 'Grafikspeicher  9.9 / 16 GB',
    'Загрузка ОЗУ  28%': 'RAM-Auslastung  28%',
    'ОЗУ  17.0 / 64 ГБ': 'RAM  17.0 / 64 GB',
    'Свободно на диске  231 ГБ': 'Freier Speicherplatz  231 GB',
    'Приём из сети  11.4 МБ/с': 'Netzwerk-Empfang  11.4 MB/s',
    'Отдача в сеть  2.3 МБ/с': 'Netzwerk-Sendung  2.3 MB/s',
    'Время работы  5ч 49м': 'Laufzeit  5 Std. 49 Min.',
    'Часы  как выбрано в настройках': 'Uhrzeit  wie in den Einstellungen gewählt',
    'Часы с секундами  как выбрано в настройках': 'Uhrzeit mit Sekunden  wie in den Einstellungen gewählt',
    'Дата  как выбрано в настройках': 'Datum  wie in den Einstellungen gewählt',
    'Дата коротко  как выбрано в настройках': 'Datum kurz  wie in den Einstellungen gewählt',
    'Погода: температура со знаком настройки  12 °C': 'Wetter: Temperatur in der gewählten Einheit  12 °C',
    'Часы  14:30': 'Uhrzeit  14:30',
    'Часы с секундами  14:30:45': 'Uhrzeit mit Sekunden  14:30:45',
    'Часы 12-часовые  02:30 PM': '12-Stunden-Uhrzeit  02:30 PM',
    'Часы 12-часовые с секундами  02:30:45 PM': '12-Stunden-Uhrzeit mit Sekunden  02:30:45 PM',
    'Дата  03.08.2026': 'Datum  03.08.2026',
    'Дата  03.08.26': 'Datum  03.08.26',
    'Дата  2026-08-03': 'Datum  2026-08-03',
    'Дата  03 August': 'Datum  03. August',
    'День недели  Monday': 'Wochentag  Monday',
    'Погода кратко  Дождь': 'Wetter kurz  Regen',
    'Погода подробно  Небольшой дождь': 'Wetter ausführlich  Leichter Regen',
    'Погода и температура  Дождь  12 °C': 'Wetter und Temperatur  Regen  12 °C',
    'Погода подробно и температура': 'Wetter ausführlich und Temperatur',
    'Погода: только температура  12 °C': 'Wetter: nur Temperatur  12 °C',
    'Погода: ощущается как  10 °C': 'Wetter: gefühlt wie  10 °C',
    'Погода: минимум и максимум  8…15 °C': 'Wetter: Tief und Hoch, nur Zahlen',
    'Погода: ветер  4 км/ч': 'Wetter: Wind  4 km/h',
    'Погода: влажность  78 %': 'Wetter: Luftfeuchtigkeit  78 %',
    'Погода: город и температура': 'Wetter: Stadt und Temperatur',
    'Погода: всё вместе': 'Wetter: alles zusammen',
    'по центру': 'mittig',
    'слева, по середине': 'links, mittig',
    'справа, по середине': 'rechts, mittig',
    'слева сверху': 'oben links',
    'по центру сверху': 'oben mittig',
    'справа сверху': 'oben rechts',
    'слева снизу': 'unten links',
    'по центру снизу': 'unten mittig',
    'справа снизу': 'unten rechts',
    'слева направо': 'von links nach rechts',
    'справа налево': 'von rechts nach links',
    'снизу вверх': 'von unten nach oben',
    'сверху вниз': 'von oben nach unten',
    'сверху': 'oben',
    'снизу': 'unten',
    'слева': 'links',
    'справа': 'rechts',
    'заполнить с обрезкой': 'füllen und zuschneiden',
    'вписать целиком': 'ganz einpassen',
    'растянуть': 'strecken',
    'как есть': 'wie es ist',
    'нет': 'kein',
    'по диагонали': 'diagonal',
    'текст': 'Text',
    'прямоугольник': 'Rechteck',
    'квадрат': 'Quadrat',
    'овал': 'Ellipse',
    'круг': 'Kreis',
    'линия': 'Linie',
    'стрелка': 'Pfeil',
    'звезда': 'Stern',
    'полоса': 'Balken',
    'кольцо': 'Ring',
    'картинка': 'Bild',
    'туда-обратно': 'hin und her',
    'по кругу': 'im Kreis',
    'затухание': 'Verblassen',
    'движение': 'Bewegung',
    'поворот': 'Drehung',
    'цвет': 'Farbe',
    'размер': 'Größe',
    'Arial обычный': 'Arial normal',
    'Arial жирный': 'Arial fett',
    'Segoe UI обычный': 'Segoe UI normal',
    'Segoe UI жирный': 'Segoe UI fett',
    'Consolas обычный': 'Consolas normal',
    'Consolas жирный': 'Consolas fett',
    'Tahoma обычный': 'Tahoma normal',
    'Tahoma жирный': 'Tahoma fett',
    'Verdana обычный': 'Verdana normal',
    'Verdana жирный': 'Verdana fett',
    'Calibri обычный': 'Calibri normal',
    'Calibri жирный': 'Calibri fett',
    'Искать по названию, типу и тексту слоя. Рядом — показывать все слои, только видимые ночью или только днём.': 'Suche nach Name, Typ und Text der Ebene. Daneben: alle Ebenen anzeigen, nur die nachts sichtbaren oder nur die tagsüber sichtbaren.',
    'Подпись для себя, в списке слева. На картинку не влияет.': 'Eine Notiz nur für dich, in der Liste links. Sie wirkt sich nicht auf das Bild aus.',
    'Отступ слева, в точках. Начало координат — левый верхний угол.': 'Abstand von links, in Punkten. Der Koordinatenursprung liegt oben links.',
    'Отступ сверху, в точках.': 'Abstand von oben, in Punkten.',
    'Куда линия приходит по горизонтали.': 'Wo die Linie horizontal endet.',
    'Куда линия приходит по вертикали.': 'Wo die Linie vertikal endet.',
    'Наклон слоя в градусах, по часовой стрелке.': 'Neigung der Ebene in Grad, im Uhrzeigersinn.',
    'Растянуть слой вширь. 1 — как есть, 2 — вдвое шире.': 'Ebene in die Breite strecken. 1 bedeutet unverändert, 2 doppelt so breit.',
    'Растянуть слой ввысь. 1 — как есть, 0.5 — вдвое ниже.': 'Ebene in die Höhe strecken. 1 bedeutet unverändert, 0.5 halb so hoch.',
    'Насколько слой прозрачен: 0 — не видно совсем, 1 — плотно.': 'Wie durchsichtig die Ebene ist: 0 bedeutet unsichtbar, 1 bedeutet deckend.',
    'Что написать. В фигурных скобках подставляются показания: {cpu_load:.0f}% даст «37%».': 'Was geschrieben wird. In geschweiften Klammern stehen Messwerte: {cpu_load:.0f}% ergibt „37%“.',
    'Готовые надписи: часы, дата, погода, загрузка. Выбери — и текст подставится сам.': 'Vorgefertigte Beschriftungen: Uhrzeit, Datum, Wetter, Auslastung. Wähl eine aus — der Text wird automatisch eingesetzt.',
    'Файл шрифта. Любой из системы или положенный рядом с темой.': 'Schriftdatei. Eine beliebige aus dem System oder eine, die neben dem Thema liegt.',
    'Высота букв в точках.': 'Buchstabenhöhe in Punkten.',
    'Влезть в ширину': 'In die Breite einpassen',
    'Влезть в столько точек по ширине. Длинная надпись сама уменьшится, короткая останется как есть. 0 — не ужимать, тогда длинное уедет за край.': 'In so viele Punkte Breite einpassen. Eine lange Beschriftung wird automatisch verkleinert, eine kurze bleibt, wie sie ist. 0 bedeutet nicht verkleinern — dann läuft ein langer Text über den Rand hinaus.',
    'Цвет букв.': 'Buchstabenfarbe.',
    'За какую точку слой держится координатами. По центру — удобно для цифр, что меняют длину.': 'An welchem Punkt die Ebene an den Koordinaten hängt. Mittig eignet sich gut für Zahlen, die ihre Länge ändern.',
    'Цвет обводки. Помогает читать надпись поверх пёстрой картинки.': 'Umrisslinienfarbe. Sie hilft, die Beschriftung über einem unruhigen Bild besser zu lesen.',
    'Толщина обводки букв в точках.': 'Dicke der Buchstabenumrandung in Punkten.',
    'Ширина слоя в точках.': 'Breite der Ebene in Punkten.',
    'Высота слоя в точках.': 'Höhe der Ebene in Punkten.',
    'Скругление углов. 0 — прямые углы.': 'Eckenrundung. 0 bedeutet rechtwinklige Ecken.',
    'Основной цвет заливки.': 'Haupt-Füllfarbe.',
    'Второй цвет: заливка станет переходом от первого ко второму.': 'Zweite Farbe: Die Füllung wird zu einem Verlauf von der ersten zur zweiten Farbe.',
    'В какую сторону идёт переход между двумя цветами.': 'In welche Richtung der Verlauf zwischen den beiden Farben geht.',
    'Толщина линии или окантовки в точках.': 'Dicke der Linie oder des Rands in Punkten.',
    'Откуда берётся число: загрузка, температура, погода.': 'Woher die Zahl kommt: Auslastung, Temperatur, Wetter.',
    'Какому значению соответствует пустая полоса или дуга.': 'Bei welchem Wert der Balken oder Bogen leer ist.',
    'Какому значению соответствует полная полоса или дуга.': 'Bei welchem Wert der Balken oder Bogen voll ist.',
    'В какую сторону растёт заполнение.': 'In welche Richtung sich die Füllung ausbreitet.',
    'Цвет незаполненной части. Можно не задавать.': 'Farbe des ungefüllten Teils. Kann leer bleiben.',
    'Радиус в точках. Координаты — это центр, а не угол.': 'Radius in Punkten. Die Koordinaten sind der Mittelpunkt, nicht eine Ecke.',
    'Радиус впадин между лучами звезды.': 'Radius der Einbuchtungen zwischen den Zacken des Sterns.',
    'Сколько лучей у звезды.': 'Wie viele Zacken der Stern hat.',
    'Повернуть звезду на столько градусов.': 'Den Stern um so viele Grad drehen.',
    'Толщина дуги в точках.': 'Dicke des Bogens in Punkten.',
    'С какой стороны у кольца вырез.': 'Auf welcher Seite der Ring einen Ausschnitt hat.',
    'Ширина выреза в градусах. 60 — небольшой, 180 — половина круга.': 'Breite des Ausschnitts in Grad. 60 ist klein, 180 ist ein halber Kreis.',
    'Заполнять дугу с другого конца, навстречу обычному.': 'Den Bogen vom anderen Ende her füllen, entgegen der üblichen Richtung.',
    'Скруглить концы — дуга или линия смотрится мягче.': 'Enden abrunden — der Bogen oder die Linie wirkt dadurch weicher.',
    'Размер наконечника стрелки в точках.': 'Größe der Pfeilspitze in Punkten.',
    'Файл картинки или папка с кадрами. Папка листается как ролик.': 'Bilddatei oder Ordner mit Einzelbildern. Ein Ordner läuft ab wie ein Clip.',
    'Что делать, если картинка не совпала с отведённым местом.': 'Was passiert, wenn das Bild nicht in den vorgesehenen Platz passt.',
    'Своя частота листания кадров. Ставь ту, с которой резал ролик, иначе он поедет быстрее или медленнее задуманного.': 'Eigene Bildwechselrate. Stell die ein, mit der der Clip geschnitten wurde, sonst läuft er schneller oder langsamer als vorgesehen.',
    'Включи, если PNG выгружены из DaVinci: там цвет уже умножен на прозрачность, и без этого по мягкому краю пойдёт тёмная каёмка.': 'Aktivieren, wenn die PNGs aus DaVinci exportiert wurden: Dort ist die Farbe bereits mit der Transparenz multipliziert, und ohne diese Option entsteht an weichen Kanten ein dunkler Saum.',
    'Поднять непрозрачность, если объект вырезался полупрозрачным и выглядит блёклым. 1 — не трогать, 1.5 — заметно плотнее.': 'Deckkraft erhöhen, wenn das Objekt halbtransparent freigestellt wurde und blass wirkt. 1 bedeutet unverändert, 1.5 spürbar kräftiger.',
    'Поворот, °': 'Drehung, °',
    'Шире': 'Breiter',
    'Выше': 'Höher',
    'Прозрачность': 'Transparenz',
    'Второй цвет': 'Zweite Farbe',
    'Переход цвета': 'Farbverlauf',
    'Готовая надпись': 'Vorgefertigte Beschriftung',
    'Текст': 'Text',
    'Шрифт': 'Schriftart',
    'Размер': 'Größe',
    'Цвет': 'Farbe',
    'Держится за': 'Ankerpunkt',
    'Обводка': 'Umrandung',
    'Толщина обводки': 'Umrandungsdicke',
    'Ширина': 'Breite',
    'Высота': 'Höhe',
    'Скругление': 'Rundung',
    'Заливка': 'Füllung',
    'Окантовка': 'Rand',
    'Толщина': 'Dicke',
    'Наконечник': 'Pfeilspitze',
    'Мягкие концы': 'Weiche Enden',
    'X конца': 'Ende X',
    'Y конца': 'Ende Y',
    'Радиус': 'Radius',
    'Радиус впадин': 'Innenradius',
    'Лучей': 'Zacken',
    'Наклон, °': 'Neigung, °',
    'Показание': 'Messwert',
    'Пусто при': 'Leer bei',
    'Полно при': 'Voll bei',
    'Направление': 'Richtung',
    'Цвет заполнения': 'Füllfarbe',
    'Цвет пустоты': 'Leerfarbe',
    'Толщина дуги': 'Bogendicke',
    'Вырез': 'Ausschnitt',
    'Вырез, °': 'Ausschnitt, °',
    'Наоборот': 'Umgekehrt',
    'Картинка': 'Bild',
    'Как вписать': 'Anpassung',
    'PNG из DaVinci': 'PNG aus DaVinci',
    'Плотнее': 'Kräftiger',
    'Что показывает': 'Was angezeigt wird',
    'Где и какого размера': 'Wo und wie groß',
    'Как выглядит': 'Wie es aussieht',
    'Прочее': 'Sonstiges',
    'новый текст': 'neuer Text',
    'новый прямоугольник': 'neues Rechteck',
    'новый квадрат': 'neues Quadrat',
    'новый овал': 'neue Ellipse',
    'новый круг': 'neuer Kreis',
    'новая линия': 'neue Linie',
    'новая стрелка': 'neuer Pfeil',
    'новая звезда': 'neuer Stern',
    'новая полоса': 'neuer Balken',
    'новое кольцо': 'neuer Ring',
    'новая картинка': 'neues Bild',
    'слой': 'Ebene',
    'блок': 'Block',
    ' копия': ' Kopie',
    '←  К темам': '←  Zu den Themen',
    'Сохранить как…': 'Speichern unter…',
    'Вернуть с диска': 'Von der Festplatte neu laden',
    'Открыть тему…': 'Thema öffnen…',
    'Описание темы…': 'Themenbeschreibung…',
    '●  Магнит': '●  Magnet',
    '○  Магнит': '○  Magnet',
    '●  Сетка {}': '●  Raster {}',
    '○  Сетка': '○  Raster',
    'Выровнять:': 'Ausrichten:',
    'К левому краю экрана': 'Zum linken Bildschirmrand',
    'По центру экрана вбок': 'Zur horizontalen Mitte des Bildschirms',
    'К правому краю экрана': 'Zum rechten Bildschirmrand',
    'К верхнему краю экрана': 'Zum oberen Bildschirmrand',
    'По центру экрана вниз': 'Zur vertikalen Mitte des Bildschirms',
    'К нижнему краю экрана': 'Zum unteren Bildschirmrand',
    'Размер:': 'Größe:',
    'Уменьшить выбранные слои на десятую часть': 'Die gewählten Ebenen um ein Zehntel verkleinern',
    'Увеличить выбранные слои на десятую часть': 'Die gewählten Ebenen um ein Zehntel vergrößern',
    '. Работает и на нескольких сразу: выдели их в списке с Ctrl или Shift.': '. Funktioniert auch mit mehreren zugleich: wähl sie in der Liste mit Strg oder Umschalt aus.',
    'Показать на экране': 'Auf dem Bildschirm anzeigen',
    'Остановить показ': 'Anzeige stoppen',
    'Слои · нижние перекрываются верхними': 'Ebenen · untere werden von oberen verdeckt',
    'все': 'alle',
    'день': 'Tag',
    'Скрыть': 'Ausblenden',
    'Копия': 'Kopie',
    'Удалить': 'Löschen',
    'Добавить:': 'Hinzufügen:',
    'Режим правки:': 'Bearbeitungsmodus:',
    'Ночной вид': 'Nachtansicht',
    'Переход': 'Übergang',
    'Дневной вид': 'Tagesansicht',
    'Прокрутка перехода:': 'Übergang durchscrollen:',
    'Двигается только выбранный слой. Стрелки — на пиксель, Shift+стрелки — на десять.\nМагнит притягивает к краям и центрам соседей; Alt при перетаскивании временно его отключает.\nНесколько слоёв разом: Ctrl+щелчок или Shift+щелчок в списке.\nCtrl+Z отменить · Ctrl+Y вернуть · Ctrl+C, Ctrl+V, Ctrl+D · Ctrl+S сохранить · Delete удалить': 'Es bewegt sich nur die gewählte Ebene. Pfeiltasten bewegen sie um ein Pixel, Umschalt+Pfeiltasten um zehn.\nDer Magnet zieht zu den Kanten und Mitten der Nachbarn; Alt beim Ziehen schaltet ihn vorübergehend aus.\nMehrere Ebenen zugleich: Strg+Klick oder Umschalt+Klick in der Liste.\nStrg+Z rückgängig · Strg+Y wiederholen · Strg+C, Strg+V, Strg+D · Strg+S speichern · Entf löschen',
    'Тип блока': 'Blocktyp',
    'Экран': 'Bildschirm',
    'Фон под всеми блоками:': 'Hintergrund unter allen Blöcken:',
    'Убрать дневной': 'Tag entfernen',
    'нет дневного — фон ночной круглые сутки': 'kein Tageshintergrund — der Nachthintergrund gilt rund um die Uhr',
    'Сжимать кадры фона': 'Hintergrundbilder komprimieren',
    'памяти вчетверо меньше, картинка та же': 'viermal weniger Speicher, dasselbe Bild',
    'кадры фона будут сжаты — готовлю заново': 'die Hintergrundbilder werden komprimiert — wird neu vorbereitet',
    'кадры фона будут распакованы — готовлю заново': 'die Hintergrundbilder werden entpackt — wird neu vorbereitet',
    'Здесь настраивается только движение.\nЧто именно меняется — задаётся\nв ночном и дневном видах.': 'Hier wird nur die Bewegung eingestellt.\nWas sich dabei ändert, wird\nin der Nacht- und Tagesansicht festgelegt.',
    'Правки уходят в дневной вид': 'Änderungen gehen in die Tagesansicht',
    'Сбросить': 'Zurücksetzen',
    'Переход к дневному виду': 'Übergang zur Tagesansicht',
    'настроен': 'eingerichtet',
    'не настроен': 'nicht eingerichtet',
    'Что меняется:': 'Was sich ändert:',
    'Отрезок перехода, %': 'Abschnitt des Übergangs, %',
    'Начало': 'Anfang',
    'Середина': 'Mitte',
    'Окончание': 'Ende',
    'Повтор по времени': 'Zeitliche Wiederholung',
    'Период, секунд': 'Periode, Sekunden',
    'Как повторять': 'Wie wiederholt wird',
    'Показать в момент': 'Zeitpunkt anzeigen',
    'сброс': 'zurücksetzen',
    'Реакция на датчик': 'Reaktion auf einen Messwert',
    'Датчик': 'Messwert',
    'Начинает меняться при': 'Beginnt sich zu ändern bei',
    'Полностью при': 'Vollständig bei',
    'Показать при значении': 'Anzeigen bei Wert',
    'отменять нечего': 'nichts rückgängig zu machen',
    'отменено': 'rückgängig gemacht',
    'возвращать нечего': 'nichts zu wiederholen',
    'возвращено': 'wiederholt',
    'слой скопирован': 'Ebene kopiert',
    'слой вырезан': 'Ebene ausgeschnitten',
    'в буфере нет слоя': 'in der Zwischenablage ist keine Ebene',
    'слой вставлен': 'Ebene eingefügt',
    'магнит включён': 'Magnet ist an',
    'магнит выключен': 'Magnet ist aus',
    'сетка выключена': 'Raster ist aus',
    'сетка по {} точек': 'Raster alle {} Punkte',
    'размер {:+.0f} % у {} слоёв': 'Größe {:+.0f} % bei {} Ebenen',
    'показано {} из {}': 'angezeigt {} von {}',
    'X {}  Y {}   (без магнита)': 'X {}  Y {}   (ohne Magnet)',
    'X {}  Y {}{}': 'X {}  Y {}{}',
    '   ({} слоёв)': '   ({} Ebenen)',
    'шрифт скопирован в папку fonts': 'Schriftart in den Ordner fonts kopiert',
    'не смог скопировать: {}': 'Kopieren fehlgeschlagen: {}',
    'переименовано, папка тоже': 'umbenannt, der Ordner ebenfalls',
    'папку переименовать не вышло: {}': 'Ordner konnte nicht umbenannt werden: {}',
    'описание изменено, не забудь сохранить': 'Beschreibung geändert, denk ans Speichern',
    'дневной вид блока сброшен': 'Tagesansicht des Blocks zurückgesetzt',
    'ошибка: {}': 'Fehler: {}',
    'сохранено': 'gespeichert',
    'открыто: ': 'geöffnet: ',
    'экран не найден': 'Bildschirm nicht gefunden',
    'показ прерван: {}': 'Anzeige unterbrochen: {}',
    '{} · редактор · {} — {}': '{} · Editor · {} — {}',
    'Удалить слой «{}»?': 'Ebene „{}“ löschen?',
    'Удалить выбранные слои ({} шт.)?': 'Gewählte Ebenen löschen ({} Stück)?',
    'Выбери файл шрифта': 'Schriftdatei auswählen',
    'Шрифты': 'Schriftarten',
    'Папка с кадрами (Отмена - выбрать файл)': 'Ordner mit Einzelbildern (Abbrechen, um eine Datei zu wählen)',
    'Открыть': 'Öffnen',
    'Вернуть': 'Neu laden',
    'Папка с темой (Отмена — выбрать файл)': 'Themenordner (Abbrechen, um eine Datei zu wählen)',
    'В папке нет файлов описания темы (.json).\n\nФайл темы должен лежать рядом с папками кадров.': 'Im Ordner gibt es keine Themendateien (.json).\n\nDie Themendatei muss neben den Ordnern mit den Einzelbildern liegen.',
    'Какой файл темы открыть': 'Welche Themendatei geöffnet werden soll',
    'Файл темы': 'Themendatei',
    'Описание панели': 'Panelbeschreibung',
    'Не удалось прочитать файл:\n{}': 'Datei konnte nicht gelesen werden:\n{}',
    'Это не похоже на тему: нет раздела layers.': 'Das sieht nicht nach einem Thema aus: Der Abschnitt layers fehlt.',
    'Тема ссылается на то, чего нет рядом с её файлом:\n\n  ': 'Das Thema verweist auf etwas, das nicht neben seiner Datei liegt:\n\n  ',
    '\n\nПеренеси эти папки в {}': '\n\nVerschiebe diese Ordner nach {}',
    'Не найден файл описания: {}': 'Beschreibungsdatei nicht gefunden: {}',
    'осмотр машины': 'Rechner-Check',
    '[д/н] ': '[j/n] ',
    'прервано': 'abgebrochen',
    'язык уже выбран': 'die Sprache ist bereits gewählt',
    'язык Windows подсказывал другой: {}': 'die Windows-Sprache legte eine andere nahe: {}',
    'язык выбран по языку Windows': 'die Sprache wurde von Windows übernommen',
    'поменять можно в Настройках -> Оформление программы': 'ändern lässt sich das in den Einstellungen -> Programmdesign',
    'Библиотеки': 'Bibliotheken',
    'сборка кадров и всё рисование': 'das Zusammensetzen der Bilder und das gesamte Zeichnen',
    'загрузка процессора, память, диски, сеть': 'Prozessorauslastung, Speicher, Laufwerke, Netzwerk',
    'разговор с экраном по COM-порту': 'die Kommunikation mit dem Bildschirm über den COM-Port',
    'само окно программы': 'das Programmfenster selbst',
    'температура процессора, видеокарты AMD и Intel': 'Prozessortemperatur, AMD- und Intel-Grafikkarten',
    'переходы цвета и мягкие края': 'Farbverläufe und weiche Kanten',
    'значок рядом с часами': 'das Symbol neben der Uhr',
    'переустанови Python, отметив «tcl/tk and IDLE»': 'installiere Python neu und aktiviere dabei „tcl/tk and IDLE“',
    'Поставить всё разом:': 'Alles auf einmal installieren:',
    'Без обязательных библиотек осматривать дальше нечего.': 'Ohne die erforderlichen Bibliotheken gibt es nichts weiter zu prüfen.',
    'Права': 'Rechte',
    'права администратора есть': 'Administratorrechte sind vorhanden',
    'прав администратора нет': 'keine Administratorrechte',
    'без них температуры процессора не будет вовсе': 'ohne sie gibt es überhaupt keine Prozessortemperatur',
    'запусти start.bat, а программу - через app.bat': 'starte start.bat, und das Programm selbst über app.bat',
    'Библиотека датчиков': 'Die Sensorbibliothek',
    'нет рядом с программой': 'nicht neben dem Programm',
    'возьми из архива LibreHardwareMonitor и положи сюда': 'nimm sie aus dem LibreHardwareMonitor-Archiv und leg sie hierher',
    'все четыре файла на месте': 'alle vier Dateien sind vorhanden',
    'снял пометку «из интернета»': 'die Markierung „aus dem Internet“ wurde entfernt',
    'помечен как скачанный из интернета': 'als aus dem Internet heruntergeladen markiert',
    'Свойства файла -> галочка «Разблокировать»': 'Dateieigenschaften -> Häkchen „Zulassen“',
    'пометки «из интернета» ни на одном нет': 'keine trägt die Markierung „aus dem Internet“',
    'Железо': 'Die Hardware',
    'процессор': 'Prozessor',
    'видеокарта': 'Grafikkarte',
    'название выяснить не удалось': 'der Name konnte nicht ermittelt werden',
    'ядер {}, потоков {}': '{} Kerne, {} Threads',
    'оперативной памяти {:.0f} ГБ': '{:.0f} GB Arbeitsspeicher',
    'системный диск {}': 'Systemlaufwerk {}',
    'опрашиваю железо, это занимает несколько секунд…': 'die Hardware wird abgefragt, das dauert ein paar Sekunden…',
    'загрузка процессора': 'Prozessorauslastung',
    'температура процессора': 'Prozessortemperatur',
    'частота процессора': 'Prozessortakt',
    'загрузка памяти': 'Speicherauslastung',
    'загрузка диска': 'Laufwerksauslastung',
    'приём из сети': 'Netzwerk-Empfang',
    'загрузка видеокарты': 'Grafikkartenauslastung',
    'температура видеокарты': 'Grafikkartentemperatur',
    'занято видеопамяти': 'belegter Grafikspeicher',
    'потребление видеокарты': 'Grafikkartenverbrauch',
    'не читается': 'nicht lesbar',
    'температура читается': 'die Temperatur ist lesbar',
    'выбран датчик: ': 'gewählter Sensor: ',
    'источник открылся, но отдаёт нули': 'die Quelle hat sich geöffnet, liefert aber Nullen',
    'библиотека отдаёт нули по всем ядрам: нет прав администратора': 'die Bibliothek liefert bei allen Kernen Nullen: keine Administratorrechte',
    'так бывает без прав администратора: запусти start.bat': 'das passiert ohne Administratorrechte: starte start.bat',
    'источник не найден': 'keine Quelle gefunden',
    'запусти программу через app.bat': 'starte das Programm über app.bat',
    'нужны права администратора и четыре .dll рядом': 'es braucht Administratorrechte und die vier .dll-Dateien daneben',
    'видеокарта читается': 'die Grafikkarte ist lesbar',
    'нет источника показаний': 'es gibt keine Quelle für Messwerte',
    'положи System.Numerics.Vectors.dll рядом с программой': 'leg System.Numerics.Vectors.dll neben das Programm',
    'нужен для видеокарт не Nvidia — на месте': 'wird für Nicht-Nvidia-Karten gebraucht — ist vorhanden',
    'нужен, чтобы читать видеокарту не Nvidia': 'wird gebraucht, um eine Nicht-Nvidia-Grafikkarte auszulesen',
    'особых прав не нужно': 'keine besonderen Rechte nötig',
    'температуры читает ядро, оно их и так отдаёт': 'die Temperaturen liest der Kernel, er liefert sie ohnehin',
    'температуры читает ядро, библиотека датчиков не нужна': 'die Temperaturen liest der Kernel, eine Sensorbibliothek wird nicht gebraucht',
    'ядро Linux': 'der Linux-Kernel',
    'ядро Linux (drm)': 'der Linux-Kernel (drm)',
    'ядро не отдаёт температур: нет /sys/class/hwmon': 'der Kernel liefert keine Temperaturen: /sys/class/hwmon fehlt',
    'ядро не отдаёт показаний видеокарты: нет /sys/class/drm': 'der Kernel liefert keine Grafikkarten-Messwerte: /sys/class/drm fehlt',
    'ядро не выложило /sys/class/hwmon: посмотри, загружен ли модуль датчиков процессора': 'der Kernel hat /sys/class/hwmon nicht bereitgestellt: prüfe, ob das Sensormodul für den Prozessor geladen ist',
    'для Nvidia нужен nvidia-smi, для AMD - драйвер amdgpu в /sys/class/drm': 'für Nvidia wird nvidia-smi gebraucht, für AMD der amdgpu-Treiber in /sys/class/drm',
    'библиотеке не хватает файла System.Numerics.Vectors.dll — без него показаний видеокарты не будет. Возьми его из архива LibreHardwareMonitor': 'der Bibliothek fehlt die Datei System.Numerics.Vectors.dll — ohne sie gibt es keine Grafikkarten-Messwerte. Nimm sie aus dem LibreHardwareMonitor-Archiv',
    'для Nvidia хватит драйвера, для AMD и Intel нужна библиотека датчиков и права': 'für Nvidia reicht der Treiber, AMD und Intel brauchen die Sensorbibliothek und die Rechte',
    'psutil (процессор, память, диски, сеть): ': 'psutil (Prozessor, Speicher, Laufwerke, Netzwerk): ',
    'есть': 'vorhanden',
    'НЕ УСТАНОВЛЕН': 'NICHT INSTALLIERT',
    'процессор: ': 'Prozessor: ',
    'видеокарта: ': 'Grafikkarte: ',
    'показания видеокарты: ': 'Grafikkarten-Messwerte: ',
    'показания видеокарты: НЕТ — ': 'Grafikkarten-Messwerte: KEINE — ',
    'показания видеокарты: НЕТ — нет ни nvidia-smi, ни LibreHardwareMonitorLib.dll': 'Grafikkarten-Messwerte: KEINE — weder nvidia-smi noch LibreHardwareMonitorLib.dll ist vorhanden',
    'температура процессора: читается ({})': 'Prozessortemperatur: lesbar ({})',
    'библиотека напрямую': 'die Bibliothek direkt',
    'через WMI': 'über WMI',
    'способ не указан': 'der Weg ist nicht angegeben',
    ', вспомогательных сборок: {}': ', Hilfsassemblies: {}',
    '  выбран датчик: ': '  gewählter Sensor: ',
    '  все найденные датчики процессора:': '  alle gefundenen Prozessorsensoren:',
    'температура процессора: НЕТ — ': 'Prozessortemperatur: KEINE — ',
    '  ВНИМАНИЕ: программа запущена без прав администратора.': '  ACHTUNG: Das Programm läuft ohne Administratorrechte.',
    '  Температуру процессора без них прочитать невозможно в принципе:': '  Ohne sie lässt sich die Prozessortemperatur grundsätzlich nicht auslesen:',
    '  Windows не даёт доступ к регистрам процессора обычным программам.': '  Windows lässt gewöhnliche Programme nicht an die Prozessorregister.',
    '  Права администратора есть. Положи рядом LibreHardwareMonitorLib.dll': '  Administratorrechte sind vorhanden. Leg LibreHardwareMonitorLib.dll neben das Programm',
    '  и HidSharp.dll, либо запусти саму LibreHardwareMonitor в фоне.': '  und HidSharp.dll, oder starte LibreHardwareMonitor selbst im Hintergrund.',
    'рядом нет LibreHardwareMonitorLib.dll (положи её в папку с программой)': 'LibreHardwareMonitorLib.dll ist nicht vorhanden (leg sie in den Programmordner)',
    'библиотека есть, но нет pythonnet. Выполни: pip install pythonnet': 'die Bibliothek ist vorhanden, aber pythonnet fehlt. Führe aus: pip install pythonnet',
    'библиотека заблокирована Windows как скачанная из интернета. Свойства файла -> галочка «Разблокировать»': 'Windows hat die Bibliothek als aus dem Internet heruntergeladen blockiert. Dateieigenschaften -> Häkchen „Zulassen“',
    'погода: получена{}{}': 'Wetter: erhalten{}{}',
    ' от ': ' von ',
    ' для ': ' für ',
    '  восход и закат: ': '  Sonnenauf- und -untergang: ',
    'погода: НЕТ — ': 'Wetter: KEIN — ',
    'ещё не загружена': 'noch nicht geladen',
    'не выбрано место — укажи город в настройках, раздел «Погода»': 'kein Ort gewählt — gib die Stadt in den Einstellungen an, Abschnitt „Wetter“',
    'не смог заглянуть в порты': 'konnte die Ports nicht einsehen',
    'экран найден': 'Bildschirm gefunden',
    'ни на одном COM-порту': 'auf keinem COM-Port',
    'проверь кабель от помпы к разъёму USB на плате': 'prüfe das Kabel von der Pumpe zum USB-Anschluss auf der Platine',
    'а вот что на портах есть:': 'aber das gibt es an den Ports:',
    'COM-портов не найдено вообще': 'es wurden überhaupt keine COM-Ports gefunden',
    'погода выключена в настройках': 'das Wetter ist in den Einstellungen ausgeschaltet',
    'прогноз получен': 'die Vorhersage ist angekommen',
    'восход {}   закат {}   ({})': 'Aufgang {}   Untergang {}   ({})',
    'свой расчёт': 'eigene Berechnung',
    'прогноза нет': 'keine Vorhersage',
    'источник не ответил': 'die Quelle hat nicht geantwortet',
    'проверь интернет и место в Настройках -> Погода и адрес': 'prüfe das Internet und den Ort in den Einstellungen -> Wetter und Ort',
    'не смог просмотреть темы': 'konnte die Themen nicht durchsehen',
    'названия железа нигде не вписаны руками': 'nirgendwo sind Hardwarenamen von Hand eingetragen',
    '«{}»: {} слоёв с вписанным названием': '„{}“: {} Ebenen mit eingetragenem Namen',
    'Заменить, чтобы тема сама называла ваше железо?': 'Ersetzen, damit das Thema deine eigene Hardware benennt?',
    'оставил как было': 'so gelassen, wie es war',
    'тема поправлена': 'das Thema wurde korrigiert',
    'не смог записать тему': 'konnte das Thema nicht schreiben',
    'Записываю в настройки': 'Schreibe in die Einstellungen',
    'железо записано': 'die Hardware wurde eingetragen',
    'опрос nvidia-smi': 'Abfrage von nvidia-smi',
    'включён': 'eingeschaltet',
    'выключен, он тут не нужен': 'ausgeschaltet, hier nicht gebraucht',
    'Температуру прочитать нечем. Выключить её опрос?': 'Es gibt nichts, um die Temperatur auszulesen. Die Abfrage dafür ausschalten?',
    'опрос температур выключен': 'die Temperaturabfrage ist ausgeschaltet',
    'Итог': 'Fazit',
    'Всё на месте. Запускай app.bat.': 'Alles vorhanden. Starte app.bat.',
    'Без этого программа будет работать не полностью:': 'Ohne diese Dinge läuft das Programm nicht vollständig:',
    'Мелочи, жить можно:': 'Kleinigkeiten, damit lässt sich leben:',
    'Когда поправишь - запусти start.bat ещё раз.': 'Wenn du das behoben hast, starte start.bat noch einmal.',
}

POGODA = {
    0: ("Klar", "Klar"),
    1: ("Klar", "Überwiegend klar"),
    2: ("Wolkig", "Teils bewölkt"),
    3: ("Bedeckt", "Bedeckt"),
    45: ("Nebel", "Nebel"),
    48: ("Nebel", "Raureifnebel"),
    51: ("Niesel", "Leichter Niesel"),
    53: ("Niesel", "Niesel"),
    55: ("Niesel", "Starker Niesel"),
    56: ("Glätte", "Gefrierender Niesel"),
    57: ("Glätte", "Starker gefrierender Niesel"),
    61: ("Regen", "Leichter Regen"),
    63: ("Regen", "Regen"),
    65: ("Regen", "Starker Regen"),
    66: ("Glätte", "Gefrierender Regen"),
    67: ("Glätte", "Starker gefrierender Regen"),
    71: ("Schnee", "Leichter Schnee"),
    73: ("Schnee", "Schnee"),
    75: ("Schnee", "Starker Schnee"),
    77: ("Schnee", "Schneegriesel"),
    80: ("Schauer", "Leichte Schauer"),
    81: ("Schauer", "Schauer"),
    82: ("Schauer", "Starke Schauer"),
    85: ("Schnee", "Schneeschauer"),
    86: ("Schnee", "Starke Schneeschauer"),
    95: ("Gewitter", "Gewitter"),
    96: ("Gewitter", "Gewitter mit Hagel"),
    99: ("Gewitter", "Schweres Gewitter mit Hagel"),
}

SOKRASHENO = {
    56: "Gefr. Niesel",
    57: "Starker gefr. Niesel",
    66: "Gefr. Regen",
    67: "Starker gefr. Regen",
    86: "Starke Schneeschauer",
    99: "Schweres Gew. m. Hagel",
}
